#!/usr/bin/env node
// seed_cookbook_batch_3.mjs — Recipes 101-145 (Summer Shred + Lean Bulk + 15-Min)
// Run: node seed_cookbook_batch_3.mjs

const SB_URL = 'https://korektlpnwuefsagfuvq.supabase.co';
const SB_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvcmVrdGxwbnd1ZWZzYWdmdXZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYwMjI0NjQsImV4cCI6MjA5MTU5ODQ2NH0.46rZOEMUKoZCyL8eKzob8FDuOoFiA2LHbr2ZoKW-HrM';
const H = {'Content-Type':'application/json','apikey':SB_KEY,'Authorization':`Bearer ${SB_KEY}`,'Prefer':'return=representation'};
const q = async (m,p,b) => { const r = await fetch(`${SB_URL}/rest/v1/${p}`,{method:m,headers:H,body:b?JSON.stringify(b):undefined}); return {ok:r.ok,status:r.status,data:await r.json().catch(()=>null)}; };

const RECIPES = [
  // ════════════════════════════════════════════
  // ☀️ SUMMER SHRED (20) — Light, cold, <400kcal
  // ════════════════════════════════════════════
  {title:'Bowl Poulet Mangue Citron Vert',category:'Summer Shred',meal_type:'lunch',goal_tag:'fat_loss',craving_tag:'frais',prep_time:15,difficulty:1,total_calories:385,total_protein:42,total_carbs:38,total_fat:8,featured:true,photo_gradient:'linear-gradient(135deg,#1a1000,#FFD700)',membership_required:'cookbook',
    ingredients:[{name:'Escalope de poulet',quantity:'180g',calories:216,protein:39.6,carbs:0,fat:3.6},{name:'Riz blanc',quantity:'40g cru',calories:144,protein:2.8,carbs:31.2,fat:0.4},{name:'Tomates',quantity:'80g',calories:14,protein:0.7,carbs:3.1,fat:0.2},{name:'Pomme',quantity:'80g',calories:42,protein:0,carbs:11.2,fat:0},{name:'Huile d\'olive',quantity:'4g',calories:36,protein:0,carbs:0,fat:4}],
    steps:['Cuire le riz à l\'eau salée 12 min.','Griller le poulet avec citron vert + coriandre + ail.','Préparer salsa : pomme en dés + tomates + coriandre + lime + sel.','Assembler bowl : riz tiède au fond.','Poulet émincé + salsa fraîche.'],
    substitutions:[{original:'Pomme',alternative:'Vraie mangue 80g si en saison'},{original:'Citron vert',alternative:'Citron jaune même résultat'}],coach_note:'Le poulet caribéen — fraîcheur tropicale même en plein été algérien. La pomme imite parfaitement la mangue.'},

  {title:'Salade Quinoa Thon Tomates',category:'Summer Shred',meal_type:'lunch',goal_tag:'fat_loss',craving_tag:'frais',prep_time:12,difficulty:1,total_calories:365,total_protein:32,total_carbs:32,total_fat:11,featured:false,photo_gradient:'linear-gradient(135deg,#001a00,#6B8E23)',membership_required:'cookbook',
    ingredients:[{name:'Thon naturel',quantity:'120g',calories:139,protein:31.2,carbs:0,fat:1.2},{name:'Riz blanc',quantity:'40g cru',calories:144,protein:2.8,carbs:31.2,fat:0.4},{name:'Tomates',quantity:'150g',calories:27,protein:1.4,carbs:5.9,fat:0.3},{name:'Huile d\'olive',quantity:'6g',calories:54,protein:0,carbs:0,fat:6}],
    steps:['Cuire riz froid (à la place du quinoa).','Égoutter le thon.','Couper tomates en petits dés.','Mélanger riz refroidi + thon + tomates + persil + lime.','Filet d\'huile + sel + poivre.'],
    substitutions:[{original:'Riz',alternative:'Vrai quinoa 40g cru'},{original:'Thon',alternative:'Poulet froid effiloché 120g'}],coach_note:'Le bowl d\'été par excellence. Tout froid, prêt en 12 minutes. Tu peux le préparer la veille.'},

  {title:'Ceviche Poisson Citron',category:'Summer Shred',meal_type:'lunch',goal_tag:'fat_loss',craving_tag:'frais',prep_time:15,difficulty:2,total_calories:285,total_protein:42,total_carbs:14,total_fat:6,featured:true,photo_gradient:'linear-gradient(135deg,#001a1a,#48D1CC)',membership_required:'cookbook',
    ingredients:[{name:'Poisson blanc',quantity:'200g',calories:170,protein:40,carbs:0,fat:2},{name:'Tomates',quantity:'80g',calories:14,protein:0.7,carbs:3.1,fat:0.2},{name:'Pomme',quantity:'50g',calories:26,protein:0,carbs:7,fat:0},{name:'Huile d\'olive',quantity:'5g',calories:45,protein:0,carbs:0,fat:5},{name:'Citron',quantity:'2 jus',calories:30,protein:1,carbs:10,fat:0}],
    steps:['Couper poisson en cubes de 1cm.','Mariner dans jus de citron 15 min — la chaleur acide "cuit" le poisson.','Égoutter, ajouter tomates et pomme en dés.','Coriandre + oignon rouge + piment optionnel.','Huile d\'olive + sel + service immédiat.'],
    substitutions:[{original:'Poisson blanc',alternative:'Crevettes cuites 200g pour version sécurisée'},{original:'Pomme',alternative:'Avocat pour version riche'}],coach_note:'Le ceviche péruvien — version algéroise. Ultra-protéiné, ultra-frais. Poisson EXTRÊMEMENT frais obligatoire.'},

  {title:'Salade Niçoise Fit',category:'Summer Shred',meal_type:'lunch',goal_tag:'fat_loss',craving_tag:'frais',prep_time:15,difficulty:1,total_calories:395,total_protein:38,total_carbs:22,total_fat:18,featured:false,photo_gradient:'linear-gradient(135deg,#0a1a00,#556B2F)',membership_required:'cookbook',
    ingredients:[{name:'Thon naturel',quantity:'120g',calories:139,protein:31.2,carbs:0,fat:1.2},{name:'Œufs durs',quantity:'2 (120g)',calories:140,protein:12,carbs:2,fat:10},{name:'Pommes de terre',quantity:'100g',calories:80,protein:2,carbs:18,fat:0},{name:'Tomates',quantity:'100g',calories:18,protein:0.9,carbs:3.9,fat:0.2},{name:'Huile d\'olive',quantity:'6g',calories:54,protein:0,carbs:0,fat:6}],
    steps:['Cuire pommes de terre 15 min, refroidir.','Cuire œufs durs 8 min, refroidir, couper en quartiers.','Disposer sur lit de salade : PDT, œufs, thon, tomates.','Olives noires 20g optionnelles.','Vinaigrette : huile + vinaigre + moutarde + ail.'],
    substitutions:[{original:'Thon',alternative:'Poulet grillé froid 120g'},{original:'Pommes de terre',alternative:'Haricots verts pour version plus light'}],coach_note:'La niçoise authentique — toujours froide, simple, parfaite. Plat de cut élégant.'},

  {title:'Wraps Frais Crudités Poulet',category:'Summer Shred',meal_type:'lunch',goal_tag:'fat_loss',craving_tag:'frais',prep_time:10,difficulty:1,total_calories:375,total_protein:38,total_carbs:36,total_fat:8,featured:false,photo_gradient:'linear-gradient(135deg,#001a00,#90EE90)',membership_required:'cookbook',
    ingredients:[{name:'Escalope de poulet',quantity:'150g',calories:180,protein:33,carbs:0,fat:3},{name:'Pain ARRUPAN',quantity:'90g',calories:240,protein:8,carbs:44,fat:3},{name:'Fromage frais Lactel 0%',quantity:'50g',calories:45,protein:4.3,carbs:2.2,fat:1.8},{name:'Tomates',quantity:'60g',calories:11,protein:0.5,carbs:2.3,fat:0.2}],
    steps:['Cuire poulet, refroidir, émincer.','Étaler fromage frais sur pain ARRUPAN.','Ajouter poulet froid, tomates, salade, concombre.','Rouler serré.','Couper en deux, servir avec tranches de pomme.'],
    substitutions:[{original:'Poulet',alternative:'Thon 150g pour version pêcheur'},{original:'Tomates',alternative:'Avocat pour version crémeuse'}],coach_note:'Le wrap froid — bureau, pique-nique, plage. Tient parfaitement plusieurs heures.'},

  {title:'Bowl Poulet Concombre Yaourt',category:'Summer Shred',meal_type:'lunch',goal_tag:'fat_loss',craving_tag:'frais',prep_time:12,difficulty:1,total_calories:340,total_protein:42,total_carbs:24,total_fat:8,featured:false,photo_gradient:'linear-gradient(135deg,#001a1a,#5F9EA0)',membership_required:'cookbook',
    ingredients:[{name:'Escalope de poulet',quantity:'180g',calories:216,protein:39.6,carbs:0,fat:3.6},{name:'Concombre',quantity:'200g',calories:32,protein:1.4,carbs:7.2,fat:0.2},{name:'Riz blanc',quantity:'30g cru',calories:108,protein:2.1,carbs:23.4,fat:0.3},{name:'Fromage frais Lactel 0%',quantity:'50g',calories:45,protein:4.3,carbs:2.2,fat:1.8}],
    steps:['Cuire poulet aux épices grecques (origan + ail + citron).','Cuire riz, refroidir.','Râper concombre, presser pour enlever eau.','Sauce tzatziki : concombre + fromage frais + ail + menthe.','Servir : riz froid + poulet + sauce généreuse.'],
    substitutions:[{original:'Poulet grec',alternative:'Poisson grillé pour version méditerranéenne'},{original:'Riz',alternative:'Quinoa pour version supérieure'}],coach_note:'Le bowl grec — fraîcheur méditerranéenne. La sauce tzatziki maison change tout.'},

  {title:'Salade Pâtes Froides Poulet',category:'Summer Shred',meal_type:'lunch',goal_tag:'all',craving_tag:'frais',prep_time:15,difficulty:1,total_calories:395,total_protein:38,total_carbs:46,total_fat:6,featured:false,photo_gradient:'linear-gradient(135deg,#1a1000,#DAA520)',membership_required:'cookbook',
    ingredients:[{name:'Escalope de poulet',quantity:'150g',calories:180,protein:33,carbs:0,fat:3},{name:'Pâtes',quantity:'60g cru',calories:210,protein:7.2,carbs:43.2,fat:1.2},{name:'Tomates',quantity:'100g',calories:18,protein:0.9,carbs:3.9,fat:0.2},{name:'Fromage frais Lactel 0%',quantity:'40g',calories:36,protein:3.4,carbs:1.7,fat:1.4}],
    steps:['Cuire pâtes al dente, rincer eau froide.','Cuire poulet, refroidir, couper en dés.','Préparer sauce : fromage frais + moutarde + basilic + ail.','Mélanger pâtes + poulet + tomates + sauce.','Frigo 30 min avant service.'],
    substitutions:[{original:'Sauce fromage frais',alternative:'Pesto maison pour version italienne'},{original:'Poulet',alternative:'Thon 150g pour version pêcheur'}],coach_note:'Les pâtes froides du déjeuner. Préparées la veille = lunch box parfait.'},

  {title:'Carpaccio Courgettes Œuf',category:'Summer Shred',meal_type:'lunch',goal_tag:'fat_loss',craving_tag:'frais',prep_time:10,difficulty:2,total_calories:265,total_protein:18,total_carbs:14,total_fat:14,featured:false,photo_gradient:'linear-gradient(135deg,#001a00,#9ACD32)',membership_required:'cookbook',
    ingredients:[{name:'Courgettes',quantity:'200g',calories:34,protein:2.6,carbs:5,fat:0.6},{name:'Œufs durs',quantity:'2 (120g)',calories:140,protein:12,carbs:2,fat:10},{name:'Fromage frais Lactel 0%',quantity:'40g',calories:36,protein:3.4,carbs:1.7,fat:1.4},{name:'Huile d\'olive',quantity:'5g',calories:45,protein:0,carbs:0,fat:5}],
    steps:['Trancher courgettes à l\'économe en lamelles fines.','Disposer en rosace sur l\'assiette.','Œufs durs en quartiers par-dessus.','Cuillerées de fromage frais en points.','Huile d\'olive + citron + sel.'],
    substitutions:[{original:'Œufs durs',alternative:'120g thon égoutté'},{original:'Courgettes',alternative:'Concombre pour version encore plus light'}],coach_note:'Le carpaccio italien — version courgettes. Visuel digne d\'un resto. Repas du soir d\'été parfait.'},

  {title:'Tabouleh Express Quinoa',category:'Summer Shred',meal_type:'lunch',goal_tag:'fat_loss',craving_tag:'frais',prep_time:10,difficulty:1,total_calories:295,total_protein:24,total_carbs:32,total_fat:6,featured:false,photo_gradient:'linear-gradient(135deg,#001a00,#7CFC00)',membership_required:'cookbook',
    ingredients:[{name:'Riz blanc',quantity:'40g cru',calories:144,protein:2.8,carbs:31.2,fat:0.4},{name:'Thon naturel',quantity:'100g',calories:116,protein:26,carbs:0,fat:1},{name:'Tomates',quantity:'150g',calories:27,protein:1.4,carbs:5.9,fat:0.3},{name:'Huile d\'olive',quantity:'3g',calories:27,protein:0,carbs:0,fat:3}],
    steps:['Cuire riz, rincer eau froide.','Hacher persil + menthe finement (50g total).','Couper tomates en mini dés.','Mélanger riz + thon + tomates + herbes.','Huile + citron généreusement + sel.'],
    substitutions:[{original:'Riz',alternative:'Vrai boulgour 40g pour version libanaise authentique'},{original:'Thon',alternative:'Poulet froid émincé 100g'}],coach_note:'Le taboulé libanais avec protéine. La menthe est obligatoire. Test ce plat même si tu ne crois pas.'},

  {title:'Salade César Poulet Light',category:'Summer Shred',meal_type:'lunch',goal_tag:'fat_loss',craving_tag:'frais',prep_time:12,difficulty:1,total_calories:355,total_protein:42,total_carbs:18,total_fat:14,featured:true,photo_gradient:'linear-gradient(135deg,#1a1000,#F0E68C)',membership_required:'cookbook',
    ingredients:[{name:'Escalope de poulet',quantity:'180g',calories:216,protein:39.6,carbs:0,fat:3.6},{name:'Pain ARRUPAN',quantity:'30g',calories:80,protein:2.7,carbs:14.7,fat:1},{name:'Fromage frais Lactel 0%',quantity:'60g',calories:53,protein:5.2,carbs:2.6,fat:2.1},{name:'Œuf entier',quantity:'1 (60g)',calories:70,protein:6,carbs:1,fat:5},{name:'Huile d\'olive',quantity:'5g',calories:45,protein:0,carbs:0,fat:5}],
    steps:['Cuire poulet aux herbes italiennes.','Toaster pain ARRUPAN coupé en cubes (croûtons).','Sauce César light : fromage frais + jaune cuit écrasé + moutarde + ail + citron + parmesan râpé.','Salade romaine en grosses lamelles.','Assembler : salade + poulet émincé + croûtons + sauce.'],
    substitutions:[{original:'Sauce César',alternative:'Mayo light 30g + ail pour version simplifiée'},{original:'Poulet',alternative:'Crevettes pour version pêcheur'}],coach_note:'La César classique — sauce maison avec fromage frais au lieu de mayo. 300 kcal de moins.'},

  {title:'Verrines Poulet Crudités',category:'Summer Shred',meal_type:'lunch',goal_tag:'fat_loss',craving_tag:'frais',prep_time:10,difficulty:1,total_calories:295,total_protein:36,total_carbs:18,total_fat:8,featured:false,photo_gradient:'linear-gradient(135deg,#1a0a00,#FFA07A)',membership_required:'cookbook',
    ingredients:[{name:'Escalope de poulet',quantity:'150g',calories:180,protein:33,carbs:0,fat:3},{name:'Tomates',quantity:'150g',calories:27,protein:1.4,carbs:5.9,fat:0.3},{name:'Concombre',quantity:'100g',calories:16,protein:0.7,carbs:3.6,fat:0.1},{name:'Fromage frais Lactel 0%',quantity:'60g',calories:53,protein:5.2,carbs:2.6,fat:2.1},{name:'Huile d\'olive',quantity:'2g',calories:18,protein:0,carbs:0,fat:2}],
    steps:['Cuire poulet, refroidir, couper en dés.','Hacher tomates et concombre en brunoise.','Dans verres : couche concombre, couche poulet, couche tomates.','Sommet : cuillère de fromage frais aux herbes.','Présenter chic — repas d\'invités.'],
    substitutions:[{original:'Poulet',alternative:'Thon 150g pour version pêcheur'},{original:'Verres',alternative:'Bowl si pas l\'envie de présenter'}],coach_note:'Les verrines apéro qui deviennent repas. Présentation Instagram, macros parfaites.'},

  {title:'Crevettes Citron Avocat',category:'Summer Shred',meal_type:'lunch',goal_tag:'fat_loss',craving_tag:'frais',prep_time:10,difficulty:1,total_calories:335,total_protein:32,total_carbs:14,total_fat:18,featured:false,photo_gradient:'linear-gradient(135deg,#1a0000,#FF6347)',membership_required:'cookbook',
    ingredients:[{name:'Crevettes',quantity:'200g',calories:190,protein:36,carbs:1,fat:4},{name:'Avocat',quantity:'60g',calories:96,protein:1.2,carbs:5.4,fat:9},{name:'Tomates',quantity:'80g',calories:14,protein:0.7,carbs:3.1,fat:0.2},{name:'Huile d\'olive',quantity:'4g',calories:36,protein:0,carbs:0,fat:4}],
    steps:['Cuire crevettes à l\'eau bouillante 3 min, refroidir.','Écraser avocat avec citron, sel, coriandre.','Couper tomates en cubes.','Disposer : avocat écrasé en base, crevettes dessus, tomates.','Citron généreux + huile d\'olive.'],
    substitutions:[{original:'Crevettes',alternative:'Poisson blanc cuit 200g'},{original:'Avocat',alternative:'Fromage frais 60g pour version moins grasse -50kcal'}],coach_note:'Le plat romantique d\'été. Mexicain dans l\'esprit, méditerranéen dans les ingrédients.'},

  {title:'Œufs Mimosa Avocat',category:'Summer Shred',meal_type:'lunch',goal_tag:'fat_loss',craving_tag:'frais',prep_time:15,difficulty:2,total_calories:325,total_protein:24,total_carbs:8,total_fat:22,featured:false,photo_gradient:'linear-gradient(135deg,#1a1000,#FFFF00)',membership_required:'cookbook',
    ingredients:[{name:'Œufs durs',quantity:'4 (240g)',calories:280,protein:24,carbs:4,fat:20},{name:'Avocat',quantity:'30g',calories:48,protein:0.6,carbs:2.7,fat:4.5},{name:'Fromage frais Lactel 0%',quantity:'30g',calories:27,protein:2.6,carbs:1.3,fat:1.1},{name:'Tomates',quantity:'30g',calories:5,protein:0.3,carbs:1.2,fat:0.1}],
    steps:['Cuire œufs durs 9 min, refroidir.','Couper en deux, retirer jaunes.','Mélanger jaunes + fromage frais + avocat + citron + sel.','Remplir blancs avec préparation à la poche.','Décorer avec paprika et persil.'],
    substitutions:[{original:'Avocat',alternative:'Plus de fromage frais pour version sans avocat -50kcal'},{original:'Œufs durs',alternative:'Œufs cuits 8 min pour jaune plus crémeux'}],coach_note:'Les œufs mimosa de mariage — version moderne. Apéro chic ou repas léger.'},

  {title:'Poke Bowl Thon Riz Vinaigre',category:'Summer Shred',meal_type:'lunch',goal_tag:'all',craving_tag:'frais',prep_time:15,difficulty:1,total_calories:395,total_protein:38,total_carbs:42,total_fat:8,featured:true,photo_gradient:'linear-gradient(135deg,#001a1a,#20B2AA)',membership_required:'cookbook',
    ingredients:[{name:'Thon naturel',quantity:'150g',calories:174,protein:39,carbs:0,fat:1.5},{name:'Riz blanc',quantity:'50g cru',calories:180,protein:3.5,carbs:39,fat:0.5},{name:'Avocat',quantity:'30g',calories:48,protein:0.6,carbs:2.7,fat:4.5},{name:'Tomates',quantity:'50g',calories:9,protein:0.5,carbs:2,fat:0.1},{name:'Huile d\'olive',quantity:'1g',calories:9,protein:0,carbs:0,fat:1}],
    steps:['Cuire riz, assaisonner vinaigre de riz + sucre + sel après cuisson.','Bowl : riz vinaigré en base.','Thon en cubes ou émietté.','Avocat tranché + tomates.','Sauce soja + sésame + gingembre + lime.'],
    substitutions:[{original:'Thon naturel',alternative:'Saumon frais (sushi grade) pour version cru'},{original:'Sauce soja',alternative:'Tamari sans gluten'}],coach_note:'Le poke hawaïen — protéine + glucides + bons gras parfaitement équilibrés. Bowl le plus populaire des coachs.'},

  {title:'Salade Lentilles Poulet Menthe',category:'Summer Shred',meal_type:'lunch',goal_tag:'all',craving_tag:'frais',prep_time:12,difficulty:1,total_calories:395,total_protein:40,total_carbs:38,total_fat:7,featured:false,photo_gradient:'linear-gradient(135deg,#001a00,#228B22)',membership_required:'cookbook',
    ingredients:[{name:'Escalope de poulet',quantity:'130g',calories:156,protein:28.6,carbs:0,fat:2.6},{name:'Lentilles vertes cuites',quantity:'150g',calories:173,protein:13.5,carbs:28.5,fat:0.8},{name:'Tomates',quantity:'80g',calories:14,protein:0.7,carbs:3.1,fat:0.2},{name:'Huile d\'olive',quantity:'5g',calories:45,protein:0,carbs:0,fat:5}],
    steps:['Cuire poulet, refroidir, émincer.','Mélanger lentilles tièdes + poulet + tomates.','Vinaigrette : huile + vinaigre + moutarde + ail + menthe.','Mélanger délicatement.','Servir frais ou température ambiante.'],
    substitutions:[{original:'Lentilles vertes',alternative:'Lentilles corail cuites + 5 min'},{original:'Menthe',alternative:'Coriandre fraîche pour version différente'}],coach_note:'Les lentilles froides — protéine végétale + animale + fibres. Plat de cut élégant et économique.'},

  {title:'Brochettes Poulet Tomates Concombre',category:'Summer Shred',meal_type:'dinner',goal_tag:'fat_loss',craving_tag:'frais',prep_time:15,difficulty:2,total_calories:325,total_protein:42,total_carbs:10,total_fat:13,featured:false,photo_gradient:'linear-gradient(135deg,#1a0000,#FF6347)',membership_required:'cookbook',
    ingredients:[{name:'Escalope de poulet',quantity:'180g',calories:216,protein:39.6,carbs:0,fat:3.6},{name:'Tomates',quantity:'150g',calories:27,protein:1.4,carbs:5.9,fat:0.3},{name:'Concombre',quantity:'150g',calories:24,protein:1.1,carbs:5.4,fat:0.2},{name:'Fromage frais Lactel 0%',quantity:'40g',calories:36,protein:3.4,carbs:1.7,fat:1.4},{name:'Huile d\'olive',quantity:'3g',calories:27,protein:0,carbs:0,fat:3}],
    steps:['Couper poulet en cubes 3cm.','Mariner : huile + paprika + ail + thym + sel 15 min.','Brochettes alternant poulet, tomates cerises, concombre.','BBQ ou grill du four 8-10 min en tournant.','Sauce tzatziki : fromage frais + concombre râpé + ail.'],
    substitutions:[{original:'Poulet',alternative:'Crevettes pour version mer'},{original:'BBQ',alternative:'Poêle bien chaude pour effet grill'}],coach_note:'Le BBQ d\'été — poulet ultra simple. La marinade fait tout le travail.'},

  {title:'Soupe Froide Tomate Basilic',category:'Summer Shred',meal_type:'lunch',goal_tag:'fat_loss',craving_tag:'frais',prep_time:8,difficulty:1,total_calories:185,total_protein:14,total_carbs:18,total_fat:6,featured:false,photo_gradient:'linear-gradient(135deg,#1a0000,#FF6347)',membership_required:'cookbook',
    ingredients:[{name:'Tomates',quantity:'400g',calories:72,protein:3.6,carbs:15.6,fat:0.8},{name:'Fromage frais Lactel 0%',quantity:'100g',calories:89,protein:8.6,carbs:4.3,fat:3.5},{name:'Huile d\'olive',quantity:'2g',calories:18,protein:0,carbs:0,fat:2},{name:'Pain ARRUPAN',quantity:'15g',calories:40,protein:1.3,carbs:7.3,fat:0.5}],
    steps:['Mixer tomates + fromage frais + ail + basilic + huile + sel.','Frigo 1h minimum pour servir bien froid.','Toaster cubes de pain ARRUPAN (croûtons).','Servir dans verres ou bols.','Décorer basilic frais.'],
    substitutions:[{original:'Tomates fraîches',alternative:'Tomates en boîte de qualité hors saison'},{original:'Basilic',alternative:'Menthe fraîche pour version méditerranéenne'}],coach_note:'Le gazpacho espagnol — version protéinée. Repas frais quand il fait 40°C dehors.'},

  {title:'Tartare Bœuf Câpres',category:'Summer Shred',meal_type:'dinner',goal_tag:'muscle',craving_tag:'frais',prep_time:10,difficulty:2,total_calories:385,total_protein:38,total_carbs:6,total_fat:22,featured:false,photo_gradient:'linear-gradient(135deg,#1a0000,#8B0000)',membership_required:'cookbook',
    ingredients:[{name:'Steak haché cru',quantity:'150g',calories:375,protein:39,carbs:0,fat:25.5},{name:'Œuf entier',quantity:'1 jaune (20g)',calories:55,protein:2.7,carbs:0.5,fat:4.5},{name:'Fromage frais Lactel 0%',quantity:'30g',calories:27,protein:2.6,carbs:1.3,fat:1.1},{name:'Tomates',quantity:'30g',calories:5,protein:0.3,carbs:1.2,fat:0.1}],
    steps:['Steak EXTRA frais haché à la dernière minute.','Mélanger viande + câpres hachées + persil + moutarde + Worcestershire.','Sel, poivre, dash de Tabasco.','Former dôme sur assiette, creuser un puits.','Casser jaune cru au centre + fromage frais à côté.'],
    substitutions:[{original:'Bœuf cru',alternative:'Saumon cru en cubes pour tartare de saumon'},{original:'Jaune cru',alternative:'Œuf poché si version sans cru'}],coach_note:'Le tartare français — restaurant à la maison. Viande HACHÉE à la commande obligatoire pour sécurité.'},

  {title:'Salade Pasta Pesto Light',category:'Summer Shred',meal_type:'lunch',goal_tag:'all',craving_tag:'frais',prep_time:10,difficulty:1,total_calories:395,total_protein:32,total_carbs:48,total_fat:10,featured:false,photo_gradient:'linear-gradient(135deg,#001a00,#228B22)',membership_required:'cookbook',
    ingredients:[{name:'Pâtes',quantity:'60g cru',calories:210,protein:7.2,carbs:43.2,fat:1.2},{name:'Escalope de poulet',quantity:'120g',calories:144,protein:26.4,carbs:0,fat:2.4},{name:'Tomates',quantity:'80g',calories:14,protein:0.7,carbs:3.1,fat:0.2},{name:'Fromage frais Lactel 0%',quantity:'30g',calories:27,protein:2.6,carbs:1.3,fat:1.1}],
    steps:['Cuire pâtes al dente, rincer froid.','Cuire poulet, refroidir, émincer.','Pesto light : basilic + ail + huile + fromage frais + 5g pignons.','Mélanger pâtes + poulet + pesto.','Tomates cerises coupées en deux.'],
    substitutions:[{original:'Pesto',alternative:'Sauce tomate froide pour version simple'},{original:'Pâtes',alternative:'Riz refroidi 60g cru'}],coach_note:'Les pâtes au pesto — version protéinée et light. Le pesto au fromage frais a 80% moins de gras.'},

  {title:'Bowl Saumon Mariné Cru',category:'Summer Shred',meal_type:'lunch',goal_tag:'fat_loss',craving_tag:'frais',prep_time:15,difficulty:2,total_calories:385,total_protein:36,total_carbs:32,total_fat:12,featured:true,photo_gradient:'linear-gradient(135deg,#1a0000,#FA8072)',membership_required:'cookbook',
    ingredients:[{name:'Saumon frais (sushi grade)',quantity:'150g',calories:312,protein:30,carbs:0,fat:19.5},{name:'Riz blanc',quantity:'40g cru',calories:144,protein:2.8,carbs:31.2,fat:0.4},{name:'Tomates',quantity:'60g',calories:11,protein:0.5,carbs:2.3,fat:0.2},{name:'Avocat',quantity:'30g',calories:48,protein:0.6,carbs:2.7,fat:4.5}],
    steps:['Mariner saumon cru en cubes : sauce soja + sésame + gingembre + ail 15 min.','Cuire riz, refroidir.','Bowl : riz, saumon mariné, tomates, avocat.','Sauce : soja + lime + sésame + huile sésame.','Coriandre fraîche + graines de sésame.'],
    substitutions:[{original:'Saumon cru',alternative:'Saumon cuit 150g si pas de sushi grade'},{original:'Riz',alternative:'Quinoa 40g cru'}],coach_note:'Le poke saumon authentique. Saumon FRAIS d\'aujourd\'hui obligatoire. Demande à ton poissonnier "sushi grade".'},

  // ════════════════════════════════════════════
  // 💪 LEAN BULK (20) — 700+kcal, dense, satisfaisant
  // ════════════════════════════════════════════
  {title:'Mass Bowl Riz Poulet Avocat',category:'Lean Bulk',meal_type:'dinner',goal_tag:'muscle',craving_tag:'chaud',prep_time:15,difficulty:1,total_calories:745,total_protein:54,total_carbs:78,total_fat:22,featured:true,photo_gradient:'linear-gradient(135deg,#1a0a00,#FFD700)',membership_required:'cookbook',
    ingredients:[{name:'Escalope de poulet',quantity:'220g',calories:264,protein:48.4,carbs:0,fat:4.4},{name:'Riz blanc',quantity:'100g cru',calories:360,protein:7,carbs:78,fat:1},{name:'Avocat',quantity:'60g',calories:96,protein:1.2,carbs:5.4,fat:9},{name:'Tomates',quantity:'80g',calories:14,protein:0.7,carbs:3.1,fat:0.2},{name:'Huile d\'olive',quantity:'10g',calories:90,protein:0,carbs:0,fat:10}],
    steps:['Cuire le riz généreusement avec un cube de bouillon.','Cuire le poulet aux épices fortes (paprika + cumin + ail).','Trancher avocat.','Bowl : riz au fond, poulet, avocat, tomates.','Filet d\'huile d\'olive abondant + citron + sel.'],
    substitutions:[{original:'Avocat',alternative:'30g beurre de cacahuète pour bons gras'},{original:'Poulet',alternative:'Steak haché 200g pour bulk plus gras'}],coach_note:'Le mass bowl de prise — densité calorique optimale. Tu manges juste assez pour pas te dégoûter du surplus.'},

  {title:'Pâtes Bolognaise Maison Riche',category:'Lean Bulk',meal_type:'dinner',goal_tag:'muscle',craving_tag:'chaud',prep_time:25,difficulty:2,total_calories:785,total_protein:52,total_carbs:88,total_fat:22,featured:true,photo_gradient:'linear-gradient(135deg,#1a0000,#B22222)',membership_required:'cookbook',
    ingredients:[{name:'Steak haché',quantity:'180g',calories:450,protein:46.8,carbs:0,fat:30.6},{name:'Pâtes',quantity:'120g cru',calories:420,protein:14.4,carbs:86.4,fat:2.4},{name:'Tomates',quantity:'150g',calories:27,protein:1.4,carbs:5.9,fat:0.3},{name:'Huile d\'olive',quantity:'10g',calories:90,protein:0,carbs:0,fat:10}],
    steps:['Faire revenir le steak haché à feu vif jusqu\'à doré.','Ajouter oignon, ail, tomates concassées, herbes italiennes.','Mijoter 15 min à feu doux pour épaississement.','Cuire pâtes al dente.','Mélanger sauce + pâtes + parmesan 5g optionnel + basilic frais.'],
    substitutions:[{original:'Steak haché',alternative:'Mélange bœuf + dinde pour version moins grasse'},{original:'Pâtes longues',alternative:'Lasagnes en couches'}],coach_note:'Les pâtes bolo classiques — portion bulk généreuse. La sauce maison a 70% moins de sel que celle en pot.'},

  {title:'Bowl Avoine Beurre Cacahuète Banane',category:'Lean Bulk',meal_type:'breakfast',goal_tag:'muscle',craving_tag:'sucré',prep_time:8,difficulty:1,total_calories:725,total_protein:32,total_carbs:88,total_fat:22,featured:false,photo_gradient:'linear-gradient(135deg,#1a0800,#A0522D)',membership_required:'cookbook',
    ingredients:[{name:'Flocons d\'avoine',quantity:'120g',calories:456,protein:15.6,carbs:72,fat:8.4},{name:'Fromage frais Lactel 0%',quantity:'150g',calories:134,protein:12.9,carbs:6.5,fat:5.3},{name:'Banane',quantity:'100g',calories:89,protein:1,carbs:23,fat:0},{name:'Beurre de cacahuète',quantity:'15g',calories:90,protein:3.75,carbs:3,fat:7.5}],
    steps:['Cuire avoine avec 350ml de lait écrémé 5 min.','Hors du feu, incorporer fromage frais.','Trancher banane par-dessus.','Beurre de cacahuète en topping généreux.','Cannelle + cacao optionnel.'],
    substitutions:[{original:'Beurre cacahuète',alternative:'25g amandes ou noix'},{original:'Banane',alternative:'Fruits rouges 100g + 10g miel'}],coach_note:'Le porridge bulk — petit déj de 725 kcal qui passe sans effort. Tu mangerais 3 cookies pour la même chose.'},

  {title:'Sandwich Triple Étage Bulk',category:'Lean Bulk',meal_type:'lunch',goal_tag:'muscle',craving_tag:'fast food',prep_time:12,difficulty:1,total_calories:765,total_protein:62,total_carbs:62,total_fat:24,featured:false,photo_gradient:'linear-gradient(135deg,#1a0800,#8B4513)',membership_required:'cookbook',
    ingredients:[{name:'Pain ARRUPAN',quantity:'180g (4 tranches)',calories:480,protein:16,carbs:88,fat:6},{name:'Escalope de poulet',quantity:'200g',calories:240,protein:44,carbs:0,fat:4},{name:'Œufs durs',quantity:'2 (120g)',calories:140,protein:12,carbs:2,fat:10},{name:'Fromage frais Lactel 0%',quantity:'60g',calories:53,protein:5.2,carbs:2.6,fat:2.1},{name:'Avocat',quantity:'40g',calories:64,protein:0.8,carbs:3.6,fat:6}],
    steps:['Toaster les 4 tranches de pain.','Cuire poulet aux épices, refroidir, émincer.','Étaler fromage frais sur chaque tranche.','Étage 1 : poulet + avocat. Étage 2 : œufs durs + tomates.','Sauce moutarde + miel + ail au final.'],
    substitutions:[{original:'4 tranches',alternative:'Bagel format XL = même calories'},{original:'2 œufs',alternative:'80g thon égoutté'}],coach_note:'Le club sandwich bulk. 765 kcal dans un sandwich qui passe. Plus efficace qu\'un shake.'},

  {title:'Riz Cantonais Bulk Poulet',category:'Lean Bulk',meal_type:'dinner',goal_tag:'muscle',craving_tag:'chaud',prep_time:18,difficulty:2,total_calories:735,total_protein:48,total_carbs:88,total_fat:18,featured:false,photo_gradient:'linear-gradient(135deg,#1a1000,#FFD700)',membership_required:'cookbook',
    ingredients:[{name:'Escalope de poulet',quantity:'180g',calories:216,protein:39.6,carbs:0,fat:3.6},{name:'Riz blanc',quantity:'100g cru',calories:360,protein:7,carbs:78,fat:1},{name:'Œufs entiers',quantity:'2 (120g)',calories:140,protein:12,carbs:2,fat:10},{name:'Huile d\'olive',quantity:'8g',calories:72,protein:0,carbs:0,fat:8},{name:'Petits pois',quantity:'80g',calories:64,protein:5.6,carbs:11.2,fat:0.5}],
    steps:['Cuire riz la veille (mieux pour version cantonaise).','Faire revenir poulet en dés.','Pousser sur le côté, casser œufs et brouiller.','Ajouter riz cuit + petits pois + sauce soja.','Mélanger TOUT à feu vif 3 min. Ciboule fraîche au final.'],
    substitutions:[{original:'Riz',alternative:'Quinoa 100g pour version plus protéinée'},{original:'Sauce soja',alternative:'Tamari sans gluten'}],coach_note:'Le riz cantonais asiatique — bulk dense, économique, savoureux. Truc de chef : riz FROID de la veille pour vraie texture.'},

  {title:'Burger XL Double Steak Avocat',category:'Lean Bulk',meal_type:'dinner',goal_tag:'muscle',craving_tag:'fast food',prep_time:15,difficulty:2,total_calories:825,total_protein:64,total_carbs:48,total_fat:38,featured:true,photo_gradient:'linear-gradient(135deg,#1a0000,#8B0000)',membership_required:'cookbook',
    ingredients:[{name:'Steak haché',quantity:'250g',calories:625,protein:65,carbs:0,fat:42.5},{name:'Pain ARRUPAN',quantity:'90g',calories:240,protein:8,carbs:44,fat:3},{name:'Avocat',quantity:'40g',calories:64,protein:0.8,carbs:3.6,fat:6},{name:'Fromage frais Lactel 0%',quantity:'50g',calories:45,protein:4.3,carbs:2.2,fat:1.8}],
    steps:['Former 2 steaks de 125g, sel et poivre généreux.','Poêle ultra chaude, 3 min par côté pour saignant.','Toaster pain ARRUPAN avec un peu d\'huile.','Étaler fromage frais + sauce burger.','Empiler : pain, steak, fromage frais, steak, avocat, tomate, pain.'],
    substitutions:[{original:'2 steaks',alternative:'1 steak de 200g pour version moins extrême'},{original:'Avocat',alternative:'Bacon fumé 30g pour version plus salée'}],coach_note:'Le double burger bulk — 825 calories de pure satisfaction. Une fois par semaine, c\'est carburant.'},

  {title:'Mac and Cheese Protéiné',category:'Lean Bulk',meal_type:'dinner',goal_tag:'muscle',craving_tag:'chaud',prep_time:18,difficulty:2,total_calories:735,total_protein:52,total_carbs:72,total_fat:24,featured:false,photo_gradient:'linear-gradient(135deg,#1a1000,#FFD700)',membership_required:'cookbook',
    ingredients:[{name:'Pâtes',quantity:'100g cru',calories:350,protein:12,carbs:72,fat:2},{name:'Escalope de poulet',quantity:'150g',calories:180,protein:33,carbs:0,fat:3},{name:'Fromage frais Lactel 0%',quantity:'200g',calories:178,protein:17.2,carbs:8.6,fat:7},{name:'Huile d\'olive',quantity:'10g',calories:90,protein:0,carbs:0,fat:10}],
    steps:['Cuire pâtes al dente.','Cuire poulet en dés à part.','Sauce : fromage frais + lait + moutarde + ail + paprika.','Mélanger pâtes + poulet + sauce.','Option : 4 min sous le grill pour version "baked".'],
    substitutions:[{original:'Sauce fromage frais',alternative:'30g cheddar pour version classique +100kcal'},{original:'Poulet',alternative:'Steak haché 150g pour version riche'}],coach_note:'Le mac and cheese américain — comfort food par excellence. Version protéinée 70% moins de gras.'},

  {title:'Bowl Avoine PB Banane Choco',category:'Lean Bulk',meal_type:'breakfast',goal_tag:'muscle',craving_tag:'sucré',prep_time:8,difficulty:1,total_calories:725,total_protein:30,total_carbs:84,total_fat:24,featured:false,photo_gradient:'linear-gradient(135deg,#1a0800,#8B4513)',membership_required:'cookbook',
    ingredients:[{name:'Flocons d\'avoine',quantity:'100g',calories:380,protein:13,carbs:60,fat:7},{name:'Fromage frais Lactel 0%',quantity:'150g',calories:134,protein:12.9,carbs:6.5,fat:5.3},{name:'Banane',quantity:'120g',calories:107,protein:1.2,carbs:27.6,fat:0},{name:'Beurre de cacahuète',quantity:'20g',calories:120,protein:5,carbs:4,fat:10},{name:'Cacao en poudre',quantity:'5g',calories:12,protein:0.5,carbs:1.8,fat:0.4}],
    steps:['Cuire avoine avec lait écrémé 250ml.','Incorporer cacao + cannelle pendant cuisson.','Hors du feu : fromage frais.','Banane tranchée par-dessus.','Beurre de cacahuète en filet généreux.'],
    substitutions:[{original:'Banane',alternative:'80g datte hachée'},{original:'PB',alternative:'30g amandes effilées'}],coach_note:'Le bowl le plus calorique en moins de 800 kcal. Pour les jours où le bulk est dur à atteindre.'},

  {title:'Pâtes Crémeuses Poulet Bacon',category:'Lean Bulk',meal_type:'dinner',goal_tag:'muscle',craving_tag:'chaud',prep_time:18,difficulty:2,total_calories:755,total_protein:58,total_carbs:72,total_fat:22,featured:false,photo_gradient:'linear-gradient(135deg,#1a0800,#FAEBD7)',membership_required:'cookbook',
    ingredients:[{name:'Pâtes',quantity:'100g cru',calories:350,protein:12,carbs:72,fat:2},{name:'Escalope de poulet',quantity:'180g',calories:216,protein:39.6,carbs:0,fat:3.6},{name:'Escalope de dinde fumée',quantity:'40g',calories:44,protein:8.8,carbs:0,fat:0.4},{name:'Fromage frais Lactel 0%',quantity:'150g',calories:134,protein:12.9,carbs:6.5,fat:5.3},{name:'Huile d\'olive',quantity:'1g',calories:9,protein:0,carbs:0,fat:1}],
    steps:['Cuire pâtes al dente.','Faire revenir dinde fumée jusqu\'à croustillante (bacon).','Cuire poulet en dés à part.','Sauce : fromage frais + ail + moutarde + parmesan râpé.','Mélanger tout + persil + poivre noir.'],
    substitutions:[{original:'Dinde fumée',alternative:'Vrai bacon 30g +100kcal'},{original:'Sauce',alternative:'Crème fraîche pour version classique +200kcal'}],coach_note:'La carbonara remixée. Le bacon fumé dinde a 75% moins de gras mais le goût du bacon classique.'},

  {title:'Wraps Triple Bulk',category:'Lean Bulk',meal_type:'lunch',goal_tag:'muscle',craving_tag:'fast food',prep_time:15,difficulty:1,total_calories:790,total_protein:62,total_carbs:78,total_fat:22,featured:false,photo_gradient:'linear-gradient(135deg,#1a1000,#DAA520)',membership_required:'cookbook',
    ingredients:[{name:'Pain ARRUPAN',quantity:'135g (3 tranches)',calories:360,protein:12,carbs:66,fat:4.5},{name:'Escalope de poulet',quantity:'200g',calories:240,protein:44,carbs:0,fat:4},{name:'Avocat',quantity:'60g',calories:96,protein:1.2,carbs:5.4,fat:9},{name:'Fromage frais Lactel 0%',quantity:'60g',calories:53,protein:5.2,carbs:2.6,fat:2.1},{name:'Œuf entier',quantity:'1 (60g)',calories:70,protein:6,carbs:1,fat:5}],
    steps:['Cuire poulet bien assaisonné.','Cuire œuf au plat.','Étaler fromage frais sur chaque tortilla.','Wrap 1: poulet + tomates. Wrap 2: avocat + œuf. Wrap 3: poulet + concombre.','Rouler serré, couper en deux chacun.'],
    substitutions:[{original:'3 wraps',alternative:'1 grosse galette pliée pour version plus simple'},{original:'Œuf au plat',alternative:'2 œufs durs en rondelles'}],coach_note:'Le festin de wraps — variety + bulk. Idéal entraînement long + repas post + collation tout-en-un.'},

  {title:'Couscous Royal Poulet Steak',category:'Lean Bulk',meal_type:'dinner',goal_tag:'muscle',craving_tag:'chaud',prep_time:25,difficulty:2,total_calories:785,total_protein:62,total_carbs:80,total_fat:18,featured:true,photo_gradient:'linear-gradient(135deg,#1a1000,#C8A415)',membership_required:'cookbook',
    ingredients:[{name:'Escalope de poulet',quantity:'150g',calories:180,protein:33,carbs:0,fat:3},{name:'Steak haché',quantity:'100g',calories:250,protein:26,carbs:0,fat:17},{name:'Couscous cru',quantity:'100g',calories:356,protein:12,carbs:74,fat:1},{name:'Pois chiches cuits',quantity:'80g',calories:131,protein:7.1,carbs:21.9,fat:2.1},{name:'Huile d\'olive',quantity:'8g',calories:72,protein:0,carbs:0,fat:8}],
    steps:['Cuire poulet et steak séparément avec épices ras el hanout.','Préparer bouillon : tomates + carottes + courgettes + navets + épices.','Préparer semoule : eau bouillante 1:1, huile.','Incorporer pois chiches dans bouillon les 5 dernières min.','Servir : semoule, légumes, poulet, steak côte à côte.'],
    substitutions:[{original:'Steak haché',alternative:'200g poulet supplémentaire'},{original:'Pois chiches',alternative:'Fèves cuites'}],coach_note:'Le couscous royal du dimanche — protéine surchargée. La double viande change tout pour la prise.'},

  {title:'Pizza Pain ARRUPAN XL Tout Garnie',category:'Lean Bulk',meal_type:'dinner',goal_tag:'muscle',craving_tag:'fast food',prep_time:15,difficulty:1,total_calories:745,total_protein:58,total_carbs:62,total_fat:24,featured:false,photo_gradient:'linear-gradient(135deg,#1a0000,#DC143C)',membership_required:'cookbook',
    ingredients:[{name:'Pain ARRUPAN',quantity:'135g (3 tranches)',calories:360,protein:12,carbs:66,fat:4.5},{name:'Steak haché',quantity:'120g',calories:300,protein:31.2,carbs:0,fat:20.4},{name:'Fromage frais Lactel 0%',quantity:'120g',calories:107,protein:10.3,carbs:5.2,fat:4.2},{name:'Œuf entier',quantity:'1 (60g)',calories:70,protein:6,carbs:1,fat:5},{name:'Tomates',quantity:'80g',calories:14,protein:0.7,carbs:3.1,fat:0.2}],
    steps:['Coller 3 tranches de pain ARRUPAN ensemble (eau pour faire pâte).','Étaler fromage frais épais.','Faire revenir steak haché émietté.','Garnir : steak + tomates + œuf cassé au centre.','Four 200°C 12 min.'],
    substitutions:[{original:'Steak haché',alternative:'200g poulet en dés'},{original:'Œuf',alternative:'Champignons + olives pour version végé'}],coach_note:'La pizza XL bulk — 745 kcal dans une présentation pizza. Coup d\'œil bluffant pour quelqu\'un en surplus.'},

  {title:'Bowl Saumon Riz Avocat Soja',category:'Lean Bulk',meal_type:'dinner',goal_tag:'muscle',craving_tag:'chaud',prep_time:15,difficulty:1,total_calories:755,total_protein:48,total_carbs:78,total_fat:24,featured:false,photo_gradient:'linear-gradient(135deg,#1a0000,#FA8072)',membership_required:'cookbook',
    ingredients:[{name:'Saumon',quantity:'180g',calories:374,protein:36,carbs:0,fat:23.4},{name:'Riz blanc',quantity:'90g cru',calories:324,protein:6.3,carbs:70.2,fat:0.9},{name:'Avocat',quantity:'40g',calories:64,protein:0.8,carbs:3.6,fat:6},{name:'Tomates',quantity:'60g',calories:11,protein:0.5,carbs:2.3,fat:0.2}],
    steps:['Cuire riz généreusement.','Cuire saumon à la poêle skin down 5 min.','Bowl : riz au fond, saumon dessus, avocat en lamelles.','Sauce : soja + miel + ail + lime + sésame.','Sésame et ciboule au final.'],
    substitutions:[{original:'Saumon',alternative:'200g poulet pour version moins grasse'},{original:'Riz blanc',alternative:'Riz complet pour bulk plus fibreux'}],coach_note:'Le bowl saumon parfait pour le bulk. Saumon = oméga-3, riz = glucides, avocat = bons gras. Trinité.'},

  {title:'Lasagnes Bulk Bœuf Triple Fromage',category:'Lean Bulk',meal_type:'dinner',goal_tag:'muscle',craving_tag:'chaud',prep_time:30,difficulty:3,total_calories:825,total_protein:58,total_carbs:78,total_fat:26,featured:true,photo_gradient:'linear-gradient(135deg,#1a0000,#8B0000)',membership_required:'cookbook',
    ingredients:[{name:'Steak haché',quantity:'200g',calories:500,protein:52,carbs:0,fat:34},{name:'Pain ARRUPAN',quantity:'135g (3 tranches)',calories:360,protein:12,carbs:66,fat:4.5},{name:'Fromage frais Lactel 0%',quantity:'200g',calories:178,protein:17.2,carbs:8.6,fat:7},{name:'Tomates',quantity:'150g',calories:27,protein:1.4,carbs:5.9,fat:0.3}],
    steps:['Cuire steak haché + tomates concassées + herbes italiennes 10 min.','Trancher pain ARRUPAN fin.','Béchamel light : fromage frais + lait + muscade.','Couches : sauce, pain, béchamel, sauce, pain, béchamel.','Four 200°C 20 min.'],
    substitutions:[{original:'Bœuf',alternative:'Mélange bœuf + dinde'},{original:'Pain ARRUPAN',alternative:'Vraies feuilles de lasagne'}],coach_note:'Les lasagnes bulk — gros sport. Préparer en 4 portions, congeler les autres pour les jours de prise compliqués.'},

  {title:'Sandwich Steak Frites Maison',category:'Lean Bulk',meal_type:'dinner',goal_tag:'muscle',craving_tag:'fast food',prep_time:20,difficulty:1,total_calories:745,total_protein:48,total_carbs:78,total_fat:22,featured:false,photo_gradient:'linear-gradient(135deg,#1a0000,#FF4500)',membership_required:'cookbook',
    ingredients:[{name:'Steak haché',quantity:'150g',calories:375,protein:39,carbs:0,fat:25.5},{name:'Pain ARRUPAN',quantity:'90g',calories:240,protein:8,carbs:44,fat:3},{name:'Pommes de terre',quantity:'200g',calories:160,protein:4,carbs:36,fat:0},{name:'Fromage frais Lactel 0%',quantity:'30g',calories:27,protein:2.6,carbs:1.3,fat:1.1},{name:'Huile d\'olive',quantity:'5g',calories:45,protein:0,carbs:0,fat:5}],
    steps:['Couper PDT en frites, huile + sel, four 200°C 20 min en remuant.','Cuire steak à la poêle bien chaude.','Toaster pain, étaler fromage frais.','Sandwich : pain, steak, oignons confits, tomates, pain.','Servir avec frites maison.'],
    substitutions:[{original:'Frites',alternative:'Patate douce pour version sucrée'},{original:'Steak haché',alternative:'2 steaks de poulet 200g'}],coach_note:'Steak frites — version saine. Frites au four = 70% moins de gras que friture. Même goût.'},

  {title:'Pâtes Carbonara Light',category:'Lean Bulk',meal_type:'dinner',goal_tag:'muscle',craving_tag:'chaud',prep_time:15,difficulty:2,total_calories:725,total_protein:52,total_carbs:78,total_fat:18,featured:false,photo_gradient:'linear-gradient(135deg,#1a1000,#FFD700)',membership_required:'cookbook',
    ingredients:[{name:'Pâtes',quantity:'120g cru',calories:420,protein:14.4,carbs:86.4,fat:2.4},{name:'Escalope de dinde fumée',quantity:'100g',calories:110,protein:22,carbs:0,fat:1},{name:'Œufs entiers',quantity:'2 (120g)',calories:140,protein:12,carbs:2,fat:10},{name:'Fromage frais Lactel 0%',quantity:'60g',calories:53,protein:5.2,carbs:2.6,fat:2.1}],
    steps:['Cuire pâtes al dente, RÉSERVER eau cuisson.','Faire revenir dinde fumée jusqu\'à croustillante.','HORS du feu : mélanger œufs battus + fromage frais + parmesan râpé + poivre noir.','Verser sur pâtes chaudes, mélanger vivement (eau de cuisson si trop sec).','Servir immédiatement.'],
    substitutions:[{original:'Dinde fumée',alternative:'Vrai pancetta 80g +200kcal'},{original:'2 œufs',alternative:'3 jaunes pour version plus crémeuse'}],coach_note:'La carbonara italienne — JAMAIS de crème. Le secret c\'est l\'œuf cru qui cuit à la chaleur des pâtes.'},

  {title:'Bowl Avoine Salée Bulk',category:'Lean Bulk',meal_type:'breakfast',goal_tag:'muscle',craving_tag:'salé',prep_time:12,difficulty:2,total_calories:735,total_protein:48,total_carbs:62,total_fat:28,featured:false,photo_gradient:'linear-gradient(135deg,#1a1000,#6B8E23)',membership_required:'cookbook',
    ingredients:[{name:'Flocons d\'avoine',quantity:'80g',calories:304,protein:10.4,carbs:48,fat:5.6},{name:'Œufs entiers',quantity:'3 (180g)',calories:210,protein:18,carbs:3,fat:15},{name:'Avocat',quantity:'60g',calories:96,protein:1.2,carbs:5.4,fat:9},{name:'Escalope de dinde',quantity:'80g',calories:88,protein:17.6,carbs:0,fat:0.8},{name:'Huile d\'olive',quantity:'4g',calories:36,protein:0,carbs:0,fat:4}],
    steps:['Cuire avoine salée à l\'eau avec cube de bouillon.','Cuire dinde émincée en parallèle.','Cuire œufs au plat.','Bowl : avoine au fond, dinde dessus, œufs, avocat.','Sauce piquante + sel + poivre.'],
    substitutions:[{original:'3 œufs',alternative:'4 œufs pour bulk plus extrême'},{original:'Dinde',alternative:'Poulet ou bacon dinde'}],coach_note:'Le power breakfast bulk. 735 kcal qui restent salés et savoureux toute la matinée.'},

  {title:'Burrito Bowl Bulk',category:'Lean Bulk',meal_type:'lunch',goal_tag:'muscle',craving_tag:'chaud',prep_time:18,difficulty:2,total_calories:785,total_protein:58,total_carbs:88,total_fat:18,featured:false,photo_gradient:'linear-gradient(135deg,#1a0a00,#FF8C00)',membership_required:'cookbook',
    ingredients:[{name:'Escalope de poulet',quantity:'200g',calories:240,protein:44,carbs:0,fat:4},{name:'Riz blanc',quantity:'100g cru',calories:360,protein:7,carbs:78,fat:1},{name:'Haricots noirs cuits',quantity:'100g',calories:132,protein:8.9,carbs:23.7,fat:0.5},{name:'Avocat',quantity:'40g',calories:64,protein:0.8,carbs:3.6,fat:6},{name:'Fromage frais Lactel 0%',quantity:'30g',calories:27,protein:2.6,carbs:1.3,fat:1.1}],
    steps:['Cuire riz généreusement.','Mariner poulet : cumin + paprika + lime + ail.','Cuire à feu vif jusqu\'à caramélisé.','Réchauffer haricots noirs avec épices.','Bowl : riz, poulet, haricots, avocat, salsa, sauce fromage frais.'],
    substitutions:[{original:'Haricots noirs',alternative:'Pois chiches cuits 100g'},{original:'Poulet',alternative:'Steak haché 180g pour version texane'}],coach_note:'Le Chipotle bowl XL — bulk version. Glucides complexes des haricots + riz = énergie longue durée.'},

  {title:'Riz au Poulet Curry Bulk',category:'Lean Bulk',meal_type:'dinner',goal_tag:'muscle',craving_tag:'chaud',prep_time:20,difficulty:2,total_calories:755,total_protein:54,total_carbs:88,total_fat:18,featured:false,photo_gradient:'linear-gradient(135deg,#1a1000,#FFD700)',membership_required:'cookbook',
    ingredients:[{name:'Escalope de poulet',quantity:'220g',calories:264,protein:48.4,carbs:0,fat:4.4},{name:'Riz blanc',quantity:'100g cru',calories:360,protein:7,carbs:78,fat:1},{name:'Fromage frais Lactel 0%',quantity:'100g',calories:89,protein:8.6,carbs:4.3,fat:3.5},{name:'Tomates',quantity:'80g',calories:14,protein:0.7,carbs:3.1,fat:0.2},{name:'Huile d\'olive',quantity:'10g',calories:90,protein:0,carbs:0,fat:10}],
    steps:['Faire revenir poulet en dés avec oignon, ail, gingembre.','Ajouter curry en poudre, garam masala, paprika.','Tomates concassées + 200ml eau, mijoter 10 min.','Hors du feu, incorporer fromage frais pour onctuosité.','Servir sur lit de riz blanc.'],
    substitutions:[{original:'Fromage frais',alternative:'150ml lait de coco pour version authentique +150kcal'},{original:'Poulet',alternative:'Crevettes 200g'}],coach_note:'Le butter chicken indien — version fit. La sauce crémeuse au fromage frais imite parfaitement la crème.'},

  {title:'Steak Frites Salade Bulk',category:'Lean Bulk',meal_type:'dinner',goal_tag:'muscle',craving_tag:'chaud',prep_time:25,difficulty:2,total_calories:795,total_protein:56,total_carbs:62,total_fat:32,featured:false,photo_gradient:'linear-gradient(135deg,#1a0000,#8B0000)',membership_required:'cookbook',
    ingredients:[{name:'Steak haché',quantity:'200g',calories:500,protein:52,carbs:0,fat:34},{name:'Pommes de terre',quantity:'250g',calories:200,protein:5,carbs:45,fat:0},{name:'Tomates',quantity:'100g',calories:18,protein:0.9,carbs:3.9,fat:0.2},{name:'Fromage frais Lactel 0%',quantity:'30g',calories:27,protein:2.6,carbs:1.3,fat:1.1},{name:'Huile d\'olive',quantity:'6g',calories:54,protein:0,carbs:0,fat:6}],
    steps:['Couper PDT en frites épaisses, huile + sel.','Four 200°C 25 min en remuant à mi-cuisson.','Steak épais — poêle ultra chaude 3 min par côté.','Laisser reposer steak 3 min.','Sauce poivre : fromage frais + poivre vert + cognac optionnel.'],
    substitutions:[{original:'Sauce poivre',alternative:'Sauce roquefort: fromage frais + 10g bleu'},{original:'Frites',alternative:'Patate douce pour version sucrée'}],coach_note:'Le steak frites de bistrot. La sauce maison fait toute la différence.'},

  // ════════════════════════════════════════════
  // ⚡ 15-MIN MEALS (5)
  // ════════════════════════════════════════════
  {title:'Poêlée Express Poulet Légumes',category:'15 Min Meals',meal_type:'dinner',goal_tag:'all',craving_tag:'chaud',prep_time:15,difficulty:1,total_calories:425,total_protein:42,total_carbs:38,total_fat:10,featured:true,photo_gradient:'linear-gradient(135deg,#1a0800,#FF8C00)',membership_required:'cookbook',
    ingredients:[{name:'Escalope de poulet',quantity:'180g',calories:216,protein:39.6,carbs:0,fat:3.6},{name:'Riz blanc',quantity:'50g cru',calories:180,protein:3.5,carbs:39,fat:0.5},{name:'Tomates',quantity:'100g',calories:18,protein:0.9,carbs:3.9,fat:0.2},{name:'Poivrons',quantity:'80g',calories:18,protein:0.6,carbs:4.2,fat:0.2},{name:'Huile d\'olive',quantity:'4g',calories:36,protein:0,carbs:0,fat:4}],
    steps:['Lancer le riz à cuire (12 min).','Couper poulet en dés, mariner épices ras el hanout.','Trancher poivrons et tomates.','Poêle ultra chaude : poulet + légumes 8 min total.','Servir sur riz, persil frais.'],
    substitutions:[{original:'Poulet',alternative:'Dinde ou steak haché émincé'},{original:'Riz',alternative:'Pâtes courtes 50g cru'}],coach_note:'15 minutes du frigo à l\'assiette. Le repas du soir pressé qui ne sacrifie ni macros ni goût.'},

  {title:'Omelette Bowl Express',category:'15 Min Meals',meal_type:'dinner',goal_tag:'all',craving_tag:'salé',prep_time:10,difficulty:1,total_calories:395,total_protein:32,total_carbs:14,total_fat:24,featured:false,photo_gradient:'linear-gradient(135deg,#1a1000,#FFD700)',membership_required:'cookbook',
    ingredients:[{name:'Œufs entiers',quantity:'4 (240g)',calories:280,protein:24,carbs:4,fat:20},{name:'Escalope de dinde',quantity:'60g',calories:66,protein:13.2,carbs:0,fat:0.6},{name:'Fromage frais Lactel 0%',quantity:'40g',calories:36,protein:3.4,carbs:1.7,fat:1.4},{name:'Tomates',quantity:'50g',calories:9,protein:0.5,carbs:2,fat:0.1}],
    steps:['Faire revenir dinde émincée à la poêle.','Battre œufs avec fromage frais, sel, poivre.','Verser sur dinde, ajouter tomates dés.','Cuire à feu doux couvert 5 min.','Servir comme omelette ouverte.'],
    substitutions:[{original:'Dinde',alternative:'Thon 60g pour version express sans cuisson'},{original:'Tomates',alternative:'Épinards + champignons'}],coach_note:'10 minutes chrono. Protéine + bons gras + légumes. Repas du soir parfait quand t\'as faim et flemme.'},

  {title:'Wrap Express Thon Avocat',category:'15 Min Meals',meal_type:'lunch',goal_tag:'all',craving_tag:'fast food',prep_time:8,difficulty:1,total_calories:425,total_protein:36,total_carbs:42,total_fat:14,featured:false,photo_gradient:'linear-gradient(135deg,#0a1a00,#90EE90)',membership_required:'cookbook',
    ingredients:[{name:'Pain ARRUPAN',quantity:'90g',calories:240,protein:8,carbs:44,fat:3},{name:'Thon naturel',quantity:'120g',calories:139,protein:31.2,carbs:0,fat:1.2},{name:'Avocat',quantity:'40g',calories:64,protein:0.8,carbs:3.6,fat:6},{name:'Tomates',quantity:'40g',calories:7,protein:0.4,carbs:1.6,fat:0.1},{name:'Fromage frais Lactel 0%',quantity:'20g',calories:18,protein:1.7,carbs:0.9,fat:0.7}],
    steps:['Égoutter le thon.','Écraser l\'avocat avec citron, sel.','Étaler avocat sur pain.','Garnir thon + tomates + fromage frais.','Rouler serré, couper en deux.'],
    substitutions:[{original:'Thon',alternative:'Poulet froid effiloché'},{original:'Avocat',alternative:'Fromage frais 60g pour version moins grasse'}],coach_note:'8 minutes — possibilité de le faire entre 2 réunions. Lunch box parfait.'},

  {title:'Pâtes Tomates Cerises Poulet',category:'15 Min Meals',meal_type:'dinner',goal_tag:'all',craving_tag:'chaud',prep_time:15,difficulty:1,total_calories:495,total_protein:42,total_carbs:62,total_fat:8,featured:false,photo_gradient:'linear-gradient(135deg,#1a0000,#B22222)',membership_required:'cookbook',
    ingredients:[{name:'Pâtes',quantity:'70g cru',calories:245,protein:8.4,carbs:50.4,fat:1.4},{name:'Escalope de poulet',quantity:'150g',calories:180,protein:33,carbs:0,fat:3},{name:'Tomates',quantity:'150g',calories:27,protein:1.4,carbs:5.9,fat:0.3},{name:'Fromage frais Lactel 0%',quantity:'40g',calories:36,protein:3.4,carbs:1.7,fat:1.4},{name:'Huile d\'olive',quantity:'1g',calories:9,protein:0,carbs:0,fat:1}],
    steps:['Lancer les pâtes (8-10 min).','Couper poulet en dés, faire revenir à feu vif.','Ajouter tomates cerises coupées en deux.','Mélanger avec pâtes égouttées + fromage frais.','Basilic + poivre + parmesan râpé 5g.'],
    substitutions:[{original:'Tomates fraîches',alternative:'Tomates en boîte de qualité'},{original:'Poulet',alternative:'Crevettes 150g'}],coach_note:'Les pâtes italiennes en 15 min. Tomates cerises sautées = goût concentré incroyable.'},

  {title:'Bowl Riz Poulet Sauce Soja',category:'15 Min Meals',meal_type:'lunch',goal_tag:'all',craving_tag:'chaud',prep_time:15,difficulty:1,total_calories:455,total_protein:42,total_carbs:52,total_fat:8,featured:true,photo_gradient:'linear-gradient(135deg,#1a0a00,#D2691E)',membership_required:'cookbook',
    ingredients:[{name:'Escalope de poulet',quantity:'180g',calories:216,protein:39.6,carbs:0,fat:3.6},{name:'Riz blanc',quantity:'60g cru',calories:216,protein:4.2,carbs:46.8,fat:0.6},{name:'Tomates',quantity:'50g',calories:9,protein:0.5,carbs:2,fat:0.1},{name:'Huile d\'olive',quantity:'2g',calories:18,protein:0,carbs:0,fat:2}],
    steps:['Lancer riz à cuire.','Couper poulet en dés, mariner soja + gingembre + ail 5 min.','Cuire à feu vif jusqu\'à caramélisé.','Servir sur riz : poulet + tomates + ciboule.','Sauce soja en filet + sésame.'],
    substitutions:[{original:'Poulet',alternative:'Crevettes 180g pour version express'},{original:'Riz blanc',alternative:'Nouilles asiatiques 60g'}],coach_note:'Le bol asiatique du quotidien. 15 minutes. Macros parfaites. Goût universellement aimé.'}
];

async function main(){
  console.log(`\n🍳  BATCH 3 — Adding ${RECIPES.length} new recipes\n`);
  let inserted = 0;
  for(let i=0;i<RECIPES.length;i+=10){
    const batch = RECIPES.slice(i,i+10);
    const ins = await q('POST','cookbook_recipes',batch);
    if(!ins.ok){
      console.error(`❌ Batch ${i/10+1}: ${ins.status}`,JSON.stringify(ins.data?.message||ins.data));
    } else {
      const rows = Array.isArray(ins.data)?ins.data:[];
      rows.forEach(r=>console.log(`  ✅ ${r.title}`));
      inserted += rows.length;
    }
  }
  console.log(`\n🎉  Batch 3 done — ${inserted}/${RECIPES.length} recipes added.\n`);
}
main().catch(e=>{console.error(e);process.exit(1);});
