// seed_exercise_library.mjs
// 80 common exercises in French with default sets/reps/rest/muscle groups
// Run: node seed_exercise_library.mjs

import { createClient } from '@supabase/supabase-js'

const SUPABASE_URL = 'https://korektlpnwuefsagfuvq.supabase.co'
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || 'PASTE_SERVICE_ROLE_HERE'

const sb = createClient(SUPABASE_URL, SUPABASE_KEY)

// Muscle group slugs match the SVG body highlighter (chest, deltoids, biceps, triceps,
// forearm, abs, obliques, trapezius, upper-back, lower-back, quadriceps, hamstring,
// gluteal, calves, adductors, tibialis)

const exercises = [
  // ════════════════════════════ CHEST (push) ════════════════════════════
  { slug:'developpe-couche-barre', name_fr:'Développé couché barre', name_en:'Barbell bench press', category:'push', muscle_groups:['chest','triceps','deltoids'], equipment:['barre','banc'], default_sets:4, default_reps:'6-10', default_rest_seconds:120, default_tempo:'3-0-1', difficulty:2, form_cue:'Omoplates serrées, pieds ancrés, descends la barre au niveau du sternum.', is_compound:true },
  { slug:'developpe-couche-halteres', name_fr:'Développé couché haltères', name_en:'Dumbbell bench press', category:'push', muscle_groups:['chest','triceps','deltoids'], equipment:['halteres','banc'], default_sets:4, default_reps:'8-12', default_rest_seconds:90, difficulty:2, form_cue:'Plus d\'amplitude qu\'à la barre — descends jusqu\'à sentir l\'étirement.', is_compound:true },
  { slug:'developpe-incline-halteres', name_fr:'Développé incliné haltères', name_en:'Incline dumbbell press', category:'push', muscle_groups:['chest','deltoids','triceps'], equipment:['halteres','banc'], default_sets:4, default_reps:'8-12', default_rest_seconds:90, difficulty:2, form_cue:'Banc à 30°, pas plus — au-delà ça travaille trop les épaules.', is_compound:true },
  { slug:'developpe-decline-barre', name_fr:'Développé décliné barre', name_en:'Decline bench press', category:'push', muscle_groups:['chest','triceps'], equipment:['barre','banc'], default_sets:4, default_reps:'8-10', default_rest_seconds:90, difficulty:2, form_cue:'Cible le bas des pectoraux. Descends bien au sternum.', is_compound:true },
  { slug:'ecarte-halteres', name_fr:'Écarté haltères', name_en:'Dumbbell fly', category:'push', muscle_groups:['chest'], equipment:['halteres','banc'], default_sets:3, default_reps:'10-12', default_rest_seconds:75, default_tempo:'3-1-1', difficulty:2, form_cue:'Coudes légèrement fléchis, fixés. Ouverture contrôlée.', is_compound:false },
  { slug:'pompes', name_fr:'Pompes', name_en:'Push-ups', category:'push', muscle_groups:['chest','triceps','deltoids','abs'], equipment:[], default_sets:3, default_reps:'10-20', default_rest_seconds:60, difficulty:1, form_cue:'Corps gainé, mains sous épaules, descends jusqu\'à toucher.', is_compound:true },
  { slug:'pompes-diamant', name_fr:'Pompes diamant', name_en:'Diamond push-ups', category:'push', muscle_groups:['triceps','chest'], equipment:[], default_sets:3, default_reps:'8-15', default_rest_seconds:60, difficulty:2, form_cue:'Mains formant un losange sous le sternum. Coudes près du corps.', is_compound:true },
  { slug:'dips', name_fr:'Dips', name_en:'Dips', category:'push', muscle_groups:['chest','triceps','deltoids'], equipment:['barres-paralleles'], default_sets:3, default_reps:'8-12', default_rest_seconds:90, difficulty:2, form_cue:'Penché en avant pour cibler pecs, droit pour cibler triceps.', is_compound:true },

  // ════════════════════════════ BACK (pull) ════════════════════════════
  { slug:'tractions-pronation', name_fr:'Tractions pronation', name_en:'Pull-ups', category:'pull', muscle_groups:['upper-back','biceps','forearm'], equipment:['barre-tractions'], default_sets:4, default_reps:'6-10', default_rest_seconds:120, difficulty:3, form_cue:'Démarre suspendu bras tendus. Mente menton au-dessus de la barre.', is_compound:true },
  { slug:'tractions-supination', name_fr:'Tractions supination', name_en:'Chin-ups', category:'pull', muscle_groups:['biceps','upper-back'], equipment:['barre-tractions'], default_sets:4, default_reps:'6-10', default_rest_seconds:120, difficulty:2, form_cue:'Paumes vers toi. Plus facile que la pronation, plus de biceps.', is_compound:true },
  { slug:'rowing-barre', name_fr:'Rowing barre', name_en:'Barbell row', category:'pull', muscle_groups:['upper-back','biceps','trapezius'], equipment:['barre'], default_sets:4, default_reps:'8-10', default_rest_seconds:120, difficulty:2, form_cue:'Dos plat, légèrement penché. Tire vers le bas du sternum.', is_compound:true },
  { slug:'rowing-haltere', name_fr:'Rowing haltère (1 bras)', name_en:'One-arm dumbbell row', category:'pull', muscle_groups:['upper-back','biceps'], equipment:['halteres','banc'], default_sets:4, default_reps:'10-12', default_rest_seconds:75, difficulty:2, form_cue:'Genou et main posés sur le banc. Tire le coude vers la hanche.', is_compound:true },
  { slug:'tirage-vertical', name_fr:'Tirage vertical (poulie)', name_en:'Lat pulldown', category:'pull', muscle_groups:['upper-back','biceps'], equipment:['poulie'], default_sets:4, default_reps:'10-12', default_rest_seconds:75, difficulty:1, form_cue:'Tire la barre devant toi, jusqu\'à la clavicule. Coudes vers le bas.', is_compound:true },
  { slug:'tirage-horizontal', name_fr:'Tirage horizontal (poulie)', name_en:'Seated cable row', category:'pull', muscle_groups:['upper-back','biceps','trapezius'], equipment:['poulie'], default_sets:4, default_reps:'10-12', default_rest_seconds:75, difficulty:1, form_cue:'Dos droit, tire vers le nombril. Serre les omoplates.', is_compound:true },
  { slug:'soulev-de-terre', name_fr:'Soulevé de terre', name_en:'Deadlift', category:'pull', muscle_groups:['lower-back','hamstring','gluteal','upper-back','trapezius'], equipment:['barre'], default_sets:4, default_reps:'5-8', default_rest_seconds:180, difficulty:3, form_cue:'Dos plat, pousse le sol avec les pieds. La barre reste collée aux jambes.', is_compound:true },
  { slug:'soulev-de-terre-roumain', name_fr:'Soulevé de terre roumain', name_en:'Romanian deadlift', category:'pull', muscle_groups:['hamstring','gluteal','lower-back'], equipment:['barre'], default_sets:4, default_reps:'8-10', default_rest_seconds:120, difficulty:2, form_cue:'Genoux légèrement fléchis, pousse les hanches en arrière. Sens l\'étirement des ischios.', is_compound:true },
  { slug:'face-pull', name_fr:'Face pull', name_en:'Face pull', category:'pull', muscle_groups:['deltoids','upper-back','trapezius'], equipment:['poulie'], default_sets:3, default_reps:'12-15', default_rest_seconds:60, difficulty:1, form_cue:'Tire vers le front. Coudes hauts. Idéal pour la santé d\'épaules.', is_compound:false },
  { slug:'shrugs', name_fr:'Shrugs haltères', name_en:'Dumbbell shrugs', category:'pull', muscle_groups:['trapezius'], equipment:['halteres'], default_sets:3, default_reps:'12-15', default_rest_seconds:60, difficulty:1, form_cue:'Hausse les épaules verticalement. Pas de rotation.', is_compound:false },

  // ════════════════════════════ SHOULDERS ════════════════════════════
  { slug:'developpe-militaire', name_fr:'Développé militaire', name_en:'Overhead press', category:'push', muscle_groups:['deltoids','triceps','trapezius'], equipment:['barre'], default_sets:4, default_reps:'6-10', default_rest_seconds:120, difficulty:2, form_cue:'Debout ou assis. Pousse la barre droit au-dessus de la tête. Gaine.', is_compound:true },
  { slug:'developpe-arnold', name_fr:'Développé Arnold', name_en:'Arnold press', category:'push', muscle_groups:['deltoids','triceps'], equipment:['halteres'], default_sets:3, default_reps:'10-12', default_rest_seconds:75, difficulty:2, form_cue:'Démarre paumes vers toi, fais une rotation en poussant.', is_compound:true },
  { slug:'elevations-laterales', name_fr:'Élévations latérales', name_en:'Lateral raises', category:'push', muscle_groups:['deltoids'], equipment:['halteres'], default_sets:4, default_reps:'12-15', default_rest_seconds:60, difficulty:1, form_cue:'Coudes légèrement fléchis. Monte jusqu\'à hauteur d\'épaule, pas plus.', is_compound:false },
  { slug:'elevations-frontales', name_fr:'Élévations frontales', name_en:'Front raises', category:'push', muscle_groups:['deltoids'], equipment:['halteres'], default_sets:3, default_reps:'10-12', default_rest_seconds:60, difficulty:1, form_cue:'Alterne les bras. Monte jusqu\'à l\'horizontale.', is_compound:false },
  { slug:'oiseau-halteres', name_fr:'Oiseau (rear delts)', name_en:'Reverse fly', category:'pull', muscle_groups:['deltoids','upper-back'], equipment:['halteres','banc'], default_sets:3, default_reps:'12-15', default_rest_seconds:60, difficulty:1, form_cue:'Buste penché à l\'horizontale. Ouvre les bras à l\'horizontale.', is_compound:false },

  // ════════════════════════════ ARMS ════════════════════════════
  { slug:'curl-biceps-barre', name_fr:'Curl biceps barre', name_en:'Barbell curl', category:'pull', muscle_groups:['biceps','forearm'], equipment:['barre'], default_sets:4, default_reps:'8-12', default_rest_seconds:75, difficulty:1, form_cue:'Coudes collés au corps. Monte la barre sans balancer.', is_compound:false },
  { slug:'curl-biceps-halteres', name_fr:'Curl biceps haltères', name_en:'Dumbbell curl', category:'pull', muscle_groups:['biceps','forearm'], equipment:['halteres'], default_sets:4, default_reps:'10-12', default_rest_seconds:60, difficulty:1, form_cue:'Supination en montant. Alterne ou simultané.', is_compound:false },
  { slug:'curl-marteau', name_fr:'Curl marteau', name_en:'Hammer curl', category:'pull', muscle_groups:['biceps','forearm'], equipment:['halteres'], default_sets:3, default_reps:'10-12', default_rest_seconds:60, difficulty:1, form_cue:'Prise neutre tout du long. Cible le brachial et l\'avant-bras.', is_compound:false },
  { slug:'curl-pupitre', name_fr:'Curl pupitre', name_en:'Preacher curl', category:'pull', muscle_groups:['biceps'], equipment:['barre','banc-pupitre'], default_sets:3, default_reps:'10-12', default_rest_seconds:60, difficulty:1, form_cue:'Bras bloqués sur le pupitre. Pic de contraction en haut.', is_compound:false },
  { slug:'extension-triceps-corde', name_fr:'Extension triceps corde', name_en:'Triceps pushdown', category:'push', muscle_groups:['triceps'], equipment:['poulie'], default_sets:4, default_reps:'10-15', default_rest_seconds:60, difficulty:1, form_cue:'Coudes collés au corps. Écarte les poignets en bas.', is_compound:false },
  { slug:'extension-triceps-nuque', name_fr:'Extension triceps nuque (haltère)', name_en:'Overhead triceps extension', category:'push', muscle_groups:['triceps'], equipment:['halteres'], default_sets:3, default_reps:'10-12', default_rest_seconds:60, difficulty:1, form_cue:'Coude vers le ciel, descends derrière la nuque. Étire bien.', is_compound:false },
  { slug:'kickback-triceps', name_fr:'Kickback triceps', name_en:'Triceps kickback', category:'push', muscle_groups:['triceps'], equipment:['halteres'], default_sets:3, default_reps:'12-15', default_rest_seconds:60, difficulty:1, form_cue:'Bras parallèle au sol. Extension complète vers l\'arrière.', is_compound:false },
  { slug:'curl-poignets', name_fr:'Curl poignets', name_en:'Wrist curl', category:'pull', muscle_groups:['forearm'], equipment:['halteres'], default_sets:3, default_reps:'15-20', default_rest_seconds:45, difficulty:1, form_cue:'Avant-bras posés. Travail isolé du poignet.', is_compound:false },

  // ════════════════════════════ LEGS — quads/glutes/hams ════════════════════════════
  { slug:'squat-barre', name_fr:'Squat barre', name_en:'Barbell squat', category:'legs', muscle_groups:['quadriceps','gluteal','hamstring','lower-back'], equipment:['barre','rack'], default_sets:4, default_reps:'6-10', default_rest_seconds:180, difficulty:3, form_cue:'Pieds largeur épaules. Descends jusqu\'à parallèle minimum. Dos droit.', is_compound:true },
  { slug:'squat-frontal', name_fr:'Squat frontal', name_en:'Front squat', category:'legs', muscle_groups:['quadriceps','gluteal','abs'], equipment:['barre','rack'], default_sets:4, default_reps:'6-10', default_rest_seconds:150, difficulty:3, form_cue:'Barre sur les épaules avant. Buste très droit. Excellent pour les quads.', is_compound:true },
  { slug:'squat-bulgare', name_fr:'Squat bulgare', name_en:'Bulgarian split squat', category:'legs', muscle_groups:['quadriceps','gluteal','hamstring'], equipment:['halteres','banc'], default_sets:3, default_reps:'10-12', default_rest_seconds:90, difficulty:2, form_cue:'Pied arrière sur banc. Descends bien à 90°. Une jambe à la fois.', is_compound:true },
  { slug:'fentes-marche', name_fr:'Fentes marchées', name_en:'Walking lunges', category:'legs', muscle_groups:['quadriceps','gluteal','hamstring'], equipment:['halteres'], default_sets:3, default_reps:'10-12', default_rest_seconds:90, difficulty:2, form_cue:'Grand pas en avant, genou arrière touche presque le sol.', is_compound:true },
  { slug:'fentes-inversees', name_fr:'Fentes inversées', name_en:'Reverse lunges', category:'legs', muscle_groups:['quadriceps','gluteal','hamstring'], equipment:['halteres'], default_sets:3, default_reps:'10-12', default_rest_seconds:75, difficulty:2, form_cue:'Recule avec une jambe. Plus facile pour les genoux que les fentes avant.', is_compound:true },
  { slug:'presse-jambes', name_fr:'Presse à jambes', name_en:'Leg press', category:'legs', muscle_groups:['quadriceps','gluteal','hamstring'], equipment:['machine'], default_sets:4, default_reps:'10-12', default_rest_seconds:120, difficulty:1, form_cue:'Pieds largeur épaules au milieu du plateau. Ne verrouille pas les genoux.', is_compound:true },
  { slug:'leg-extension', name_fr:'Leg extension', name_en:'Leg extension', category:'legs', muscle_groups:['quadriceps'], equipment:['machine'], default_sets:3, default_reps:'12-15', default_rest_seconds:60, difficulty:1, form_cue:'Pic de contraction en haut. Contrôle la descente.', is_compound:false },
  { slug:'leg-curl', name_fr:'Leg curl', name_en:'Leg curl', category:'legs', muscle_groups:['hamstring'], equipment:['machine'], default_sets:4, default_reps:'10-12', default_rest_seconds:75, difficulty:1, form_cue:'Plie les genoux à fond. Évite de relever le bassin.', is_compound:false },
  { slug:'good-morning', name_fr:'Good morning', name_en:'Good morning', category:'legs', muscle_groups:['hamstring','lower-back','gluteal'], equipment:['barre'], default_sets:3, default_reps:'8-10', default_rest_seconds:90, difficulty:2, form_cue:'Pousse les hanches en arrière. Garde le dos plat. Étire les ischios.', is_compound:true },
  { slug:'hip-thrust', name_fr:'Hip thrust', name_en:'Hip thrust', category:'legs', muscle_groups:['gluteal','hamstring'], equipment:['barre','banc'], default_sets:4, default_reps:'8-12', default_rest_seconds:90, difficulty:2, form_cue:'Hauts dorsaux sur le banc. Pousse fort avec les talons. Serre les fessiers en haut.', is_compound:true },
  { slug:'hip-thrust-une-jambe', name_fr:'Hip thrust une jambe', name_en:'Single-leg hip thrust', category:'legs', muscle_groups:['gluteal','hamstring'], equipment:['banc'], default_sets:3, default_reps:'10-12', default_rest_seconds:75, difficulty:2, form_cue:'Une jambe en l\'air. Excellent pour corriger les déséquilibres.', is_compound:true },
  { slug:'kickback-fessier', name_fr:'Kickback fessier (poulie)', name_en:'Cable glute kickback', category:'legs', muscle_groups:['gluteal'], equipment:['poulie'], default_sets:3, default_reps:'12-15', default_rest_seconds:60, difficulty:1, form_cue:'Pousse la jambe vers l\'arrière. Pic de contraction en haut.', is_compound:false },
  { slug:'adducteurs-machine', name_fr:'Adducteurs machine', name_en:'Hip adduction', category:'legs', muscle_groups:['adductors'], equipment:['machine'], default_sets:3, default_reps:'12-15', default_rest_seconds:60, difficulty:1, form_cue:'Serre les genoux. Travail des intérieurs de cuisse.', is_compound:false },

  // ════════════════════════════ CALVES ════════════════════════════
  { slug:'mollets-debout', name_fr:'Mollets debout', name_en:'Standing calf raise', category:'legs', muscle_groups:['calves'], equipment:['machine'], default_sets:4, default_reps:'12-20', default_rest_seconds:60, difficulty:1, form_cue:'Amplitude complète : étire en bas, contracte en haut.', is_compound:false },
  { slug:'mollets-assis', name_fr:'Mollets assis', name_en:'Seated calf raise', category:'legs', muscle_groups:['calves'], equipment:['machine'], default_sets:3, default_reps:'15-20', default_rest_seconds:60, difficulty:1, form_cue:'Cible le soléaire (mollet profond). Pause en haut.', is_compound:false },

  // ════════════════════════════ ABS / CORE ════════════════════════════
  { slug:'planche', name_fr:'Planche', name_en:'Plank', category:'core', muscle_groups:['abs','obliques','lower-back'], equipment:[], default_sets:3, default_reps:'30-60s', default_rest_seconds:45, difficulty:1, form_cue:'Corps en ligne droite. Ne creuse pas le dos.', is_compound:true },
  { slug:'planche-laterale', name_fr:'Planche latérale', name_en:'Side plank', category:'core', muscle_groups:['obliques','abs'], equipment:[], default_sets:3, default_reps:'30-45s', default_rest_seconds:45, difficulty:1, form_cue:'Coude sous l\'épaule. Pousse les hanches vers le haut.', is_compound:false },
  { slug:'crunch', name_fr:'Crunch', name_en:'Crunch', category:'core', muscle_groups:['abs'], equipment:[], default_sets:3, default_reps:'15-20', default_rest_seconds:45, difficulty:1, form_cue:'Décolle seulement les omoplates. Mains qui ne tirent pas la nuque.', is_compound:false },
  { slug:'relev-jambes', name_fr:'Relevé de jambes (barre)', name_en:'Hanging leg raise', category:'core', muscle_groups:['abs','obliques'], equipment:['barre-tractions'], default_sets:3, default_reps:'8-15', default_rest_seconds:60, difficulty:2, form_cue:'Pas de balancement. Jambes tendues ou pliées au début.', is_compound:false },
  { slug:'mountain-climbers', name_fr:'Mountain climbers', name_en:'Mountain climbers', category:'cardio', muscle_groups:['abs','quadriceps','deltoids'], equipment:[], default_sets:3, default_reps:'30-45s', default_rest_seconds:45, difficulty:1, form_cue:'Position de planche, genoux alternés vers la poitrine. Rythme rapide.', is_compound:true },
  { slug:'russian-twist', name_fr:'Russian twist', name_en:'Russian twist', category:'core', muscle_groups:['obliques','abs'], equipment:['haltere'], default_sets:3, default_reps:'20-30', default_rest_seconds:45, difficulty:1, form_cue:'Pieds levés ou au sol. Rotation contrôlée du buste.', is_compound:false },
  { slug:'hollow-hold', name_fr:'Hollow hold', name_en:'Hollow hold', category:'core', muscle_groups:['abs'], equipment:[], default_sets:3, default_reps:'20-40s', default_rest_seconds:60, difficulty:2, form_cue:'Bas du dos collé au sol. Jambes et bras tendus en l\'air.', is_compound:false },
  { slug:'dead-bug', name_fr:'Dead bug', name_en:'Dead bug', category:'core', muscle_groups:['abs','lower-back'], equipment:[], default_sets:3, default_reps:'10-12', default_rest_seconds:45, difficulty:1, form_cue:'Bras et jambe opposés s\'allongent. Lombaires au sol.', is_compound:false },

  // ════════════════════════════ CARDIO / HIIT ════════════════════════════
  { slug:'burpees', name_fr:'Burpees', name_en:'Burpees', category:'cardio', muscle_groups:['quadriceps','chest','abs','deltoids'], equipment:[], default_sets:4, default_reps:'30s', default_rest_seconds:30, difficulty:3, form_cue:'Descente en planche, pompe, saut. Rythme constant.', is_compound:true },
  { slug:'jumping-jacks', name_fr:'Jumping jacks', name_en:'Jumping jacks', category:'cardio', muscle_groups:['quadriceps','calves','deltoids'], equipment:[], default_sets:3, default_reps:'45-60s', default_rest_seconds:30, difficulty:1, form_cue:'Sauts contrôlés. Excellent échauffement.', is_compound:true },
  { slug:'sprint-tapis', name_fr:'Sprint tapis', name_en:'Treadmill sprint', category:'cardio', muscle_groups:['quadriceps','hamstring','gluteal','calves'], equipment:['tapis'], default_sets:8, default_reps:'30s', default_rest_seconds:60, difficulty:2, form_cue:'Inclinaison 1-2%. Sprint à 90% pendant 30s, marche 60s.', is_compound:true },
  { slug:'velo-hiit', name_fr:'Vélo HIIT', name_en:'Bike HIIT', category:'cardio', muscle_groups:['quadriceps','calves','gluteal'], equipment:['velo'], default_sets:10, default_reps:'30s', default_rest_seconds:30, difficulty:2, form_cue:'30s sprint max, 30s récup active. Cible 85% FCmax.', is_compound:true },
  { slug:'corde-saut', name_fr:'Corde à sauter', name_en:'Jump rope', category:'cardio', muscle_groups:['calves','quadriceps','deltoids'], equipment:['corde'], default_sets:5, default_reps:'1-2min', default_rest_seconds:30, difficulty:1, form_cue:'Petits sauts, poignets qui tournent. Idéal cardio + coordination.', is_compound:true },
  { slug:'box-jumps', name_fr:'Box jumps', name_en:'Box jumps', category:'cardio', muscle_groups:['quadriceps','gluteal','calves'], equipment:['box'], default_sets:4, default_reps:'8-10', default_rest_seconds:75, difficulty:2, form_cue:'Saute, atterris en flexion. Descends sans sauter (sécurité).', is_compound:true },
  { slug:'rameur', name_fr:'Rameur', name_en:'Rowing machine', category:'cardio', muscle_groups:['upper-back','quadriceps','biceps','gluteal'], equipment:['rameur'], default_sets:1, default_reps:'10-20min', default_rest_seconds:0, difficulty:1, form_cue:'Pousse avec les jambes d\'abord, puis tire avec le dos.', is_compound:true },

  // ════════════════════════════ MOBILITY / WARMUP ════════════════════════════
  { slug:'rotations-epaules', name_fr:'Rotations d\'épaules', name_en:'Shoulder rotations', category:'mobility', muscle_groups:['deltoids','upper-back'], equipment:[], default_sets:2, default_reps:'10 chaque sens', default_rest_seconds:0, difficulty:1, form_cue:'Échauffement parfait avant tout push/pull.', is_compound:false },
  { slug:'rotations-hanches', name_fr:'Rotations de hanches', name_en:'Hip rotations', category:'mobility', muscle_groups:['gluteal','adductors'], equipment:[], default_sets:2, default_reps:'10 chaque sens', default_rest_seconds:0, difficulty:1, form_cue:'Sur une jambe ou les deux. Ouvre l\'articulation.', is_compound:false },
  { slug:'chat-vache', name_fr:'Chat-vache', name_en:'Cat-cow', category:'mobility', muscle_groups:['lower-back','abs'], equipment:[], default_sets:2, default_reps:'10-15', default_rest_seconds:0, difficulty:1, form_cue:'Alterne flexion/extension de la colonne. Yoga classique.', is_compound:false },
  { slug:'world-greatest-stretch', name_fr:'World\'s greatest stretch', name_en:'World\'s greatest stretch', category:'mobility', muscle_groups:['hamstring','gluteal','adductors','obliques'], equipment:[], default_sets:2, default_reps:'5 chaque côté', default_rest_seconds:0, difficulty:1, form_cue:'Fente avant, main au sol, rotation vers le haut. Tout le corps.', is_compound:true },
  { slug:'etirement-ischios', name_fr:'Étirement ischios', name_en:'Hamstring stretch', category:'mobility', muscle_groups:['hamstring'], equipment:[], default_sets:2, default_reps:'30s chaque', default_rest_seconds:0, difficulty:1, form_cue:'Assis ou debout. Plie le dos vers la jambe tendue.', is_compound:false },
  { slug:'pigeon-pose', name_fr:'Posture du pigeon', name_en:'Pigeon pose', category:'mobility', muscle_groups:['gluteal','adductors'], equipment:[], default_sets:2, default_reps:'45s chaque', default_rest_seconds:0, difficulty:1, form_cue:'Excellent pour ouvrir les hanches. Tient la position.', is_compound:false },

  // ════════════════════════════ FULL BODY / FUNCTIONAL ════════════════════════════
  { slug:'kettlebell-swing', name_fr:'Kettlebell swing', name_en:'Kettlebell swing', category:'full', muscle_groups:['gluteal','hamstring','lower-back','deltoids'], equipment:['kettlebell'], default_sets:4, default_reps:'15-20', default_rest_seconds:60, difficulty:2, form_cue:'Hip hinge, pas un squat. L\'élan vient des hanches.', is_compound:true },
  { slug:'clean', name_fr:'Clean', name_en:'Clean', category:'full', muscle_groups:['quadriceps','gluteal','trapezius','deltoids','upper-back'], equipment:['barre'], default_sets:5, default_reps:'3-5', default_rest_seconds:120, difficulty:3, form_cue:'Mouvement explosif. Technique avant tout — commence léger.', is_compound:true },
  { slug:'snatch', name_fr:'Snatch (arraché)', name_en:'Snatch', category:'full', muscle_groups:['quadriceps','gluteal','deltoids','trapezius'], equipment:['barre'], default_sets:5, default_reps:'3-5', default_rest_seconds:120, difficulty:3, form_cue:'Du sol au-dessus de la tête en un mouvement. Apprends avec un coach.', is_compound:true },
  { slug:'turkish-get-up', name_fr:'Turkish get-up', name_en:'Turkish get-up', category:'full', muscle_groups:['abs','deltoids','gluteal','quadriceps'], equipment:['kettlebell'], default_sets:3, default_reps:'3-5 chaque', default_rest_seconds:90, difficulty:3, form_cue:'Du sol jusqu\'à debout avec un poids en l\'air. Mouvement complet.', is_compound:true },
  { slug:'thruster', name_fr:'Thruster', name_en:'Thruster', category:'full', muscle_groups:['quadriceps','gluteal','deltoids','triceps'], equipment:['barre'], default_sets:4, default_reps:'8-12', default_rest_seconds:90, difficulty:2, form_cue:'Front squat + développé militaire en un mouvement.', is_compound:true },
  { slug:'farmer-walk', name_fr:'Farmer walk', name_en:'Farmer\'s walk', category:'full', muscle_groups:['trapezius','forearm','abs','quadriceps'], equipment:['halteres'], default_sets:3, default_reps:'30-50m', default_rest_seconds:90, difficulty:1, form_cue:'Marche avec des charges lourdes. Posture droite. Renforce tout.', is_compound:true },

  // ════════════════════════════ POSTERIOR CHAIN ════════════════════════════
  { slug:'hyperextensions', name_fr:'Hyperextensions', name_en:'Back extensions', category:'pull', muscle_groups:['lower-back','gluteal','hamstring'], equipment:['banc-lombaire'], default_sets:3, default_reps:'12-15', default_rest_seconds:75, difficulty:1, form_cue:'Ne dépasse pas l\'horizontale. Bonne ouverture de hanches.', is_compound:false },
  { slug:'nordic-curl', name_fr:'Nordic curl', name_en:'Nordic hamstring curl', category:'legs', muscle_groups:['hamstring','gluteal'], equipment:[], default_sets:3, default_reps:'5-8', default_rest_seconds:90, difficulty:3, form_cue:'À genoux, chevilles bloquées. Descends ultra-lentement. Très dur.', is_compound:false },
  { slug:'pull-through', name_fr:'Pull-through câble', name_en:'Cable pull-through', category:'pull', muscle_groups:['gluteal','hamstring','lower-back'], equipment:['poulie'], default_sets:3, default_reps:'12-15', default_rest_seconds:60, difficulty:1, form_cue:'Hip hinge entre les jambes. Pousse les hanches en avant en remontant.', is_compound:false }
]

console.log(`Seeding ${exercises.length} exercises into exercise_library...\n`)

let success=0,failed=0,errors=[]
for(const ex of exercises){
  const {error}=await sb.from('exercise_library').insert(ex)
  if(error){
    failed++
    errors.push({ex:ex.slug,msg:error.message})
    console.error(`❌ ${ex.slug}: ${error.message}`)
  } else {
    success++
    console.log(`✓ ${ex.name_fr}`)
  }
}

console.log(`\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`)
console.log(`✨ ${success} inserted, ${failed} failed.`)
if(failed){
  console.log(`\nFirst few errors:`)
  errors.slice(0,3).forEach(e=>console.log(`  - ${e.ex}: ${e.msg}`))
}
