#!/usr/bin/env node
// seed_cookbook_batch_2.mjs — Recipes 71-100 (Algerian + Desserts)
// Run: node seed_cookbook_batch_2.mjs

const SB_URL = 'https://korektlpnwuefsagfuvq.supabase.co';
const SB_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvcmVrdGxwbnd1ZWZzYWdmdXZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYwMjI0NjQsImV4cCI6MjA5MTU5ODQ2NH0.46rZOEMUKoZCyL8eKzob8FDuOoFiA2LHbr2ZoKW-HrM';
const H = {'Content-Type':'application/json','apikey':SB_KEY,'Authorization':`Bearer ${SB_KEY}`,'Prefer':'return=representation'};
const q = async (m,p,b) => { const r = await fetch(`${SB_URL}/rest/v1/${p}`,{method:m,headers:H,body:b?JSON.stringify(b):undefined}); return {ok:r.ok,status:r.status,data:await r.json().catch(()=>null)}; };

const RECIPES = [
  // ── ALGERIAN CLASSICS 11-25 (15 new) ─────────────────
  {title:'Mhajeb Poulet Fromage',category:'Algerian Classics',meal_type:'dinner',goal_tag:'all',craving_tag:'salé',prep_time:18,difficulty:2,total_calories:445,total_protein:38,total_carbs:42,total_fat:14,featured:false,photo_gradient:'linear-gradient(135deg,#1a0800,#A0522D)',membership_required:'cookbook',
    ingredients:[{name:'Escalope de poulet',quantity:'150g',calories:180,protein:33,carbs:0,fat:3},{name:'Pain ARRUPAN',quantity:'90g',calories:240,protein:8,carbs:44,fat:3},{name:'Fromage frais Lactel 0%',quantity:'80g',calories:71,protein:6.9,carbs:3.4,fat:2.8},{name:'Tomates',quantity:'60g',calories:11,protein:0.5,carbs:2.3,fat:0.2},{name:'Huile d\'olive',quantity:'5g',calories:45,protein:0,carbs:0,fat:5}],
    steps:['Cuire poulet émincé avec oignon, tomates, paprika.','Étaler pain ARRUPAN en rectangle.','Garnir avec poulet et fromage frais.','Plier en carré comme mhajeb traditionnel.','Cuire à la poêle 3 min par côté sans matière grasse.'],
    substitutions:[{original:'Poulet',alternative:'Dinde même quantité'},{original:'Pain ARRUPAN',alternative:'Galette mhajeb maison traditionnelle'}],coach_note:'Le mhajeb du vendredi — version fit. Le pain ARRUPAN imite parfaitement la galette traditionnelle.'},

  {title:'Tlitli Poulet Tomates',category:'Algerian Classics',meal_type:'dinner',goal_tag:'all',craving_tag:'chaud',prep_time:25,difficulty:2,total_calories:520,total_protein:44,total_carbs:60,total_fat:10,featured:false,photo_gradient:'linear-gradient(135deg,#1a0a00,#FF7F50)',membership_required:'cookbook',
    ingredients:[{name:'Escalope de poulet',quantity:'180g',calories:216,protein:39.6,carbs:0,fat:3.6},{name:'Pâtes tlitli',quantity:'80g cru',calories:280,protein:9.6,carbs:57.6,fat:1.6},{name:'Tomates',quantity:'200g',calories:36,protein:1.8,carbs:7.8,fat:0.4},{name:'Huile d\'olive',quantity:'5g',calories:45,protein:0,carbs:0,fat:5}],
    steps:['Faire revenir poulet en morceaux avec oignon.','Ajouter tomates concassées, ras el hanout, sel.','Couvrir d\'eau, mijoter 15 min.','Ajouter pâtes tlitli, cuire 10 min de plus.','Vérifier consistance, servir bien chaud.'],
    substitutions:[{original:'Tlitli',alternative:'Pâtes courtes type coquillettes'},{original:'Poulet',alternative:'Dinde ou viande de bœuf maigre'}],coach_note:'Le tlitli de ta mère — plat constantinois authentique. Les pâtes cuites dans la sauce absorbent toutes les saveurs.'},

  {title:'Baghrir Protéiné Miel Yaourt',category:'Algerian Classics',meal_type:'breakfast',goal_tag:'muscle',craving_tag:'sucré',prep_time:15,difficulty:2,total_calories:425,total_protein:24,total_carbs:62,total_fat:9,featured:true,photo_gradient:'linear-gradient(135deg,#1a1000,#F4A460)',membership_required:'cookbook',
    ingredients:[{name:'Flocons d\'avoine mixés',quantity:'70g',calories:266,protein:9.1,carbs:42,fat:4.9},{name:'Œufs entiers',quantity:'1 (60g)',calories:70,protein:6,carbs:1,fat:5},{name:'Fromage frais Lactel 0%',quantity:'80g',calories:71,protein:6.9,carbs:3.4,fat:2.8},{name:'Banane',quantity:'20g',calories:18,protein:0.2,carbs:4.6,fat:0}],
    steps:['Mixer avoine en farine fine.','Mélanger avec œuf, fromage frais, eau pour pâte fluide.','Levure chimique 1 cc pour les mille trous.','Cuire à la poêle 2 min un seul côté.','Servir avec banane écrasée + cannelle.'],
    substitutions:[{original:'Banane',alternative:'5g miel pour version traditionnelle'},{original:'Œuf',alternative:'Aquafaba pour version vegan'}],coach_note:'Les mille trous algériens — version protéinée. La levure crée les trous, l\'avoine remplace la semoule. Stupéfiant.'},

  {title:'Sfenj Protéiné Four',category:'Algerian Classics',meal_type:'breakfast',goal_tag:'all',craving_tag:'sucré',prep_time:12,difficulty:2,total_calories:380,total_protein:18,total_carbs:54,total_fat:10,featured:false,photo_gradient:'linear-gradient(135deg,#1a1000,#FFD700)',membership_required:'cookbook',
    ingredients:[{name:'Flocons d\'avoine mixés',quantity:'60g',calories:228,protein:7.8,carbs:36,fat:4.2},{name:'Œufs entiers',quantity:'1 (60g)',calories:70,protein:6,carbs:1,fat:5},{name:'Fromage frais Lactel 0%',quantity:'60g',calories:53,protein:5.2,carbs:2.6,fat:2.1},{name:'Banane',quantity:'40g',calories:36,protein:0.4,carbs:9.2,fat:0}],
    steps:['Mixer avoine en farine.','Mélanger tous les ingrédients en pâte épaisse.','Former des beignets sur plaque four.','Four 190°C 15-18 min jusqu\'à doré.','Servir saupoudré de cannelle.'],
    substitutions:[{original:'Banane',alternative:'Compote de pomme 40g'},{original:'Four',alternative:'Airfryer 180°C 10 min'}],coach_note:'Le sfenj du dimanche matin — sans bain d\'huile. Texture moelleuse identique au four.'},

  {title:'Berkoukes Légumes Poulet',category:'Algerian Classics',meal_type:'dinner',goal_tag:'all',craving_tag:'chaud',prep_time:25,difficulty:2,total_calories:495,total_protein:42,total_carbs:54,total_fat:12,featured:false,photo_gradient:'linear-gradient(135deg,#1a0800,#A0522D)',membership_required:'cookbook',
    ingredients:[{name:'Escalope de poulet',quantity:'150g',calories:180,protein:33,carbs:0,fat:3},{name:'Berkoukes (gros couscous)',quantity:'70g cru',calories:245,protein:8.4,carbs:51,fat:0.7},{name:'Tomates',quantity:'150g',calories:27,protein:1.4,carbs:5.9,fat:0.3},{name:'Carottes',quantity:'100g',calories:41,protein:0.9,carbs:9.6,fat:0.2},{name:'Huile d\'olive',quantity:'8g',calories:72,protein:0,carbs:0,fat:8}],
    steps:['Faire revenir poulet en morceaux avec oignon.','Ajouter tomates concassées, carottes, navets, courgettes.','Verser eau, mijoter 15 min.','Ajouter berkoukes, cuire 10 min jusqu\'à tendre.','Servir bien chaud avec persil frais.'],
    substitutions:[{original:'Berkoukes',alternative:'Gros couscous moyen'},{original:'Poulet',alternative:'Agneau maigre pour version traditionnelle'}],coach_note:'Le berkoukes — soupe-plat algérien qui réchauffe l\'âme. Mijoté longtemps, les saveurs deviennent profondes.'},

  {title:'Loubia Blanche Tomates',category:'Algerian Classics',meal_type:'lunch',goal_tag:'all',craving_tag:'chaud',prep_time:20,difficulty:1,total_calories:445,total_protein:28,total_carbs:62,total_fat:10,featured:false,photo_gradient:'linear-gradient(135deg,#1a0a00,#CD853F)',membership_required:'cookbook',
    ingredients:[{name:'Haricots blancs cuits',quantity:'200g',calories:280,protein:18,carbs:50,fat:1.2},{name:'Escalope de poulet',quantity:'80g',calories:96,protein:17.6,carbs:0,fat:1.6},{name:'Tomates',quantity:'150g',calories:27,protein:1.4,carbs:5.9,fat:0.3},{name:'Huile d\'olive',quantity:'8g',calories:72,protein:0,carbs:0,fat:8}],
    steps:['Faire revenir poulet émincé avec oignon, ail, cumin.','Ajouter tomates concassées, paprika, sel.','Incorporer haricots blancs égouttés.','Mijoter 10 min, ajuster consistance avec eau.','Servir avec persil et un filet d\'huile.'],
    substitutions:[{original:'Haricots cuits',alternative:'Haricots secs trempés la veille + cuisson 1h'},{original:'Poulet',alternative:'Sans viande pour version végétarienne'}],coach_note:'La loubia algérienne — protéine végétale + animale combinées. Comfort food parfait pour les jours froids.'},

  {title:'Hmiss Salade Tomates Grillées',category:'Algerian Classics',meal_type:'side',goal_tag:'fat_loss',craving_tag:'frais',prep_time:15,difficulty:2,total_calories:185,total_protein:6,total_carbs:18,total_fat:11,featured:false,photo_gradient:'linear-gradient(135deg,#1a0000,#B22222)',membership_required:'cookbook',
    ingredients:[{name:'Tomates',quantity:'250g',calories:45,protein:2.3,carbs:9.8,fat:0.5},{name:'Poivrons',quantity:'150g',calories:35,protein:1.2,carbs:7.9,fat:0.5},{name:'Huile d\'olive',quantity:'10g',calories:90,protein:0,carbs:0,fat:10},{name:'Œuf entier',quantity:'1/2 (30g)',calories:35,protein:3,carbs:0.5,fat:2.5}],
    steps:['Griller tomates et poivrons directement sur flamme ou four 200°C.','Peler les peaux noircies.','Écraser au mortier avec ail, sel, cumin.','Incorporer huile d\'olive en filet.','Œuf dur émietté par-dessus.'],
    substitutions:[{original:'Œuf dur',alternative:'Thon 30g pour version protéinée +30kcal'},{original:'Cumin',alternative:'Carvi pour variation algéroise'}],coach_note:'L\'accompagnement parfait de tout plat algérien. Grillé sur flamme = goût fumé authentique.'},

  {title:'Chorba Frik Légère',category:'Algerian Classics',meal_type:'dinner',goal_tag:'fat_loss',craving_tag:'chaud',prep_time:20,difficulty:2,total_calories:320,total_protein:32,total_carbs:36,total_fat:6,featured:false,photo_gradient:'linear-gradient(135deg,#1a0800,#CD5C5C)',membership_required:'cookbook',
    ingredients:[{name:'Escalope de poulet',quantity:'150g',calories:180,protein:33,carbs:0,fat:3},{name:'Frik (blé concassé)',quantity:'40g cru',calories:140,protein:5.6,carbs:28,fat:0.8},{name:'Tomates',quantity:'150g',calories:27,protein:1.4,carbs:5.9,fat:0.3},{name:'Huile d\'olive',quantity:'3g',calories:27,protein:0,carbs:0,fat:3}],
    steps:['Cuire poulet émincé avec oignon, cannelle, sel.','Ajouter tomates pelées, ras el hanout.','Verser 800ml eau, mijoter 15 min.','Ajouter frik, cuire 10 min jusqu\'à tendre.','Citron + coriandre + menthe fraîche au service.'],
    substitutions:[{original:'Frik',alternative:'Boulgour ou quinoa pour variation'},{original:'Poulet',alternative:'Pois chiches pour version végé'}],coach_note:'La chorba de Ramadan — version léger pour toute l\'année. Réchauffe sans alourdir.'},

  {title:'Boulettes Viande Sauce Tomate',category:'Algerian Classics',meal_type:'dinner',goal_tag:'all',craving_tag:'chaud',prep_time:25,difficulty:2,total_calories:485,total_protein:42,total_carbs:38,total_fat:18,featured:true,photo_gradient:'linear-gradient(135deg,#1a0000,#8B0000)',membership_required:'cookbook',
    ingredients:[{name:'Steak haché',quantity:'150g',calories:375,protein:39,carbs:0,fat:25.5},{name:'Riz blanc',quantity:'50g cru',calories:180,protein:3.5,carbs:39,fat:0.5},{name:'Tomates',quantity:'200g',calories:36,protein:1.8,carbs:7.8,fat:0.4},{name:'Œuf entier',quantity:'1/2 (30g)',calories:35,protein:3,carbs:0.5,fat:2.5},{name:'Huile d\'olive',quantity:'5g',calories:45,protein:0,carbs:0,fat:5}],
    steps:['Mélanger steak haché avec œuf battu, persil, sel, poivre, cumin.','Former petites boulettes de 25g.','Cuire la sauce : tomates + oignon + ail + paprika + 200ml eau.','Pocher les boulettes dans la sauce 15 min.','Servir sur lit de riz blanc.'],
    substitutions:[{original:'Steak haché',alternative:'Dinde hachée pour version plus légère'},{original:'Riz blanc',alternative:'Couscous ou purée de pommes de terre'}],coach_note:'Les boulettes de Maman — recette familiale algérienne. Cuites dans la sauce, elles restent juteuses et absorbent les saveurs.'},

  {title:'Chtitha Poulet Pommes de Terre',category:'Algerian Classics',meal_type:'dinner',goal_tag:'all',craving_tag:'chaud',prep_time:25,difficulty:2,total_calories:495,total_protein:42,total_carbs:44,total_fat:14,featured:false,photo_gradient:'linear-gradient(135deg,#1a0000,#DC143C)',membership_required:'cookbook',
    ingredients:[{name:'Escalope de poulet',quantity:'180g',calories:216,protein:39.6,carbs:0,fat:3.6},{name:'Pommes de terre',quantity:'200g',calories:160,protein:4,carbs:36,fat:0},{name:'Tomates',quantity:'150g',calories:27,protein:1.4,carbs:5.9,fat:0.3},{name:'Huile d\'olive',quantity:'8g',calories:72,protein:0,carbs:0,fat:8}],
    steps:['Faire revenir poulet en morceaux avec oignon, ail, paprika fort.','Ajouter tomates concassées, harissa, cumin.','Incorporer pommes de terre en cubes.','Verser eau juste pour couvrir, mijoter 20 min.','Persil frais au service.'],
    substitutions:[{original:'Harissa',alternative:'Paprika doux pour version sans piquant'},{original:'Pommes de terre',alternative:'Courgettes pour version moins glucidique'}],coach_note:'La chtitha — version épicée du tajine algérien. La harissa réveille tous les autres ingrédients.'},

  {title:'Lablabi (Soupe Pois Chiches)',category:'Algerian Classics',meal_type:'lunch',goal_tag:'fat_loss',craving_tag:'chaud',prep_time:15,difficulty:1,total_calories:395,total_protein:24,total_carbs:52,total_fat:10,featured:false,photo_gradient:'linear-gradient(135deg,#1a0a00,#D2B48C)',membership_required:'cookbook',
    ingredients:[{name:'Pois chiches cuits',quantity:'200g',calories:328,protein:17.8,carbs:54.8,fat:5.2},{name:'Pain ARRUPAN',quantity:'45g',calories:120,protein:4,carbs:22,fat:1.5},{name:'Œuf entier',quantity:'1 (60g)',calories:70,protein:6,carbs:1,fat:5},{name:'Huile d\'olive',quantity:'4g',calories:36,protein:0,carbs:0,fat:4}],
    steps:['Chauffer pois chiches dans leur bouillon + ail + cumin + harissa.','Émietter pain ARRUPAN dans bol.','Verser pois chiches chauds par-dessus.','Casser un œuf cru qui cuit avec la chaleur.','Citron + harissa au goût.'],
    substitutions:[{original:'Œuf cru',alternative:'Œuf dur en quartiers'},{original:'Harissa',alternative:'Paprika pour version moins épicée'}],coach_note:'La lablabi — petit déj tunisien adopté par l\'Algérie. Hivernal, économique, ultra protéiné.'},

  {title:'Salade Mechouia Grillée',category:'Algerian Classics',meal_type:'side',goal_tag:'fat_loss',craving_tag:'frais',prep_time:20,difficulty:2,total_calories:220,total_protein:12,total_carbs:18,total_fat:12,featured:false,photo_gradient:'linear-gradient(135deg,#0a1a00,#556B2F)',membership_required:'cookbook',
    ingredients:[{name:'Tomates',quantity:'200g',calories:36,protein:1.8,carbs:7.8,fat:0.4},{name:'Poivrons',quantity:'150g',calories:35,protein:1.2,carbs:7.9,fat:0.5},{name:'Œufs entiers',quantity:'1 (60g)',calories:70,protein:6,carbs:1,fat:5},{name:'Thon naturel',quantity:'30g',calories:35,protein:7.8,carbs:0,fat:0.3},{name:'Huile d\'olive',quantity:'5g',calories:45,protein:0,carbs:0,fat:5}],
    steps:['Griller tomates et poivrons sur flamme ou four 220°C.','Peler les peaux noircies.','Hacher grossièrement, mélanger avec ail écrasé, cumin, sel.','Garnir avec œuf dur en quartiers et thon émietté.','Filet d\'huile d\'olive + olives noires.'],
    substitutions:[{original:'Thon',alternative:'Sardines à l\'huile égouttées'},{original:'Œuf dur',alternative:'Câpres + persil pour version végé'}],coach_note:'La mechouia — salade tunisienne devenue culte au Maghreb. Le secret : grillage direct flamme.'},

  {title:'Pkaila (Plat Juif Algérien)',category:'Algerian Classics',meal_type:'dinner',goal_tag:'all',craving_tag:'chaud',prep_time:30,difficulty:3,total_calories:525,total_protein:44,total_carbs:38,total_fat:18,featured:false,photo_gradient:'linear-gradient(135deg,#001a00,#228B22)',membership_required:'cookbook',
    ingredients:[{name:'Escalope de poulet',quantity:'180g',calories:216,protein:39.6,carbs:0,fat:3.6},{name:'Épinards congelés',quantity:'200g',calories:46,protein:5.8,carbs:7.4,fat:0.4},{name:'Haricots blancs cuits',quantity:'150g',calories:210,protein:13.5,carbs:37.5,fat:0.9},{name:'Huile d\'olive',quantity:'10g',calories:90,protein:0,carbs:0,fat:10}],
    steps:['Faire revenir épinards dans huile jusqu\'à très foncés (clé du goût).','Ajouter poulet en morceaux, ail, cumin, sel.','Incorporer haricots blancs et eau.','Mijoter 20 min à couvert.','Servir avec riz blanc ou pain.'],
    substitutions:[{original:'Épinards',alternative:'Blettes ou bettes pour version traditionnelle'},{original:'Poulet',alternative:'Bœuf maigre 180g pour version riche'}],coach_note:'La pkaila — patrimoine juif-algérien. Les épinards bien noircis donnent le goût caractéristique.'},

  {title:'Maakouda Pommes de Terre Four',category:'Algerian Classics',meal_type:'lunch',goal_tag:'all',craving_tag:'salé',prep_time:25,difficulty:2,total_calories:385,total_protein:24,total_carbs:42,total_fat:14,featured:false,photo_gradient:'linear-gradient(135deg,#1a1000,#DAA520)',membership_required:'cookbook',
    ingredients:[{name:'Pommes de terre',quantity:'200g',calories:160,protein:4,carbs:36,fat:0},{name:'Œufs entiers',quantity:'2 (120g)',calories:140,protein:12,carbs:2,fat:10},{name:'Escalope de dinde hachée',quantity:'60g',calories:66,protein:13.2,carbs:0,fat:0.6},{name:'Fromage frais Lactel 0%',quantity:'30g',calories:27,protein:2.6,carbs:1.3,fat:1.1}],
    steps:['Cuire pommes de terre 15 min eau bouillante.','Écraser, mélanger avec œufs battus, dinde, persil, ail.','Former galettes plates.','Four 200°C 20 min sur plaque huilée.','Servir avec sauce fromage frais + citron.'],
    substitutions:[{original:'Dinde',alternative:'Thon en boîte 60g pour version express'},{original:'Four',alternative:'Airfryer 190°C 12 min'}],coach_note:'La maakouda — version four, pas friture. Croustillante dehors, fondante dedans. Goûter d\'enfance retrouvé.'},

  {title:'Couscous au Poisson',category:'Algerian Classics',meal_type:'dinner',goal_tag:'fat_loss',craving_tag:'chaud',prep_time:30,difficulty:3,total_calories:495,total_protein:42,total_carbs:62,total_fat:8,featured:false,photo_gradient:'linear-gradient(135deg,#001a1a,#4682B4)',membership_required:'cookbook',
    ingredients:[{name:'Poisson blanc',quantity:'200g',calories:170,protein:40,carbs:0,fat:2},{name:'Couscous cru',quantity:'80g',calories:285,protein:9.6,carbs:59.2,fat:0.8},{name:'Tomates',quantity:'100g',calories:18,protein:0.9,carbs:3.9,fat:0.2},{name:'Carottes',quantity:'80g',calories:33,protein:0.7,carbs:7.7,fat:0.2},{name:'Huile d\'olive',quantity:'4g',calories:36,protein:0,carbs:0,fat:4}],
    steps:['Préparer bouillon : tomates + carottes + courgettes + épices.','Cuire poisson dans le bouillon les 5 dernières minutes.','Préparer semoule : eau bouillante 1:1, gonflage couvert 5 min.','Servir semoule + légumes + poisson + bouillon.','Citron en quartiers à côté.'],
    substitutions:[{original:'Poisson blanc',alternative:'Saumon 180g pour version riche'},{original:'Couscous',alternative:'Quinoa 70g pour version sans gluten'}],coach_note:'Le couscous de la côte algéroise — version pêcheur. Poisson maigre + bouillon léger = plat de cut parfait.'},

  // ── HIGH PROTEIN DESSERTS 6-25 (15 new) ──────────────
  {title:'Cheesecake Sans Cuisson',category:'Desserts',meal_type:'snack',goal_tag:'all',craving_tag:'sucré',prep_time:10,difficulty:1,total_calories:295,total_protein:24,total_carbs:24,total_fat:10,featured:true,photo_gradient:'linear-gradient(135deg,#1a1000,#F0E68C)',membership_required:'cookbook',
    ingredients:[{name:'Fromage frais Lactel 0%',quantity:'200g',calories:178,protein:17.2,carbs:8.6,fat:7},{name:'Flocons d\'avoine',quantity:'30g',calories:114,protein:3.9,carbs:18,fat:2.1},{name:'Beurre de cacahuète',quantity:'5g',calories:30,protein:1.25,carbs:1,fat:2.5},{name:'Banane',quantity:'30g',calories:27,protein:0.3,carbs:6.9,fat:0}],
    steps:['Base : mixer avoine + beurre cacahuète + banane écrasée.','Tasser dans le fond d\'un ramequin.','Mélanger fromage frais avec vanille + citron + un peu de banane.','Verser sur la base.','Frigo 2h minimum, idéalement nuit.'],
    substitutions:[{original:'Banane base',alternative:'Datte écrasée 15g'},{original:'Vanille',alternative:'Cacao pour version chocolat'}],coach_note:'Le cheesecake instagrammable — sans four, sans calories. 24g de protéines dans une vraie pâtisserie.'},

  {title:'Yaourt Glacé Fraise',category:'Desserts',meal_type:'snack',goal_tag:'fat_loss',craving_tag:'frais',prep_time:5,difficulty:1,total_calories:225,total_protein:18,total_carbs:30,total_fat:4,featured:false,photo_gradient:'linear-gradient(135deg,#1a0010,#FF1493)',membership_required:'cookbook',
    ingredients:[{name:'Fromage frais Lactel 0%',quantity:'200g',calories:178,protein:17.2,carbs:8.6,fat:7},{name:'Fraises congelées',quantity:'150g',calories:48,protein:1,carbs:11.6,fat:0.4}],
    steps:['Mettre fraises congelées et fromage frais dans blender.','Mixer 60 secondes — texture glace italienne.','Servir immédiatement ou remettre 10 min au congélateur.','Décorer avec menthe fraîche.','Option : 5g miel pour version plus sucrée.'],
    substitutions:[{original:'Fraises',alternative:'Mangue congelée pour version tropicale'},{original:'Fromage frais',alternative:'Yaourt grec 0% pour texture plus liquide'}],coach_note:'Le froyo Instagram — version maison à 225kcal. Texture identique grâce aux fruits congelés.'},

  {title:'Brownies Avoine Chocolat',category:'Desserts',meal_type:'snack',goal_tag:'muscle',craving_tag:'sucré',prep_time:15,difficulty:2,total_calories:248,total_protein:14,total_carbs:30,total_fat:8,featured:true,photo_gradient:'linear-gradient(135deg,#0a0000,#1a0000)',membership_required:'cookbook',
    ingredients:[{name:'Flocons d\'avoine mixés',quantity:'40g',calories:152,protein:5.2,carbs:24,fat:2.8},{name:'Œuf entier',quantity:'1 (60g)',calories:70,protein:6,carbs:1,fat:5},{name:'Fromage frais Lactel 0%',quantity:'60g',calories:53,protein:5.2,carbs:2.6,fat:2.1},{name:'Cacao en poudre',quantity:'15g',calories:37,protein:1.5,carbs:5.3,fat:1.2},{name:'Banane',quantity:'50g',calories:45,protein:0.5,carbs:11.5,fat:0}],
    steps:['Mixer avoine en farine, mélanger avec cacao tamisé.','Écraser banane, ajouter œuf et fromage frais.','Incorporer aux secs jusqu\'à pâte homogène.','Verser dans moule petit format.','Four 175°C 20 min. Surveillage important — ne pas trop cuire.'],
    substitutions:[{original:'Banane',alternative:'40g compote de pomme + 5g miel'},{original:'Cacao',alternative:'Cacao + pépites chocolat noir pour version riche'}],coach_note:'Le brownie qui reste FONDANT au centre. Secret : sortir AVANT cuisson complète (légèrement humide au couteau).'},

  {title:'Pudding Chia Vanille',category:'Desserts',meal_type:'snack',goal_tag:'all',craving_tag:'sucré',prep_time:5,difficulty:1,total_calories:285,total_protein:18,total_carbs:32,total_fat:10,featured:false,photo_gradient:'linear-gradient(135deg,#1a1000,#F5DEB3)',membership_required:'cookbook',
    ingredients:[{name:'Graines de chia',quantity:'20g',calories:97,protein:3.4,carbs:8.4,fat:6.2},{name:'Fromage frais Lactel 0%',quantity:'150g',calories:134,protein:12.9,carbs:6.5,fat:5.3},{name:'Lait écrémé',quantity:'100ml',calories:35,protein:3.5,carbs:5,fat:0.1},{name:'Banane',quantity:'30g',calories:27,protein:0.3,carbs:6.9,fat:0}],
    steps:['Mélanger chia + lait + vanille dans un bocal.','Laisser 5 min, remuer à nouveau (évite les grumeaux).','Frigo 4h minimum (ou la veille).','Au moment de servir : incorporer fromage frais.','Garnir de banane.'],
    substitutions:[{original:'Banane',alternative:'Fruits rouges 50g pour version antioxydants'},{original:'Vanille',alternative:'Cacao pour version chocolat'}],coach_note:'Le pudding chia — superfood mainstream. Préparé la veille = petit déj prêt en 0 minute le matin.'},

  {title:'Glace Avocat Chocolat',category:'Desserts',meal_type:'snack',goal_tag:'all',craving_tag:'frais',prep_time:5,difficulty:1,total_calories:268,total_protein:15,total_carbs:24,total_fat:12,featured:false,photo_gradient:'linear-gradient(135deg,#0a0000,#2F4F2F)',membership_required:'cookbook',
    ingredients:[{name:'Avocat',quantity:'80g',calories:128,protein:1.6,carbs:7.2,fat:12},{name:'Fromage frais Lactel 0%',quantity:'150g',calories:134,protein:12.9,carbs:6.5,fat:5.3},{name:'Cacao en poudre',quantity:'10g',calories:25,protein:1,carbs:3.5,fat:0.8},{name:'Banane congelée',quantity:'50g',calories:45,protein:0.5,carbs:11.5,fat:0}],
    steps:['Mixer avocat + banane congelée + cacao + fromage frais.','Texture crémeuse — ajouter glaçons si trop liquide.','Servir immédiatement ou frigo 20 min pour fermeté.','Décorer avec copeaux de cacao.','Option : 5g miel.'],
    substitutions:[{original:'Avocat',alternative:'Plus de banane congelée pour version moins grasse'},{original:'Cacao',alternative:'Beurre de cacahuète pour version PB'}],coach_note:'Personne ne soupçonne l\'avocat. Texture ultra crémeuse, goût chocolat dominant. Test sur tes amis.'},

  {title:'Energy Balls Cacao Avoine',category:'Desserts',meal_type:'snack',goal_tag:'muscle',craving_tag:'sucré',prep_time:15,difficulty:1,total_calories:225,total_protein:8,total_carbs:30,total_fat:8,featured:false,photo_gradient:'linear-gradient(135deg,#0a0000,#3D0000)',membership_required:'cookbook',
    ingredients:[{name:'Flocons d\'avoine',quantity:'30g',calories:114,protein:3.9,carbs:18,fat:2.1},{name:'Dattes',quantity:'30g',calories:83,protein:0.5,carbs:22.5,fat:0.1},{name:'Beurre de cacahuète',quantity:'10g',calories:60,protein:2.5,carbs:2,fat:5},{name:'Cacao en poudre',quantity:'5g',calories:12,protein:0.5,carbs:1.8,fat:0.4}],
    steps:['Mixer dattes en pâte.','Mélanger avec beurre de cacahuète et cacao.','Incorporer flocons d\'avoine.','Former boules de 25g avec mains humides.','Frigo 30 min pour raffermir. Conservation 1 semaine.'],
    substitutions:[{original:'Dattes',alternative:'Raisins secs + 5g miel'},{original:'Cacao',alternative:'Cannelle pour version épicée'}],coach_note:'L\'en-cas pré-entraînement parfait. Sucres rapides (dattes) + protéines + bons gras. Énergie 2h garantie.'},

  {title:'Tarte Banane Avoine Choco',category:'Desserts',meal_type:'snack',goal_tag:'all',craving_tag:'sucré',prep_time:25,difficulty:2,total_calories:325,total_protein:16,total_carbs:48,total_fat:8,featured:false,photo_gradient:'linear-gradient(135deg,#1a0a00,#A0522D)',membership_required:'cookbook',
    ingredients:[{name:'Flocons d\'avoine',quantity:'50g',calories:190,protein:6.5,carbs:30,fat:3.5},{name:'Banane',quantity:'100g',calories:89,protein:1,carbs:23,fat:0},{name:'Œuf entier',quantity:'1 (60g)',calories:70,protein:6,carbs:1,fat:5},{name:'Cacao en poudre',quantity:'5g',calories:12,protein:0.5,carbs:1.8,fat:0.4}],
    steps:['Base : avoine mixée + œuf + 1/2 banane écrasée. Tasser dans moule.','Four 10 min à 180°C pour pré-cuire.','Trancher l\'autre demi-banane, disposer sur la base.','Saupoudrer cacao.','Four 10 min de plus.'],
    substitutions:[{original:'Cacao',alternative:'Cannelle pour version pomme'},{original:'Banane',alternative:'Pomme tranchée pour tarte aux pommes'}],coach_note:'La tarte du dimanche — version individuelle. 8 minutes de préparation, 20 minutes de four.'},

  {title:'Trifle Fromage Frais Fruits',category:'Desserts',meal_type:'snack',goal_tag:'fat_loss',craving_tag:'sucré',prep_time:5,difficulty:1,total_calories:215,total_protein:18,total_carbs:24,total_fat:6,featured:false,photo_gradient:'linear-gradient(135deg,#1a0a00,#FF6B6B)',membership_required:'cookbook',
    ingredients:[{name:'Fromage frais Lactel 0%',quantity:'200g',calories:178,protein:17.2,carbs:8.6,fat:7},{name:'Banane',quantity:'80g',calories:71,protein:0.8,carbs:18.4,fat:0},{name:'Flocons d\'avoine',quantity:'10g',calories:38,protein:1.3,carbs:6,fat:0.7},{name:'Cacao en poudre',quantity:'3g',calories:7,protein:0.3,carbs:1.1,fat:0.2}],
    steps:['Couper la banane en rondelles fines.','Dans un verre, alterner : couche fromage frais, couche banane, couche fromage frais.','Saupoudrer avoine + cacao au sommet.','Frigo 10 min pour fraîcheur.','Servir dans verres transparents pour effet visuel.'],
    substitutions:[{original:'Banane',alternative:'Fruits rouges pour version été'},{original:'Cacao',alternative:'Cannelle pour version douce'}],coach_note:'Le trifle anglais — version 5 minutes. Beau visuellement, parfait pour invités.'},

  {title:'Soufflé Chocolat Sans Farine',category:'Desserts',meal_type:'snack',goal_tag:'all',craving_tag:'sucré',prep_time:15,difficulty:3,total_calories:185,total_protein:15,total_carbs:14,total_fat:8,featured:false,photo_gradient:'linear-gradient(135deg,#0a0000,#1a0000)',membership_required:'cookbook',
    ingredients:[{name:'Œufs entiers',quantity:'2 (120g)',calories:140,protein:12,carbs:2,fat:10},{name:'Fromage frais Lactel 0%',quantity:'50g',calories:45,protein:4.3,carbs:2.2,fat:1.8},{name:'Cacao en poudre',quantity:'10g',calories:25,protein:1,carbs:3.5,fat:0.8},{name:'Banane',quantity:'30g',calories:27,protein:0.3,carbs:6.9,fat:0}],
    steps:['Séparer blancs et jaunes.','Mélanger jaunes + fromage frais + cacao + banane écrasée.','Monter les blancs en neige ferme.','Incorporer délicatement aux jaunes.','Verser dans ramequins. Four 180°C 12 min — NE PAS OUVRIR.'],
    substitutions:[{original:'Cacao',alternative:'Beurre de cacahuète pour version PB'},{original:'Banane',alternative:'5g miel + vanille pour version classique'}],coach_note:'Le soufflé — challenge ultime de pâtisserie. Servi IMMÉDIATEMENT — il retombe sinon. Spectaculaire.'},

  {title:'Tiramisu Fit',category:'Desserts',meal_type:'snack',goal_tag:'all',craving_tag:'sucré',prep_time:15,difficulty:2,total_calories:295,total_protein:22,total_carbs:30,total_fat:9,featured:true,photo_gradient:'linear-gradient(135deg,#1a0a00,#8B4513)',membership_required:'cookbook',
    ingredients:[{name:'Pain ARRUPAN',quantity:'45g',calories:120,protein:4,carbs:22,fat:1.5},{name:'Fromage frais Lactel 0%',quantity:'200g',calories:178,protein:17.2,carbs:8.6,fat:7},{name:'Œuf entier',quantity:'1 jaune (20g)',calories:55,protein:2.7,carbs:0.5,fat:4.5},{name:'Cacao en poudre',quantity:'5g',calories:12,protein:0.5,carbs:1.8,fat:0.4}],
    steps:['Tremper pain ARRUPAN dans café fort + vanille.','Mélanger fromage frais + jaune d\'œuf battu + vanille.','Disposer pain au fond du verre.','Recouvrir de crème fromage frais.','Saupoudrer cacao en poudre. Frigo 2h.'],
    substitutions:[{original:'Pain ARRUPAN',alternative:'Biscuits sponge si version moins fit'},{original:'Jaune cru',alternative:'Supprimer pour version sans œuf cru'}],coach_note:'Le tiramisu italien — version macros. Le pain ARRUPAN imbibé ressemble exactement aux biscuits cuillère.'},

  {title:'Crumble Pommes Avoine',category:'Desserts',meal_type:'snack',goal_tag:'all',craving_tag:'sucré',prep_time:20,difficulty:1,total_calories:285,total_protein:10,total_carbs:42,total_fat:9,featured:false,photo_gradient:'linear-gradient(135deg,#1a0800,#CD853F)',membership_required:'cookbook',
    ingredients:[{name:'Pomme',quantity:'200g',calories:104,protein:0,carbs:28,fat:0},{name:'Flocons d\'avoine',quantity:'30g',calories:114,protein:3.9,carbs:18,fat:2.1},{name:'Beurre de cacahuète',quantity:'5g',calories:30,protein:1.25,carbs:1,fat:2.5},{name:'Fromage frais Lactel 0%',quantity:'40g',calories:36,protein:3.4,carbs:1.7,fat:1.4}],
    steps:['Couper pommes en cubes, disposer dans ramequin.','Mélanger avoine + beurre de cacahuète + cannelle pour topping.','Émietter le topping sur les pommes.','Four 180°C 20 min.','Servir tiède avec fromage frais à côté (substitut crème).'],
    substitutions:[{original:'Pommes',alternative:'Poires + cannelle pour variation'},{original:'Beurre cacahuète',alternative:'5g beurre classique pour version traditionnelle'}],coach_note:'Le crumble anglais — version fit. Le fromage frais frais à côté contraste avec la pomme chaude.'},

  {title:'Pancakes Fluffy Banane',category:'Desserts',meal_type:'snack',goal_tag:'muscle',craving_tag:'sucré',prep_time:10,difficulty:2,total_calories:325,total_protein:22,total_carbs:38,total_fat:10,featured:false,photo_gradient:'linear-gradient(135deg,#1a0800,#DEB887)',membership_required:'cookbook',
    ingredients:[{name:'Flocons d\'avoine mixés',quantity:'40g',calories:152,protein:5.2,carbs:24,fat:2.8},{name:'Œuf entier',quantity:'1 (60g)',calories:70,protein:6,carbs:1,fat:5},{name:'Fromage frais Lactel 0%',quantity:'80g',calories:71,protein:6.9,carbs:3.4,fat:2.8},{name:'Banane',quantity:'40g',calories:36,protein:0.4,carbs:9.2,fat:0}],
    steps:['Séparer blanc et jaune.','Mélanger jaune + avoine + fromage frais + banane.','Monter le blanc en neige, incorporer délicatement.','Cuire à la poêle 3 min par côté, feu très doux.','Empiler 3-4 pancakes pour effet "fluffy".'],
    substitutions:[{original:'Banane',alternative:'5g miel'},{original:'1 œuf',alternative:'2 blancs pour version plus protéinée'}],coach_note:'Les pancakes japonais soufflés. Le blanc monté donne le côté "fluffy" Instagram. Patience à la cuisson.'},

  {title:'Glace Banane PB Choco',category:'Desserts',meal_type:'snack',goal_tag:'muscle',craving_tag:'frais',prep_time:5,difficulty:1,total_calories:298,total_protein:14,total_carbs:36,total_fat:10,featured:false,photo_gradient:'linear-gradient(135deg,#1a0800,#8B4513)',membership_required:'cookbook',
    ingredients:[{name:'Banane congelée',quantity:'150g',calories:134,protein:1.5,carbs:34.5,fat:0},{name:'Fromage frais Lactel 0%',quantity:'100g',calories:89,protein:8.6,carbs:4.3,fat:3.5},{name:'Beurre de cacahuète',quantity:'10g',calories:60,protein:2.5,carbs:2,fat:5},{name:'Cacao en poudre',quantity:'5g',calories:12,protein:0.5,carbs:1.8,fat:0.4}],
    steps:['Banane congelée la veille en morceaux.','Mixer avec fromage frais jusqu\'à texture glace.','Incorporer beurre de cacahuète et cacao.','Servir immédiatement.','Option : copeaux de chocolat noir 5g.'],
    substitutions:[{original:'Beurre cacahuète',alternative:'10g pâte tahini pour version sésame'},{original:'Cacao',alternative:'Vanille extract pour version vanille PB'}],coach_note:'Le triple combo banane-PB-choco — saveurs jumelles. Texture de glace italienne, 0 sucre ajouté.'},

  {title:'Gâteau Mug Cacahuète',category:'Desserts',meal_type:'snack',goal_tag:'muscle',craving_tag:'sucré',prep_time:3,difficulty:1,total_calories:268,total_protein:18,total_carbs:24,total_fat:10,featured:false,photo_gradient:'linear-gradient(135deg,#1a0800,#A0522D)',membership_required:'cookbook',
    ingredients:[{name:'Flocons d\'avoine mixés',quantity:'30g',calories:114,protein:3.9,carbs:18,fat:2.1},{name:'Œuf entier',quantity:'1 (60g)',calories:70,protein:6,carbs:1,fat:5},{name:'Beurre de cacahuète',quantity:'15g',calories:90,protein:3.75,carbs:3,fat:7.5},{name:'Fromage frais Lactel 0%',quantity:'30g',calories:27,protein:2.6,carbs:1.3,fat:1.1}],
    steps:['Mélanger tous les ingrédients dans un mug.','Bien battre, ajouter 30ml eau si épais.','Micro-ondes 90 secondes max.','Laisser reposer 1 min.','Décorer avec banane tranchée.'],
    substitutions:[{original:'Beurre cacahuète',alternative:'Cacao pour version chocolat'},{original:'Fromage frais',alternative:'Yaourt grec 0%'}],coach_note:'Le mug cake PB — 3 minutes du frigo à la bouche. Pour les soirs où l\'envie de sucré est forte.'},

  {title:'Tarte Citron Meringuée Fit',category:'Desserts',meal_type:'snack',goal_tag:'all',craving_tag:'sucré',prep_time:25,difficulty:3,total_calories:295,total_protein:24,total_carbs:24,total_fat:10,featured:false,photo_gradient:'linear-gradient(135deg,#1a1000,#FFD700)',membership_required:'cookbook',
    ingredients:[{name:'Flocons d\'avoine mixés',quantity:'30g',calories:114,protein:3.9,carbs:18,fat:2.1},{name:'Œuf entier',quantity:'2 (120g)',calories:140,protein:12,carbs:2,fat:10},{name:'Fromage frais Lactel 0%',quantity:'150g',calories:134,protein:12.9,carbs:6.5,fat:5.3},{name:'Citron',quantity:'1 (jus)',calories:15,protein:0.5,carbs:5,fat:0}],
    steps:['Base : avoine + 1 jaune + cannelle. Cuire 10 min four 180°C.','Crème : jaune restant + fromage frais + jus citron + zeste.','Verser sur base, four 12 min.','Meringue : blancs montés en neige ferme.','Étaler sur tarte, four 3 min position grill.'],
    substitutions:[{original:'Citron',alternative:'Orange pour version moins acide'},{original:'Meringue',alternative:'Filet de miel pour version simplifiée'}],coach_note:'La tarte citron de pâtisserie — version fit. La meringue maison sans sucre = challenge accepté.'},

  {title:'Mousse Café Yaourt Grec',category:'Desserts',meal_type:'snack',goal_tag:'fat_loss',craving_tag:'sucré',prep_time:5,difficulty:1,total_calories:185,total_protein:18,total_carbs:14,total_fat:6,featured:false,photo_gradient:'linear-gradient(135deg,#0a0800,#3D2B1F)',membership_required:'cookbook',
    ingredients:[{name:'Fromage frais Lactel 0%',quantity:'200g',calories:178,protein:17.2,carbs:8.6,fat:7},{name:'Café fort',quantity:'30ml',calories:5,protein:0.3,carbs:0.5,fat:0},{name:'Cacao en poudre',quantity:'3g',calories:7,protein:0.3,carbs:1.1,fat:0.2},{name:'Cannelle',quantity:'1g',calories:3,protein:0.1,carbs:0.7,fat:0}],
    steps:['Préparer café espresso fort, laisser refroidir.','Mélanger fromage frais + café + cannelle.','Battre vigoureusement 30 secondes pour aérer.','Verser dans verre, saupoudrer cacao.','Frigo 30 min minimum.'],
    substitutions:[{original:'Café',alternative:'Cacao chaud pour version chocolat'},{original:'Cannelle',alternative:'Vanille pour version douce'}],coach_note:'La mousse café tiramisu sans pâte. 185 kcal pour finir un repas sur une note caféinée et protéinée.'}
];

async function main(){
  console.log(`\n🍳  BATCH 2 — Adding ${RECIPES.length} new recipes\n`);
  let inserted = 0;
  for(let i=0;i<RECIPES.length;i+=10){
    const batch = RECIPES.slice(i,i+10);
    const ins = await q('POST','cookbook_recipes',batch);
    if(!ins.ok){
      console.error(`❌ Batch ${i/10+1}: ${ins.status}`,JSON.stringify(ins.data?.message||ins.data));
    } else {
      const rows = Array.isArray(ins.data)?ins.data:[];
      rows.forEach(r=>console.log(`  ✅ ${r.title}`));
      inserted += rows.length;
    }
  }
  console.log(`\n🎉  Batch 2 done — ${inserted}/${RECIPES.length} recipes added.\n`);
}
main().catch(e=>{console.error(e);process.exit(1);});
