#!/usr/bin/env node
// seed_cookbook_batch_1.mjs — Recipes 41-80
// Run: node seed_cookbook_batch_1.mjs

const SB_URL = 'https://korektlpnwuefsagfuvq.supabase.co';
const SB_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvcmVrdGxwbnd1ZWZzYWdmdXZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYwMjI0NjQsImV4cCI6MjA5MTU5ODQ2NH0.46rZOEMUKoZCyL8eKzob8FDuOoFiA2LHbr2ZoKW-HrM';
const H = {'Content-Type':'application/json','apikey':SB_KEY,'Authorization':`Bearer ${SB_KEY}`,'Prefer':'return=representation'};
const q = async (m,p,b) => { const r = await fetch(`${SB_URL}/rest/v1/${p}`,{method:m,headers:H,body:b?JSON.stringify(b):undefined}); return {ok:r.ok,status:r.status,data:await r.json().catch(()=>null)}; };

const RECIPES = [
  // ── BREAKFASTS 11-25 (15 new) ────────────────────────
  {title:'Avoine Salée Œufs Avocat',category:'Breakfasts',meal_type:'breakfast',goal_tag:'all',craving_tag:'salé',prep_time:10,difficulty:1,total_calories:425,total_protein:24,total_carbs:42,total_fat:18,featured:false,photo_gradient:'linear-gradient(135deg,#1a1a00,#6B8E23)',membership_required:'cookbook',
    ingredients:[{name:'Flocons d\'avoine',quantity:'60g',calories:228,protein:7.8,carbs:36,fat:4.2},{name:'Œufs entiers',quantity:'2 (120g)',calories:140,protein:12,carbs:2,fat:10},{name:'Fromage frais Lactel 0%',quantity:'40g',calories:36,protein:3.4,carbs:1.7,fat:1.4},{name:'Tomates',quantity:'80g',calories:14,protein:0.7,carbs:3.1,fat:0.2},{name:'Huile d\'olive',quantity:'1g',calories:9,protein:0,carbs:0,fat:1}],
    steps:['Cuire l\'avoine à l\'eau salée avec un cube de bouillon — 4 min.','Cuire les œufs au plat avec très peu d\'huile.','Mélanger fromage frais dans l\'avoine hors du feu.','Servir avoine en bol, œufs dessus, tomates fraîches.','Sel, poivre, paprika.'],
    substitutions:[{original:'Œufs au plat',alternative:'2 œufs durs si meal prep'},{original:'Tomates',alternative:'Avocat 50g pour version riche en bons gras'}],coach_note:'Personne ne te dit que l\'avoine peut être salée. Game changer pour ceux qui n\'aiment pas le sucré le matin.'},

  {title:'Œufs Bénédicte Fit',category:'Breakfasts',meal_type:'breakfast',goal_tag:'all',craving_tag:'salé',prep_time:12,difficulty:2,total_calories:410,total_protein:36,total_carbs:30,total_fat:16,featured:false,photo_gradient:'linear-gradient(135deg,#1a0a00,#CD5C5C)',membership_required:'cookbook',
    ingredients:[{name:'Pain ARRUPAN',quantity:'90g',calories:240,protein:8,carbs:44,fat:3},{name:'Œufs entiers',quantity:'2 (120g)',calories:140,protein:12,carbs:2,fat:10},{name:'Escalope de dinde',quantity:'80g',calories:88,protein:17.6,carbs:0,fat:0.8},{name:'Fromage frais Lactel 0%',quantity:'40g',calories:36,protein:3.4,carbs:1.7,fat:1.4}],
    steps:['Pocher les œufs dans l\'eau bouillante vinaigrée 3 min.','Griller la dinde 2 min par côté.','Toaster le pain ARRUPAN.','Hollandaise fit : fromage frais + jaune cru + citron + curcuma.','Empiler : pain, dinde, œuf, sauce.'],
    substitutions:[{original:'Dinde',alternative:'Saumon fumé 60g pour version brunch'},{original:'Œufs pochés',alternative:'Œufs au plat plus simples'}],coach_note:'La hollandaise au fromage frais est ma trouvaille préférée. Goût de beurre, macros de yaourt.'},

  {title:'Bowl Yaourt Granola Maison',category:'Breakfasts',meal_type:'breakfast',goal_tag:'all',craving_tag:'sucré',prep_time:6,difficulty:1,total_calories:445,total_protein:28,total_carbs:58,total_fat:12,featured:false,photo_gradient:'linear-gradient(135deg,#1a1000,#DEB887)',membership_required:'cookbook',
    ingredients:[{name:'Fromage frais Lactel 0%',quantity:'200g',calories:178,protein:17.2,carbs:8.6,fat:7},{name:'Flocons d\'avoine grillés',quantity:'40g',calories:152,protein:5.2,carbs:24,fat:2.8},{name:'Banane',quantity:'100g',calories:89,protein:1,carbs:23,fat:0},{name:'Beurre de cacahuète',quantity:'4g',calories:24,protein:1,carbs:0.8,fat:2}],
    steps:['Griller à sec les flocons d\'avoine à la poêle 3 min — clé de la texture.','Mélanger avec une pincée de cannelle.','Verser le fromage frais dans un bol.','Couvrir de granola maison.','Trancher la banane par-dessus, filet de beurre de cacahuète.'],
    substitutions:[{original:'Banane',alternative:'Pomme râpée 80g pour moins de sucre'},{original:'Avoine grillée',alternative:'Avoine crue pour version express'}],coach_note:'Le secret du granola maison : pas besoin de miel ou huile. Juste griller à sec. Crunch parfait, zéro calorie ajoutée.'},

  {title:'Crêpe Géante Avoine Banane',category:'Breakfasts',meal_type:'breakfast',goal_tag:'muscle',craving_tag:'sucré',prep_time:8,difficulty:1,total_calories:478,total_protein:26,total_carbs:60,total_fat:14,featured:false,photo_gradient:'linear-gradient(135deg,#1a0800,#DEB887)',membership_required:'cookbook',
    ingredients:[{name:'Flocons d\'avoine mixés',quantity:'70g',calories:266,protein:9.1,carbs:42,fat:4.9},{name:'Banane',quantity:'80g',calories:71,protein:0.8,carbs:18.4,fat:0},{name:'Œuf entier',quantity:'1 (60g)',calories:70,protein:6,carbs:1,fat:5},{name:'Fromage frais Lactel 0%',quantity:'70g',calories:62,protein:6,carbs:3,fat:2.5},{name:'Beurre de cacahuète',quantity:'8g',calories:48,protein:2,carbs:1.6,fat:4}],
    steps:['Mixer tous les ingrédients sauf beurre de cacahuète.','Verser dans une grande poêle antiadhésive.','Cuire à feu doux couvert 5 min — texture crêpe géante.','Retourner avec assiette, 2 min de l\'autre côté.','Garnir de beurre de cacahuète et banane fraîche.'],
    substitutions:[{original:'Banane',alternative:'100g compote de pomme'},{original:'Crêpe géante',alternative:'5 petites crêpes plus rapides à cuire'}],coach_note:'Quand t\'as la flemme de faire 5 crêpes — une grosse remplit l\'assiette. Effet bluffant.'},

  {title:'Œufs Brouillés Crémeux Truffés',category:'Breakfasts',meal_type:'breakfast',goal_tag:'all',craving_tag:'salé',prep_time:8,difficulty:2,total_calories:395,total_protein:34,total_carbs:8,total_fat:24,featured:true,photo_gradient:'linear-gradient(135deg,#0a0a00,#2F4F2F)',membership_required:'cookbook',
    ingredients:[{name:'Œufs entiers',quantity:'4 (240g)',calories:280,protein:24,carbs:4,fat:20},{name:'Fromage frais Lactel 0%',quantity:'80g',calories:71,protein:6.9,carbs:3.4,fat:2.8},{name:'Huile d\'olive',quantity:'4g',calories:36,protein:0,carbs:0,fat:4},{name:'Tomates',quantity:'50g',calories:9,protein:0.5,carbs:2,fat:0.1}],
    steps:['Battre les œufs vigoureusement 30 secondes — incorpore l\'air.','Poêle à FEU TRÈS DOUX avec huile.','Verser les œufs, remuer SANS arrêt avec spatule.','Hors du feu, incorporer fromage frais — texture crémeuse.','Servir IMMÉDIATEMENT — ils continuent de cuire.'],
    substitutions:[{original:'Tomates',alternative:'Truffe râpée pour version restaurant'},{original:'Huile d\'olive',alternative:'8g beurre pour version classique +40kcal'}],coach_note:'La règle des œufs brouillés parfaits : feu doux, mouvement constant, jamais cuire à 100%. Hôtels 5 étoiles font exactement ça.'},

  {title:'Toast Avocat Œuf Poché',category:'Breakfasts',meal_type:'breakfast',goal_tag:'all',craving_tag:'salé',prep_time:10,difficulty:2,total_calories:440,total_protein:24,total_carbs:36,total_fat:22,featured:false,photo_gradient:'linear-gradient(135deg,#0a1a00,#556B2F)',membership_required:'cookbook',
    ingredients:[{name:'Pain ARRUPAN',quantity:'90g',calories:240,protein:8,carbs:44,fat:3},{name:'Avocat',quantity:'60g',calories:96,protein:1.2,carbs:5.4,fat:9},{name:'Œuf entier',quantity:'2 (120g)',calories:140,protein:12,carbs:2,fat:10},{name:'Tomates',quantity:'50g',calories:9,protein:0.5,carbs:2,fat:0.1}],
    steps:['Pocher les œufs : eau frémissante + vinaigre, tourbillon, casser œuf dedans, 3 min.','Écraser l\'avocat avec sel, poivre, citron, ail.','Toaster le pain ARRUPAN.','Étaler avocat sur pain, œuf poché dessus.','Sel, poivre, piment d\'Espelette si tu aimes.'],
    substitutions:[{original:'Œuf poché',alternative:'2 œufs au plat plus simples'},{original:'Avocat',alternative:'Fromage frais 60g pour version moins grasse -50kcal'}],coach_note:'Le brunch d\'Instagram à 12€ — fait chez toi en 10 min pour 80 DA. Avocat = bons gras essentiels.'},

  {title:'Smoothie Vert Protéiné',category:'Breakfasts',meal_type:'breakfast',goal_tag:'fat_loss',craving_tag:'frais',prep_time:5,difficulty:1,total_calories:325,total_protein:24,total_carbs:42,total_fat:6,featured:false,photo_gradient:'linear-gradient(135deg,#001a00,#228B22)',membership_required:'cookbook',
    ingredients:[{name:'Fromage frais Lactel 0%',quantity:'200g',calories:178,protein:17.2,carbs:8.6,fat:7},{name:'Banane',quantity:'100g',calories:89,protein:1,carbs:23,fat:0},{name:'Pomme',quantity:'100g',calories:52,protein:0,carbs:14,fat:0},{name:'Épinards',quantity:'50g',calories:11,protein:1.4,carbs:1.8,fat:0.2}],
    steps:['Mettre tous les ingrédients dans le blender.','Ajouter 150ml d\'eau ou lait écrémé.','Mixer 60 secondes à vitesse max.','Servir immédiatement.','Option : ajouter glaçons pour version frappée.'],
    substitutions:[{original:'Épinards',alternative:'Salade verte si pas d\'épinards — goût identique'},{original:'Pomme',alternative:'Ananas pour version tropicale'}],coach_note:'Tu ne goûtes PAS les épinards. Promis. Mais tu ajoutes 50g de légumes verts avant 9h du matin. Win.'},

  {title:'Avoine au Lait Banane Cannelle',category:'Breakfasts',meal_type:'breakfast',goal_tag:'all',craving_tag:'sucré',prep_time:7,difficulty:1,total_calories:380,total_protein:18,total_carbs:62,total_fat:7,featured:false,photo_gradient:'linear-gradient(135deg,#1a1000,#D2B48C)',membership_required:'cookbook',
    ingredients:[{name:'Flocons d\'avoine',quantity:'70g',calories:266,protein:9.1,carbs:42,fat:4.9},{name:'Lait écrémé',quantity:'200ml',calories:70,protein:7,carbs:10,fat:0.2},{name:'Banane',quantity:'80g',calories:71,protein:0.8,carbs:18.4,fat:0},{name:'Cannelle',quantity:'2g',calories:6,protein:0.2,carbs:1.6,fat:0.1}],
    steps:['Mélanger avoine + lait dans casserole.','Cuire à feu moyen 5 min en remuant.','Ajouter banane écrasée à mi-cuisson.','Cannelle généreuse hors du feu.','Servir chaud, option : 5g de miel pour les enfants.'],
    substitutions:[{original:'Lait écrémé',alternative:'200ml eau pour version sans lactose -70kcal'},{original:'Cannelle',alternative:'Cacao en poudre pour version chocolat'}],coach_note:'L\'avoine au lait de ton enfance, sans le sucre. La cannelle remplace 2 cuillères de sucre — essaie tu verras.'},

  {title:'Wrap Petit Déj Œuf Dinde',category:'Breakfasts',meal_type:'breakfast',goal_tag:'all',craving_tag:'salé',prep_time:10,difficulty:1,total_calories:420,total_protein:38,total_carbs:34,total_fat:14,featured:false,photo_gradient:'linear-gradient(135deg,#1a0800,#A52A2A)',membership_required:'cookbook',
    ingredients:[{name:'Pain ARRUPAN',quantity:'90g',calories:240,protein:8,carbs:44,fat:3},{name:'Œufs entiers',quantity:'2 (120g)',calories:140,protein:12,carbs:2,fat:10},{name:'Escalope de dinde',quantity:'80g',calories:88,protein:17.6,carbs:0,fat:0.8},{name:'Fromage frais Lactel 0%',quantity:'40g',calories:36,protein:3.4,carbs:1.7,fat:1.4}],
    steps:['Cuire les œufs brouillés avec dinde émincée dans la même poêle.','Réchauffer le pain ARRUPAN à la poêle sèche pour l\'assouplir.','Étaler fromage frais sur pain.','Garnir avec œufs + dinde + tomates.','Rouler serré comme un wrap.'],
    substitutions:[{original:'Dinde',alternative:'Thon en boîte 80g pour version sans cuisson'},{original:'Pain ARRUPAN',alternative:'Tortilla complète'}],coach_note:'Le wrap du matin avant le boulot. Se mange à une main dans la voiture. Mes clients pressés ne jurent que par ça.'},

  {title:'Cottage Cheese Bowl Sucré',category:'Breakfasts',meal_type:'breakfast',goal_tag:'fat_loss',craving_tag:'sucré',prep_time:3,difficulty:1,total_calories:285,total_protein:24,total_carbs:30,total_fat:6,featured:false,photo_gradient:'linear-gradient(135deg,#1a1010,#FAEBD7)',membership_required:'cookbook',
    ingredients:[{name:'Fromage frais Lactel 0%',quantity:'200g',calories:178,protein:17.2,carbs:8.6,fat:7},{name:'Banane',quantity:'80g',calories:71,protein:0.8,carbs:18.4,fat:0},{name:'Flocons d\'avoine',quantity:'10g',calories:38,protein:1.3,carbs:6,fat:0.7},{name:'Cannelle',quantity:'1g',calories:3,protein:0.1,carbs:0.8,fat:0}],
    steps:['Mettre fromage frais dans un bol.','Couper la banane en rondelles.','Saupoudrer d\'avoine et cannelle.','Optionnel : 5g miel pour les enfants.','3 minutes chrono.'],
    substitutions:[{original:'Banane',alternative:'Pomme + cannelle pour automne'},{original:'Avoine crue',alternative:'Granola maison'}],coach_note:'Le petit déj express. 3 ingrédients, 24g de protéines, 285 calories. Pour les matins où tu n\'as pas le temps.'},

  {title:'Pain Perdu Protéiné',category:'Breakfasts',meal_type:'breakfast',goal_tag:'all',craving_tag:'sucré',prep_time:10,difficulty:1,total_calories:435,total_protein:26,total_carbs:48,total_fat:14,featured:false,photo_gradient:'linear-gradient(135deg,#1a0a00,#D2691E)',membership_required:'cookbook',
    ingredients:[{name:'Pain ARRUPAN',quantity:'90g',calories:240,protein:8,carbs:44,fat:3},{name:'Œufs entiers',quantity:'2 (120g)',calories:140,protein:12,carbs:2,fat:10},{name:'Fromage frais Lactel 0%',quantity:'50g',calories:45,protein:4.3,carbs:2.2,fat:1.8},{name:'Banane',quantity:'30g',calories:27,protein:0.3,carbs:6.9,fat:0},{name:'Cannelle',quantity:'2g',calories:6,protein:0.2,carbs:1.6,fat:0.1}],
    steps:['Battre œufs avec fromage frais, cannelle, banane écrasée.','Tremper chaque tranche de pain 30 secondes dans le mélange.','Cuire dans poêle antiadhésive 2 min par côté.','Servir avec banane fraîche.','Option : filet de miel ou compote sans sucre.'],
    substitutions:[{original:'Banane mélange',alternative:'Vanille extract + cannelle pour pain perdu classique'},{original:'Pain ARRUPAN',alternative:'Pain rassis classique — recette d\'origine'}],coach_note:'Le pain perdu de grand-mère. Aucun sucre ajouté. La banane sucre naturellement le mélange.'},

  {title:'Pizza Petit Déj Œuf',category:'Breakfasts',meal_type:'breakfast',goal_tag:'all',craving_tag:'salé',prep_time:10,difficulty:1,total_calories:415,total_protein:32,total_carbs:36,total_fat:16,featured:false,photo_gradient:'linear-gradient(135deg,#1a0000,#B22222)',membership_required:'cookbook',
    ingredients:[{name:'Pain ARRUPAN',quantity:'90g',calories:240,protein:8,carbs:44,fat:3},{name:'Œufs entiers',quantity:'2 (120g)',calories:140,protein:12,carbs:2,fat:10},{name:'Fromage frais Lactel 0%',quantity:'60g',calories:53,protein:5.2,carbs:2.6,fat:2.1},{name:'Tomates',quantity:'80g',calories:14,protein:0.7,carbs:3.1,fat:0.2},{name:'Escalope de dinde',quantity:'50g',calories:55,protein:11,carbs:0,fat:0.5}],
    steps:['Étaler fromage frais sur pain ARRUPAN comme base de pizza.','Disposer tomates en rondelles, dinde émincée.','Casser un œuf au centre.','Four 200°C 8-10 min jusqu\'à œuf cuit.','Origan, sel, poivre.'],
    substitutions:[{original:'Dinde',alternative:'Champignons pour version végé'},{original:'Œuf entier',alternative:'2 blancs d\'œuf pour version plus light'}],coach_note:'La pizza du matin — oui ça existe. La sauce fromage frais + œuf cuit au four = combinaison parfaite.'},

  {title:'Riz au Lait Protéiné',category:'Breakfasts',meal_type:'breakfast',goal_tag:'muscle',craving_tag:'sucré',prep_time:15,difficulty:1,total_calories:495,total_protein:24,total_carbs:78,total_fat:8,featured:false,photo_gradient:'linear-gradient(135deg,#1a1000,#FAEBD7)',membership_required:'cookbook',
    ingredients:[{name:'Riz blanc',quantity:'60g cru',calories:216,protein:4.2,carbs:46.8,fat:0.6},{name:'Lait écrémé',quantity:'300ml',calories:105,protein:10.5,carbs:15,fat:0.3},{name:'Fromage frais Lactel 0%',quantity:'100g',calories:89,protein:8.6,carbs:4.3,fat:3.5},{name:'Banane',quantity:'80g',calories:71,protein:0.8,carbs:18.4,fat:0},{name:'Cannelle',quantity:'2g',calories:6,protein:0.2,carbs:1.6,fat:0.1}],
    steps:['Cuire le riz dans le lait à feu doux 15 min en remuant.','Quand le riz est tendre, retirer du feu.','Incorporer fromage frais et banane écrasée.','Cannelle généreuse.','Servir tiède ou froid.'],
    substitutions:[{original:'Banane',alternative:'10g miel pour version classique'},{original:'Riz blanc',alternative:'Riz complet pour plus de fibres'}],coach_note:'Le riz au lait de ta grand-mère — version musclée. Parfait post-entraînement, glucides + protéines parfaitement dosés.'},

  {title:'Œufs Cocotte Tomates',category:'Breakfasts',meal_type:'breakfast',goal_tag:'fat_loss',craving_tag:'salé',prep_time:12,difficulty:2,total_calories:325,total_protein:30,total_carbs:14,total_fat:18,featured:false,photo_gradient:'linear-gradient(135deg,#1a0000,#8B0000)',membership_required:'cookbook',
    ingredients:[{name:'Œufs entiers',quantity:'3 (180g)',calories:210,protein:18,carbs:3,fat:15},{name:'Tomates',quantity:'150g',calories:27,protein:1.4,carbs:5.9,fat:0.3},{name:'Fromage frais Lactel 0%',quantity:'60g',calories:53,protein:5.2,carbs:2.6,fat:2.1},{name:'Huile d\'olive',quantity:'5g',calories:45,protein:0,carbs:0,fat:5}],
    steps:['Cuire les tomates concassées 5 min avec huile, ail, herbes.','Verser dans ramequins.','Casser les œufs sur les tomates.','Couvrir de fromage frais.','Four 180°C 8 min — jaune coulant.'],
    substitutions:[{original:'Tomates concassées',alternative:'Épinards + champignons pour variation'},{original:'3 œufs',alternative:'2 œufs si moins faim'}],coach_note:'Le brunch français à la maison. Présentation digne d\'un restaurant.'},

  {title:'Banana Bread Protéiné (1 part)',category:'Breakfasts',meal_type:'breakfast',goal_tag:'muscle',craving_tag:'sucré',prep_time:8,difficulty:1,total_calories:380,total_protein:22,total_carbs:48,total_fat:10,featured:false,photo_gradient:'linear-gradient(135deg,#1a0800,#A0522D)',membership_required:'cookbook',
    ingredients:[{name:'Flocons d\'avoine mixés',quantity:'50g',calories:190,protein:6.5,carbs:30,fat:3.5},{name:'Banane',quantity:'100g',calories:89,protein:1,carbs:23,fat:0},{name:'Fromage frais Lactel 0%',quantity:'80g',calories:71,protein:6.9,carbs:3.4,fat:2.8},{name:'Œuf entier',quantity:'1 (60g)',calories:70,protein:6,carbs:1,fat:5},{name:'Cannelle',quantity:'2g',calories:6,protein:0.2,carbs:1.6,fat:0.1}],
    steps:['Mixer tous les ingrédients ensemble en pâte lisse.','Verser dans petit moule individuel.','Four 175°C 25-30 minutes.','Vérifier cuisson avec couteau — sec = prêt.','Laisser refroidir 5 min avant démouler.'],
    substitutions:[{original:'Moule individuel',alternative:'4x la recette pour un grand banana bread (4 portions)'},{original:'Cannelle',alternative:'Cacao 5g pour version chocolat'}],coach_note:'Le banana bread du dimanche. Tu peux le tripler pour avoir 3 jours de petits déj prêts.'},

  // ── FAST FOOD REMAKES 21-50 (15 new) ─────────────────
  {title:'McChicken Maison Fit',category:'Fast Food Remakes',meal_type:'lunch',goal_tag:'all',craving_tag:'fast food',prep_time:15,difficulty:2,total_calories:455,total_protein:42,total_carbs:42,total_fat:13,featured:true,photo_gradient:'linear-gradient(135deg,#1a1200,#DAA520)',membership_required:'cookbook',
    ingredients:[{name:'Escalope de poulet',quantity:'150g',calories:180,protein:33,carbs:0,fat:3},{name:'Flocons d\'avoine mixés',quantity:'30g',calories:114,protein:3.9,carbs:18,fat:2.1},{name:'Pain ARRUPAN',quantity:'90g',calories:240,protein:8,carbs:44,fat:3},{name:'Œuf entier',quantity:'1 (60g)',calories:70,protein:6,carbs:1,fat:5},{name:'Fromage frais Lactel 0%',quantity:'30g',calories:27,protein:2.6,carbs:1.3,fat:1.1}],
    steps:['Aplatir le poulet à 1cm d\'épaisseur.','Panure : avoine + paprika + sel — tremper œuf puis panure.','Cuire à la poêle avec spray d\'huile, 3 min par côté.','Sauce : fromage frais + moutarde + mayo light + paprika.','Assembler dans pain ARRUPAN avec salade.'],
    substitutions:[{original:'Avoine panure',alternative:'Chapelure complète'},{original:'Poêle',alternative:'Airfryer 190°C 10 min pour effet panné parfait'}],coach_note:'Le McChicken qu\'on aime tous — mais 350kcal de moins que l\'original. La sauce fait toute la différence.'},

  {title:'Cheeseburger Drive Fit',category:'Fast Food Remakes',meal_type:'lunch',goal_tag:'muscle',craving_tag:'fast food',prep_time:12,difficulty:1,total_calories:530,total_protein:44,total_carbs:40,total_fat:22,featured:false,photo_gradient:'linear-gradient(135deg,#1a0000,#FF4500)',membership_required:'cookbook',
    ingredients:[{name:'Steak haché',quantity:'150g',calories:375,protein:39,carbs:0,fat:25.5},{name:'Pain ARRUPAN',quantity:'90g',calories:240,protein:8,carbs:44,fat:3},{name:'Fromage frais Lactel 0%',quantity:'50g',calories:45,protein:4.3,carbs:2.2,fat:1.8},{name:'Tomates',quantity:'50g',calories:9,protein:0.5,carbs:2,fat:0.1}],
    steps:['Former steak fin de 150g, sel et poivre.','Poêle ULTRA chaude, 2 min par côté pour saignant.','Étaler fromage frais épais sur pain — effet "fromage fondu".','Empiler steak, tomate, ketchup maison, cornichons.','Toaster légèrement le pain avant pour effet crustillant.'],
    substitutions:[{original:'Steak haché',alternative:'130g poulet haché pour version -100kcal'},{original:'Fromage frais',alternative:'1 tranche emmental allégé pour fromage réel +30kcal'}],coach_note:'Le cheeseburger du drive — sans la grosse pile de gras. Truc de pro : fromage frais TIÈDE = effet fromage fondu.'},

  {title:'Wrap Fajitas Poulet',category:'Fast Food Remakes',meal_type:'lunch',goal_tag:'all',craving_tag:'fast food',prep_time:12,difficulty:2,total_calories:510,total_protein:44,total_carbs:48,total_fat:13,featured:false,photo_gradient:'linear-gradient(135deg,#1a0800,#FF6347)',membership_required:'cookbook',
    ingredients:[{name:'Escalope de poulet',quantity:'180g',calories:216,protein:39.6,carbs:0,fat:3.6},{name:'Pain ARRUPAN',quantity:'90g',calories:240,protein:8,carbs:44,fat:3},{name:'Fromage frais Lactel 0%',quantity:'50g',calories:45,protein:4.3,carbs:2.2,fat:1.8},{name:'Poivrons',quantity:'100g',calories:23,protein:0.8,carbs:5.3,fat:0.3},{name:'Huile d\'olive',quantity:'4g',calories:36,protein:0,carbs:0,fat:4}],
    steps:['Couper poulet en lamelles, mariner épices fajitas (paprika, cumin, ail, lime).','Faire sauter à feu vif avec poivrons en lamelles.','Sauce : fromage frais + coriandre + lime + sel.','Réchauffer pain ARRUPAN, étaler sauce.','Garnir poulet + poivrons, rouler.'],
    substitutions:[{original:'Poulet',alternative:'Steak haché émincé 150g pour version texane'},{original:'Poivrons',alternative:'Champignons pour version automne'}],coach_note:'Le wrap fajitas de Tex-Mex restaurant. Tout est dans les épices et la cuisson FORTE pour les marques de grill.'},

  {title:'Subway Italien Fit',category:'Fast Food Remakes',meal_type:'lunch',goal_tag:'fat_loss',craving_tag:'fast food',prep_time:8,difficulty:1,total_calories:425,total_protein:42,total_carbs:38,total_fat:12,featured:false,photo_gradient:'linear-gradient(135deg,#001a00,#228B22)',membership_required:'cookbook',
    ingredients:[{name:'Pain ARRUPAN',quantity:'90g',calories:240,protein:8,carbs:44,fat:3},{name:'Escalope de dinde',quantity:'120g',calories:132,protein:26.4,carbs:0,fat:1.2},{name:'Fromage frais Lactel 0%',quantity:'40g',calories:36,protein:3.4,carbs:1.7,fat:1.4},{name:'Tomates',quantity:'80g',calories:14,protein:0.7,carbs:3.1,fat:0.2},{name:'Huile d\'olive',quantity:'3g',calories:27,protein:0,carbs:0,fat:3}],
    steps:['Trancher le pain ARRUPAN en deux dans la longueur.','Étaler fromage frais sur les deux côtés.','Disposer dinde, tomates, salade.','Filet d\'huile d\'olive, origan italien.','Sel et poivre.'],
    substitutions:[{original:'Dinde',alternative:'Thon en boîte 120g pour version méditerranéenne'},{original:'Origan',alternative:'Pesto maison pour version pesto'}],coach_note:'Le sub italien classique. Le secret : pain assoupli légèrement à la poêle sèche avant assemblage.'},

  {title:'Kebab Poulet Fit',category:'Fast Food Remakes',meal_type:'lunch',goal_tag:'all',craving_tag:'fast food',prep_time:15,difficulty:2,total_calories:485,total_protein:46,total_carbs:42,total_fat:14,featured:true,photo_gradient:'linear-gradient(135deg,#1a0a00,#D2691E)',membership_required:'cookbook',
    ingredients:[{name:'Escalope de poulet',quantity:'180g',calories:216,protein:39.6,carbs:0,fat:3.6},{name:'Pain ARRUPAN',quantity:'90g',calories:240,protein:8,carbs:44,fat:3},{name:'Fromage frais Lactel 0%',quantity:'60g',calories:53,protein:5.2,carbs:2.6,fat:2.1},{name:'Tomates',quantity:'80g',calories:14,protein:0.7,carbs:3.1,fat:0.2}],
    steps:['Couper poulet en lamelles, mariner cumin + paprika + ail + huile.','Cuire à la poêle TRÈS chaude pour effet rôtissoire.','Sauce blanche : fromage frais + ail + citron + persil.','Garnir pain ARRUPAN, salade, tomates.','Sauce blanche généreuse.'],
    substitutions:[{original:'Poulet',alternative:'Steak haché émincé pour version bœuf'},{original:'Sauce blanche',alternative:'Sauce harissa + yaourt grec pour version épicée'}],coach_note:'Le kebab du quartier — fait chez toi avec exactement les bonnes épices. 600kcal de moins que l\'original.'},

  {title:'Pizza 4 Fromages Light',category:'Fast Food Remakes',meal_type:'dinner',goal_tag:'all',craving_tag:'fast food',prep_time:12,difficulty:1,total_calories:478,total_protein:38,total_carbs:42,total_fat:18,featured:false,photo_gradient:'linear-gradient(135deg,#1a1000,#DAA520)',membership_required:'cookbook',
    ingredients:[{name:'Pain ARRUPAN',quantity:'90g',calories:240,protein:8,carbs:44,fat:3},{name:'Fromage frais Lactel 0%',quantity:'120g',calories:107,protein:10.3,carbs:5.2,fat:4.2},{name:'Œufs entiers',quantity:'2 (120g)',calories:140,protein:12,carbs:2,fat:10},{name:'Tomates',quantity:'80g',calories:14,protein:0.7,carbs:3.1,fat:0.2}],
    steps:['Étaler fromage frais sur pain ARRUPAN.','Casser les œufs sur le dessus — bien étaler.','Tomates en rondelles fines.','Four 200°C 10 min.','Origan, basilic, poivre noir.'],
    substitutions:[{original:'Œufs',alternative:'80g thon pour version pêcheur'},{original:'Tomates',alternative:'Olives noires pour version italienne'}],coach_note:'La pizza "4 fromages" n\'a qu\'un fromage — mais le résultat trompe le palais. Les œufs cuits dessus = effet jaune comme mozzarella.'},

  {title:'Hot Dog NY Fit',category:'Fast Food Remakes',meal_type:'lunch',goal_tag:'fat_loss',craving_tag:'fast food',prep_time:8,difficulty:1,total_calories:368,total_protein:36,total_carbs:32,total_fat:12,featured:false,photo_gradient:'linear-gradient(135deg,#1a0000,#DC143C)',membership_required:'cookbook',
    ingredients:[{name:'Escalope de dinde',quantity:'140g',calories:154,protein:30.8,carbs:0,fat:1.4},{name:'Pain ARRUPAN',quantity:'90g',calories:240,protein:8,carbs:44,fat:3},{name:'Fromage frais Lactel 0%',quantity:'40g',calories:36,protein:3.4,carbs:1.7,fat:1.4},{name:'Tomates',quantity:'30g',calories:5,protein:0.3,carbs:1.2,fat:0.1}],
    steps:['Façonner la dinde en boudin allongé style saucisse.','Cuire à la poêle 4 min en roulant pour cuisson uniforme.','Toaster pain ARRUPAN.','Sauce : fromage frais + moutarde + ketchup maison.','Ajouter cornichons (optionnel).'],
    substitutions:[{original:'Dinde boudin',alternative:'Vraies saucisses dinde 0% MG si disponibles'},{original:'Ketchup maison',alternative:'Coulis tomates + paprika + ail'}],coach_note:'Le hot dog de Times Square. La dinde façonnée trompe complètement le cerveau — texture identique à une saucisse industrielle.'},

  {title:'Sandwich Poulet Bacon',category:'Fast Food Remakes',meal_type:'lunch',goal_tag:'muscle',craving_tag:'fast food',prep_time:12,difficulty:2,total_calories:545,total_protein:54,total_carbs:36,total_fat:18,featured:false,photo_gradient:'linear-gradient(135deg,#1a0800,#8B4513)',membership_required:'cookbook',
    ingredients:[{name:'Escalope de poulet',quantity:'180g',calories:216,protein:39.6,carbs:0,fat:3.6},{name:'Pain ARRUPAN',quantity:'90g',calories:240,protein:8,carbs:44,fat:3},{name:'Escalope de dinde fumée',quantity:'40g',calories:44,protein:8.8,carbs:0,fat:0.4},{name:'Fromage frais Lactel 0%',quantity:'50g',calories:45,protein:4.3,carbs:2.2,fat:1.8}],
    steps:['Griller le poulet avec paprika fumé, sel.','Cuire la dinde fumée à la poêle (remplace le bacon).','Toaster le pain ARRUPAN.','Sauce : fromage frais + moutarde + ail.','Empiler : pain, sauce, poulet, dinde fumée, tomate, pain.'],
    substitutions:[{original:'Dinde fumée',alternative:'Vrai bacon 30g pour version classique +80kcal'},{original:'Sauce',alternative:'Mayo light 20g pour sauce classique'}],coach_note:'Le combo poulet-bacon — version fit. La dinde fumée a 75% moins de gras que le bacon mais le même goût fumé.'},

  {title:'Pizza Pepperoni Express',category:'Fast Food Remakes',meal_type:'dinner',goal_tag:'all',craving_tag:'fast food',prep_time:10,difficulty:1,total_calories:445,total_protein:38,total_carbs:36,total_fat:16,featured:false,photo_gradient:'linear-gradient(135deg,#1a0000,#B22222)',membership_required:'cookbook',
    ingredients:[{name:'Pain ARRUPAN',quantity:'90g',calories:240,protein:8,carbs:44,fat:3},{name:'Escalope de dinde épicée',quantity:'80g',calories:88,protein:17.6,carbs:0,fat:0.8},{name:'Fromage frais Lactel 0%',quantity:'80g',calories:71,protein:6.9,carbs:3.4,fat:2.8},{name:'Tomates',quantity:'80g',calories:14,protein:0.7,carbs:3.1,fat:0.2},{name:'Huile d\'olive',quantity:'4g',calories:36,protein:0,carbs:0,fat:4}],
    steps:['Étaler fromage frais sur pain ARRUPAN.','Disposer tomates fines en rondelles.','Émincer dinde épicée (paprika + chili + ail) en lamelles fines comme pepperoni.','Four 200°C 10 minutes.','Origan généreux + huile d\'olive avant service.'],
    substitutions:[{original:'Dinde épicée',alternative:'Vrai pepperoni 30g pour version originale +100kcal'},{original:'Pain ARRUPAN',alternative:'Pâte à pizza maison fine'}],coach_note:'Le pepperoni dinde épicée bluffe tout le monde. Texture et goût épicé du pepperoni, sans la graisse.'},

  {title:'Burrito Bowl Mexicain',category:'Fast Food Remakes',meal_type:'lunch',goal_tag:'all',craving_tag:'fast food',prep_time:15,difficulty:2,total_calories:565,total_protein:48,total_carbs:62,total_fat:12,featured:true,photo_gradient:'linear-gradient(135deg,#1a0a00,#FF8C00)',membership_required:'cookbook',
    ingredients:[{name:'Escalope de poulet',quantity:'180g',calories:216,protein:39.6,carbs:0,fat:3.6},{name:'Riz blanc',quantity:'70g cru',calories:252,protein:4.9,carbs:54.6,fat:0.7},{name:'Tomates',quantity:'80g',calories:14,protein:0.7,carbs:3.1,fat:0.2},{name:'Fromage frais Lactel 0%',quantity:'60g',calories:53,protein:5.2,carbs:2.6,fat:2.1},{name:'Huile d\'olive',quantity:'4g',calories:36,protein:0,carbs:0,fat:4}],
    steps:['Cuire le riz blanc avec un peu de coriandre fraîche et lime.','Mariner poulet : cumin + paprika + lime + ail.','Sauter à feu vif.','Préparer pico de gallo : tomates + oignon + coriandre + lime.','Bowl : riz, poulet, pico, sauce fromage frais + lime.'],
    substitutions:[{original:'Poulet',alternative:'Steak haché émincé pour version bœuf'},{original:'Sauce',alternative:'Guacamole 40g pour version riche en bons gras'}],coach_note:'Le Chipotle bowl à la maison. 600 calories de moins que l\'original. Les portions raisonnables font toute la différence.'},

  {title:'Lasagnes Light Pain ARRUPAN',category:'Fast Food Remakes',meal_type:'dinner',goal_tag:'all',craving_tag:'chaud',prep_time:20,difficulty:3,total_calories:495,total_protein:46,total_carbs:38,total_fat:18,featured:false,photo_gradient:'linear-gradient(135deg,#1a0000,#8B0000)',membership_required:'cookbook',
    ingredients:[{name:'Steak haché',quantity:'120g',calories:300,protein:31.2,carbs:0,fat:20.4},{name:'Pain ARRUPAN',quantity:'70g',calories:187,protein:6.2,carbs:34.2,fat:2.3},{name:'Fromage frais Lactel 0%',quantity:'100g',calories:89,protein:8.6,carbs:4.3,fat:3.5},{name:'Tomates',quantity:'150g',calories:27,protein:1.4,carbs:5.9,fat:0.3}],
    steps:['Cuire steak haché émietté avec tomates concassées 10 min.','Trancher pain ARRUPAN finement pour remplacer feuilles de lasagne.','Béchamel light : fromage frais + lait + sel + muscade.','Alterner : sauce viande, pain, béchamel, sauce viande, pain, béchamel.','Four 200°C 15 minutes.'],
    substitutions:[{original:'Steak haché',alternative:'Dinde hachée pour version -150kcal'},{original:'Pain ARRUPAN feuilles',alternative:'Feuilles de courgette pour version sans glucides'}],coach_note:'Les lasagnes du dimanche, version semaine. Le pain ARRUPAN absorbe parfaitement les sauces comme les vraies feuilles.'},

  {title:'Quesadilla Poulet Fromage',category:'Fast Food Remakes',meal_type:'lunch',goal_tag:'all',craving_tag:'fast food',prep_time:10,difficulty:1,total_calories:465,total_protein:44,total_carbs:36,total_fat:15,featured:false,photo_gradient:'linear-gradient(135deg,#1a1000,#D2691E)',membership_required:'cookbook',
    ingredients:[{name:'Escalope de poulet',quantity:'150g',calories:180,protein:33,carbs:0,fat:3},{name:'Pain ARRUPAN',quantity:'90g',calories:240,protein:8,carbs:44,fat:3},{name:'Fromage frais Lactel 0%',quantity:'80g',calories:71,protein:6.9,carbs:3.4,fat:2.8},{name:'Tomates',quantity:'50g',calories:9,protein:0.5,carbs:2,fat:0.1}],
    steps:['Cuire poulet émincé avec épices mexicaines.','Étaler fromage frais sur pain ARRUPAN.','Garnir avec poulet + tomates concassées.','Plier en deux, cuire à la poêle SANS huile, presser légèrement.','2 min par côté pour effet croustillant.'],
    substitutions:[{original:'Pain ARRUPAN',alternative:'Tortilla complète'},{original:'Poulet',alternative:'Haricots noirs + tomates pour version végé'}],coach_note:'La quesadilla en 10 min. Truc magique : presser pendant cuisson pour effet panini.'},

  {title:'Bagel Saumon Avocat',category:'Fast Food Remakes',meal_type:'lunch',goal_tag:'all',craving_tag:'fast food',prep_time:8,difficulty:1,total_calories:498,total_protein:32,total_carbs:42,total_fat:22,featured:false,photo_gradient:'linear-gradient(135deg,#1a0a00,#FA8072)',membership_required:'cookbook',
    ingredients:[{name:'Pain ARRUPAN',quantity:'90g',calories:240,protein:8,carbs:44,fat:3},{name:'Saumon fumé',quantity:'80g',calories:116,protein:18.4,carbs:0,fat:4.8},{name:'Fromage frais Lactel 0%',quantity:'80g',calories:71,protein:6.9,carbs:3.4,fat:2.8},{name:'Avocat',quantity:'40g',calories:64,protein:0.8,carbs:3.6,fat:6},{name:'Tomates',quantity:'30g',calories:5,protein:0.3,carbs:1.2,fat:0.1}],
    steps:['Toaster légèrement le pain ARRUPAN.','Étaler fromage frais généreusement.','Disposer avocat tranché.','Recouvrir de saumon fumé.','Tomates et poivre noir sur le dessus.'],
    substitutions:[{original:'Saumon fumé',alternative:'Thon naturel 100g pour version moins chère'},{original:'Avocat',alternative:'Concombre pour version moins grasse -50kcal'}],coach_note:'Le brunch newyorkais. Saumon fumé = oméga-3 gold. Vaut bien les 5€ d\'un bagel store.'},

  {title:'Calzone Poulet Champignons',category:'Fast Food Remakes',meal_type:'dinner',goal_tag:'all',craving_tag:'chaud',prep_time:18,difficulty:2,total_calories:485,total_protein:44,total_carbs:46,total_fat:13,featured:false,photo_gradient:'linear-gradient(135deg,#1a1000,#DAA520)',membership_required:'cookbook',
    ingredients:[{name:'Pain ARRUPAN',quantity:'90g',calories:240,protein:8,carbs:44,fat:3},{name:'Escalope de poulet',quantity:'150g',calories:180,protein:33,carbs:0,fat:3},{name:'Fromage frais Lactel 0%',quantity:'80g',calories:71,protein:6.9,carbs:3.4,fat:2.8},{name:'Champignons',quantity:'80g',calories:18,protein:2.5,carbs:2.6,fat:0.2},{name:'Tomates',quantity:'40g',calories:7,protein:0.4,carbs:1.6,fat:0.1}],
    steps:['Cuire poulet en dés avec champignons à feu vif.','Étaler pain ARRUPAN en grand format.','Garnir une moitié : fromage frais, poulet, champignons, tomates.','Replier en demi-lune, sceller les bords.','Four 200°C 12 minutes.'],
    substitutions:[{original:'Champignons',alternative:'Épinards pour version Florentine'},{original:'Poulet',alternative:'Thon 150g pour version pêcheur'}],coach_note:'Le calzone qu\'on commande à 25€ chez Pizza Hut. Fait chez toi pour 400 DA d\'ingrédients.'},

  {title:'Sloppy Joe Fit',category:'Fast Food Remakes',meal_type:'dinner',goal_tag:'muscle',craving_tag:'fast food',prep_time:15,difficulty:1,total_calories:525,total_protein:42,total_carbs:42,total_fat:18,featured:false,photo_gradient:'linear-gradient(135deg,#1a0000,#B22222)',membership_required:'cookbook',
    ingredients:[{name:'Steak haché',quantity:'150g',calories:375,protein:39,carbs:0,fat:25.5},{name:'Pain ARRUPAN',quantity:'90g',calories:240,protein:8,carbs:44,fat:3},{name:'Tomates',quantity:'100g',calories:18,protein:0.9,carbs:3.9,fat:0.2},{name:'Fromage frais Lactel 0%',quantity:'40g',calories:36,protein:3.4,carbs:1.7,fat:1.4}],
    steps:['Cuire steak haché émietté à feu vif.','Ajouter tomates concassées, ail, oignon, paprika, sauce Worcestershire.','Mijoter 8 min jusqu\'à sauce épaisse.','Toaster pain ARRUPAN.','Servir viande sloppy avec sauce fromage frais à côté.'],
    substitutions:[{original:'Steak haché',alternative:'Dinde hachée pour version -100kcal'},{original:'Pain ARRUPAN',alternative:'Sur lit de riz pour version sans pain'}],coach_note:'Le sloppy joe américain — comfort food par excellence. Riche, savoureux, et étonnamment bien équilibré en macros.'}
];

async function main(){
  console.log(`\n🍳  BATCH 1 — Adding ${RECIPES.length} new recipes\n`);
  let inserted = 0;
  for(let i=0;i<RECIPES.length;i+=10){
    const batch = RECIPES.slice(i,i+10);
    const ins = await q('POST','cookbook_recipes',batch);
    if(!ins.ok){
      console.error(`❌ Batch ${i/10+1}: ${ins.status}`,JSON.stringify(ins.data?.message||ins.data));
    } else {
      const rows = Array.isArray(ins.data)?ins.data:[];
      rows.forEach(r=>console.log(`  ✅ ${r.title}`));
      inserted += rows.length;
    }
  }
  console.log(`\n🎉  Batch 1 done — ${inserted}/${RECIPES.length} recipes added.\n`);
}
main().catch(e=>{console.error(e);process.exit(1);});
