// seed_cookbook_v2_indian.mjs
// Cookbook v2 — Batch 5: Indian cuisine (25 recipes)
// Run with: node seed_cookbook_v2_indian.mjs

import { createClient } from '@supabase/supabase-js'

const SUPABASE_URL = 'https://korektlpnwuefsagfuvq.supabase.co'
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || 'PASTE_SERVICE_ROLE_HERE'

const sb = createClient(SUPABASE_URL, SUPABASE_KEY)

const recipes = [
  {
    title: 'Poulet Tikka Masala',
    category: 'main_meals',
    cuisine: 'indian',
    meal_type: 'dinner',
    goal_tag: 'bulk',
    craving_tag: 'comfort',
    prep_time: 45,
    difficulty: 2,
    total_calories: 620,
    total_protein: 48,
    total_carbs: 38,
    total_fat: 32,
    ingredients: [
      { name: 'Blanc de poulet', qty: '300g' },
      { name: 'Yaourt nature', qty: '4 c.à.s' },
      { name: 'Ail', qty: '4 gousses' },
      { name: 'Gingembre frais', qty: '1 c.à.s' },
      { name: 'Garam masala (ou ras el hanout)', qty: '2 c.à.s' },
      { name: 'Paprika', qty: '1 c.à.s' },
      { name: 'Cumin', qty: '1 c.à.c' },
      { name: 'Coriandre en poudre', qty: '1 c.à.c' },
      { name: 'Tomates concassées', qty: '400g' },
      { name: 'Crème liquide', qty: '150ml' },
      { name: 'Oignon', qty: '1' },
      { name: 'Citron', qty: '½' },
      { name: 'Coriandre fraîche', qty: '2 c.à.s' },
      { name: 'Riz basmati cuit', qty: '150g' }
    ],
    steps: [
      'Marine le poulet en cubes avec yaourt, moitié ail-gingembre, paprika, jus de citron 30 min.',
      'Fais cuire le poulet à la poêle 6 min jusqu\'à doré. Réserve.',
      'Dans la même poêle, fais revenir oignon haché.',
      'Ajoute reste ail-gingembre, garam masala, cumin, coriandre poudre. Fais griller 1 min.',
      'Ajoute tomates, mijote 10 min.',
      'Verse la crème, remue. Remets le poulet, mijote 8 min.',
      'Coriandre fraîche, sers avec riz basmati.'
    ],
    substitutions: [
      { from: 'Garam masala', to: 'Ras el hanout (mélange algérien)' }
    ],
    coach_note: 'Le plat indien le plus aimé au monde. 48g de protéines, sauce crémeuse onctueuse.',
    photo_url: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&q=80',
    photo_gradient: 'linear-gradient(135deg,#bb3e03,#fcbf49)',
    membership_required: 'cookbook',
    featured: true
  },
  {
    title: 'Butter Chicken',
    category: 'main_meals',
    cuisine: 'indian',
    meal_type: 'dinner',
    goal_tag: 'bulk',
    craving_tag: 'comfort',
    prep_time: 40,
    difficulty: 2,
    total_calories: 680,
    total_protein: 46,
    total_carbs: 32,
    total_fat: 40,
    ingredients: [
      { name: 'Cuisses de poulet désossées', qty: '300g' },
      { name: 'Yaourt nature', qty: '4 c.à.s' },
      { name: 'Beurre', qty: '40g' },
      { name: 'Crème liquide', qty: '150ml' },
      { name: 'Tomates concassées', qty: '300g' },
      { name: 'Ail', qty: '4 gousses' },
      { name: 'Gingembre', qty: '1 c.à.s' },
      { name: 'Garam masala', qty: '1 c.à.s' },
      { name: 'Cumin', qty: '1 c.à.c' },
      { name: 'Paprika doux', qty: '2 c.à.c' },
      { name: 'Miel', qty: '1 c.à.s' },
      { name: 'Coriandre fraîche', qty: '2 c.à.s' }
    ],
    steps: [
      'Marine le poulet en gros morceaux avec yaourt, ail-gingembre, paprika, garam masala 1h.',
      'Fais griller au four 15 min à 220°C.',
      'Dans une casserole, fais fondre le beurre. Ajoute tomates, mijote 15 min.',
      'Mixe pour avoir une sauce lisse.',
      'Remets sur le feu, ajoute crème, miel, cumin.',
      'Ajoute le poulet grillé. Mijote 10 min.',
      'Coriandre fraîche, sers avec riz ou naan.'
    ],
    substitutions: [
      { from: 'Cuisses', to: 'Blancs de poulet (moins savoureux)' }
    ],
    coach_note: 'Plus crémeux et plus doux que le tikka masala. C\'est le préféré des enfants.',
    photo_url: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=800&q=80',
    photo_gradient: 'linear-gradient(135deg,#fcbf49,#bb3e03)',
    membership_required: 'cookbook',
    featured: true
  },
  {
    title: 'Dal Lentilles Corail',
    category: 'main_meals',
    cuisine: 'indian',
    meal_type: 'lunch',
    goal_tag: 'cut',
    craving_tag: 'comfort',
    prep_time: 35,
    difficulty: 1,
    total_calories: 340,
    total_protein: 18,
    total_carbs: 52,
    total_fat: 8,
    ingredients: [
      { name: 'Lentilles corail (ou jaunes)', qty: '200g' },
      { name: 'Oignon', qty: '1' },
      { name: 'Ail', qty: '3 gousses' },
      { name: 'Gingembre', qty: '1 c.à.s' },
      { name: 'Tomate', qty: '2' },
      { name: 'Curcuma', qty: '1 c.à.c' },
      { name: 'Cumin', qty: '1 c.à.c' },
      { name: 'Coriandre en poudre', qty: '1 c.à.c' },
      { name: 'Garam masala', qty: '1 c.à.c' },
      { name: 'Beurre ou huile', qty: '2 c.à.s' },
      { name: 'Eau ou bouillon', qty: '700ml' },
      { name: 'Coriandre fraîche', qty: '2 c.à.s' },
      { name: 'Citron', qty: '½' }
    ],
    steps: [
      'Rince les lentilles, mets-les dans une casserole avec eau, curcuma, sel. Cuis 20 min.',
      'Dans une poêle, fais chauffer beurre. Ajoute cumin, fais griller 30 sec.',
      'Ajoute oignon haché, fais dorer 5 min.',
      'Ajoute ail, gingembre, tomates, coriandre poudre, garam masala. Mijote 5 min.',
      'Verse ce mélange dans les lentilles cuites.',
      'Mijote 5 min, ajuste avec eau si trop épais.',
      'Coriandre fraîche, jus de citron. Sers avec riz.'
    ],
    substitutions: [
      { from: 'Lentilles corail', to: 'Lentilles vertes (cuisson 35 min)' }
    ],
    coach_note: 'Le dal c\'est mon plat indien préféré. 18g de protéines végétales, 340 kcal — top en cut.',
    photo_url: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&q=80',
    photo_gradient: 'linear-gradient(135deg,#fcbf49,#bb3e03)',
    membership_required: 'cookbook',
    featured: true
  },
  {
    title: 'Biryani au Poulet',
    category: 'main_meals',
    cuisine: 'indian',
    meal_type: 'dinner',
    goal_tag: 'bulk',
    craving_tag: 'comfort',
    prep_time: 75,
    difficulty: 3,
    total_calories: 680,
    total_protein: 42,
    total_carbs: 78,
    total_fat: 22,
    ingredients: [
      { name: 'Riz basmati', qty: '200g' },
      { name: 'Cuisses de poulet', qty: '300g' },
      { name: 'Yaourt nature', qty: '4 c.à.s' },
      { name: 'Oignons', qty: '2' },
      { name: 'Ail', qty: '4 gousses' },
      { name: 'Gingembre', qty: '1 c.à.s' },
      { name: 'Garam masala', qty: '1 c.à.s' },
      { name: 'Cumin', qty: '1 c.à.c' },
      { name: 'Cannelle', qty: '1 bâton' },
      { name: 'Cardamome', qty: '3 gousses' },
      { name: 'Clous de girofle', qty: '3' },
      { name: 'Safran ou curcuma', qty: '1 pincée' },
      { name: 'Beurre', qty: '40g' },
      { name: 'Coriandre, menthe fraîches', qty: '½ bouquet chaque' },
      { name: 'Lait chaud', qty: '4 c.à.s' }
    ],
    steps: [
      'Marine le poulet 30 min avec yaourt, ail-gingembre, garam masala.',
      'Fais frire un oignon en lamelles fines jusqu\'à brun croustillant. Réserve.',
      'Dans la même huile, fais cuire l\'autre oignon haché, puis le poulet 10 min.',
      'En parallèle, cuis le riz à 70% avec cannelle, cardamome, clous, sel.',
      'Trempe le safran dans le lait chaud.',
      'Dans une grande casserole, dispose : poulet → riz cuit → oignons frits → herbes → lait safrané → beurre.',
      'Couvre hermétiquement. Cuis 25 min à très feu doux (dum cooking).',
      'À la fin, mélange doucement et sers.'
    ],
    substitutions: [
      { from: 'Safran', to: 'Curcuma (couleur différente, goût voisin)' }
    ],
    coach_note: 'Plat festif indien. Long mais le résultat vaut chaque minute. Le secret : cuisson "dum" (étouffée).',
    photo_url: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&q=80',
    photo_gradient: 'linear-gradient(135deg,#fcbf49,#bb3e03)',
    membership_required: 'cookbook',
    featured: true
  },
  {
    title: 'Curry de Pois Chiches (Chana Masala)',
    category: 'main_meals',
    cuisine: 'indian',
    meal_type: 'lunch',
    goal_tag: 'cut',
    craving_tag: 'comfort',
    prep_time: 30,
    difficulty: 1,
    total_calories: 380,
    total_protein: 14,
    total_carbs: 58,
    total_fat: 10,
    ingredients: [
      { name: 'Pois chiches cuits', qty: '300g' },
      { name: 'Tomates concassées', qty: '300g' },
      { name: 'Oignon', qty: '1' },
      { name: 'Ail', qty: '3 gousses' },
      { name: 'Gingembre', qty: '1 c.à.s' },
      { name: 'Garam masala', qty: '1 c.à.s' },
      { name: 'Cumin', qty: '1 c.à.c' },
      { name: 'Curcuma', qty: '½ c.à.c' },
      { name: 'Coriandre en poudre', qty: '1 c.à.c' },
      { name: 'Huile', qty: '2 c.à.s' },
      { name: 'Coriandre fraîche', qty: '2 c.à.s' },
      { name: 'Citron', qty: '½' }
    ],
    steps: [
      'Chauffe l\'huile, ajoute cumin, fais griller 30 sec.',
      'Ajoute oignon haché, dorer 5 min.',
      'Ajoute ail, gingembre, tomates, épices restantes. Mijote 10 min.',
      'Ajoute pois chiches, un verre d\'eau. Mijote 15 min.',
      'Écrase légèrement quelques pois chiches pour épaissir.',
      'Coriandre, citron. Sers avec riz ou naan.'
    ],
    substitutions: [],
    coach_note: 'Plat 100% végétarien, ultra-rassasiant. 14g de protéines végétales.',
    photo_url: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=800&q=80',
    photo_gradient: 'linear-gradient(135deg,#bb3e03,#fcbf49)',
    membership_required: 'cookbook',
    featured: false
  },
  {
    title: 'Naan Maison (Pain Indien)',
    category: 'snacks',
    cuisine: 'indian',
    meal_type: 'snack',
    goal_tag: 'maintain',
    craving_tag: 'comfort',
    prep_time: 90,
    difficulty: 2,
    total_calories: 280,
    total_protein: 8,
    total_carbs: 42,
    total_fat: 8,
    ingredients: [
      { name: 'Farine', qty: '300g' },
      { name: 'Yaourt nature', qty: '4 c.à.s' },
      { name: 'Eau tiède', qty: '120ml' },
      { name: 'Levure boulangère', qty: '5g' },
      { name: 'Sel', qty: '5g' },
      { name: 'Huile', qty: '2 c.à.s' },
      { name: 'Beurre fondu', qty: '20g' },
      { name: 'Coriandre fraîche', qty: '2 c.à.s' },
      { name: 'Ail', qty: '2 gousses (facultatif)' }
    ],
    steps: [
      'Mélange farine, levure, sel.',
      'Ajoute yaourt, eau tiède, huile. Pétris 8 min, pâte souple.',
      'Repose 1h.',
      'Divise en 6 boules. Étale chaque en larme (forme ovale).',
      'Chauffe une poêle à sec très chaude.',
      'Cuis chaque naan 1 min par face — il doit gonfler par endroits.',
      'À la sortie, badigeonne de beurre fondu + ail râpé + coriandre (= ail naan).'
    ],
    substitutions: [
      { from: 'Yaourt', to: 'Lait fermenté' }
    ],
    coach_note: 'Le naan c\'est ce qui transforme un plat en festin. Tu peux les garder 2 jours dans un torchon.',
    photo_url: 'https://images.unsplash.com/photo-1633377-3-tagged-as-naan?w=800&q=80',
    photo_gradient: 'linear-gradient(135deg,#fcbf49,#dda15e)',
    membership_required: 'cookbook',
    featured: false
  },
  {
    title: 'Riz Pulao aux Légumes',
    category: 'main_meals',
    cuisine: 'indian',
    meal_type: 'dinner',
    goal_tag: 'maintain',
    craving_tag: 'comfort',
    prep_time: 35,
    difficulty: 1,
    total_calories: 420,
    total_protein: 10,
    total_carbs: 72,
    total_fat: 10,
    ingredients: [
      { name: 'Riz basmati', qty: '200g' },
      { name: 'Oignon', qty: '1' },
      { name: 'Carotte', qty: '1' },
      { name: 'Petits pois', qty: '80g' },
      { name: 'Pomme de terre', qty: '1' },
      { name: 'Cumin', qty: '1 c.à.c' },
      { name: 'Cannelle', qty: '1 bâton' },
      { name: 'Cardamome', qty: '3 gousses' },
      { name: 'Clous de girofle', qty: '3' },
      { name: 'Laurier', qty: '1 feuille' },
      { name: 'Huile ou beurre', qty: '2 c.à.s' },
      { name: 'Bouillon', qty: '400ml' },
      { name: 'Coriandre fraîche', qty: '2 c.à.s' }
    ],
    steps: [
      'Rince le riz à l\'eau froide jusqu\'à eau claire.',
      'Chauffe l\'huile, ajoute toutes les épices entières, fais griller 30 sec.',
      'Ajoute oignon, fais dorer 5 min.',
      'Ajoute les légumes en dés, mélange 3 min.',
      'Ajoute le riz, nacrer 1 min.',
      'Verse le bouillon chaud. Sale.',
      'Couvre, cuis 18 min à feu doux sans soulever.',
      'Repose 5 min, aère à la fourchette, coriandre.'
    ],
    substitutions: [],
    coach_note: 'Riz parfumé indien. Tu peux le servir seul ou en accompagnement.',
    photo_url: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=800&q=80',
    photo_gradient: 'linear-gradient(135deg,#fcbf49,#588157)',
    membership_required: 'cookbook',
    featured: false
  },
  {
    title: 'Saag Paneer (Épinards Fromage)',
    category: 'main_meals',
    cuisine: 'indian',
    meal_type: 'dinner',
    goal_tag: 'maintain',
    craving_tag: 'comfort',
    prep_time: 30,
    difficulty: 1,
    total_calories: 420,
    total_protein: 22,
    total_carbs: 18,
    total_fat: 28,
    ingredients: [
      { name: 'Épinards frais (ou surgelés)', qty: '500g' },
      { name: 'Fromage frais en cubes (style halloumi ou paneer maison)', qty: '200g' },
      { name: 'Oignon', qty: '1' },
      { name: 'Ail', qty: '3 gousses' },
      { name: 'Gingembre', qty: '1 c.à.s' },
      { name: 'Tomate', qty: '1' },
      { name: 'Garam masala', qty: '1 c.à.c' },
      { name: 'Cumin', qty: '1 c.à.c' },
      { name: 'Crème liquide', qty: '4 c.à.s' },
      { name: 'Beurre', qty: '20g' }
    ],
    steps: [
      'Fais tomber les épinards à l\'eau bouillante 2 min. Égoutte, mixe en purée.',
      'Fais dorer les cubes de fromage dans une poêle. Réserve.',
      'Dans la même poêle, fais revenir oignon, puis ail-gingembre, tomate, épices.',
      'Ajoute la purée d\'épinards. Mijote 8 min.',
      'Ajoute crème et beurre.',
      'Remets le fromage. Mélange doucement. Sers avec riz ou naan.'
    ],
    substitutions: [
      { from: 'Paneer', to: 'Halloumi, feta ferme, ou tofu' }
    ],
    coach_note: 'Si tu trouves pas de paneer, halloumi marche très bien. Plat indien végétarien classique.',
    photo_url: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=800&q=80',
    photo_gradient: 'linear-gradient(135deg,#588157,#dda15e)',
    membership_required: 'cookbook',
    featured: false
  },
  {
    title: 'Tandoori Chicken',
    category: 'main_meals',
    cuisine: 'indian',
    meal_type: 'dinner',
    goal_tag: 'cut',
    craving_tag: 'protein',
    prep_time: 50,
    difficulty: 2,
    total_calories: 380,
    total_protein: 52,
    total_carbs: 6,
    total_fat: 16,
    ingredients: [
      { name: 'Cuisses ou blancs de poulet', qty: '350g' },
      { name: 'Yaourt nature', qty: '5 c.à.s' },
      { name: 'Ail', qty: '4 gousses' },
      { name: 'Gingembre', qty: '1 c.à.s' },
      { name: 'Garam masala', qty: '1 c.à.s' },
      { name: 'Paprika', qty: '1 c.à.s' },
      { name: 'Cumin', qty: '1 c.à.c' },
      { name: 'Coriandre en poudre', qty: '1 c.à.c' },
      { name: 'Curcuma', qty: '½ c.à.c' },
      { name: 'Piment doux (facultatif)', qty: '½ c.à.c' },
      { name: 'Citron', qty: '1' },
      { name: 'Huile', qty: '1 c.à.s' }
    ],
    steps: [
      'Fais des entailles dans le poulet pour que la marinade pénètre.',
      'Mélange yaourt avec toutes les épices, ail râpé, gingembre, jus de citron, huile.',
      'Enrobe le poulet, marine 2h minimum (idéalement 6h ou nuit).',
      'Préchauffe le four à 220°C.',
      'Pose le poulet sur une grille, cuis 25 min en retournant à mi-cuisson.',
      'Finis 3 min sous le grill pour la couleur.',
      'Sers avec quartiers de citron, oignon cru.'
    ],
    substitutions: [],
    coach_note: 'Marinade longue = poulet ultra-tendre et savoureux. 52g de protéines pour 380 kcal.',
    photo_url: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&q=80',
    photo_gradient: 'linear-gradient(135deg,#bb3e03,#fcbf49)',
    membership_required: 'cookbook',
    featured: true
  },
  {
    title: 'Aloo Gobi (Curry Pommes de Terre & Chou-Fleur)',
    category: 'main_meals',
    cuisine: 'indian',
    meal_type: 'lunch',
    goal_tag: 'cut',
    craving_tag: 'comfort',
    prep_time: 35,
    difficulty: 1,
    total_calories: 280,
    total_protein: 8,
    total_carbs: 42,
    total_fat: 10,
    ingredients: [
      { name: 'Chou-fleur', qty: '½ chou' },
      { name: 'Pommes de terre', qty: '2' },
      { name: 'Oignon', qty: '1' },
      { name: 'Tomate', qty: '1' },
      { name: 'Ail', qty: '3 gousses' },
      { name: 'Gingembre', qty: '1 c.à.s' },
      { name: 'Cumin', qty: '1 c.à.c' },
      { name: 'Curcuma', qty: '1 c.à.c' },
      { name: 'Coriandre en poudre', qty: '1 c.à.c' },
      { name: 'Garam masala', qty: '½ c.à.c' },
      { name: 'Huile', qty: '2 c.à.s' },
      { name: 'Coriandre fraîche', qty: '2 c.à.s' }
    ],
    steps: [
      'Coupe chou-fleur en bouquets, patates en cubes.',
      'Fais chauffer huile, ajoute cumin.',
      'Ajoute oignon, dorer 5 min.',
      'Ajoute ail, gingembre, tomate, autres épices. Cuis 3 min.',
      'Ajoute légumes, mélange.',
      'Couvre, cuis 20 min à feu doux en remuant de temps en temps.',
      'Garam masala et coriandre fraîche en fin de cuisson.'
    ],
    substitutions: [],
    coach_note: 'Curry végétarien sec (sans sauce). Parfait avec du riz ou en accompagnement de poulet.',
    photo_url: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=800&q=80',
    photo_gradient: 'linear-gradient(135deg,#fcbf49,#588157)',
    membership_required: 'cookbook',
    featured: false
  },
  {
    title: 'Samoussas au Bœuf',
    category: 'snacks',
    cuisine: 'indian',
    meal_type: 'snack',
    goal_tag: 'maintain',
    craving_tag: 'comfort',
    prep_time: 60,
    difficulty: 2,
    total_calories: 320,
    total_protein: 16,
    total_carbs: 32,
    total_fat: 14,
    ingredients: [
      { name: 'Feuilles de brick', qty: '10' },
      { name: 'Viande hachée bœuf', qty: '200g' },
      { name: 'Pommes de terre', qty: '1' },
      { name: 'Petits pois', qty: '60g' },
      { name: 'Oignon', qty: '1' },
      { name: 'Ail', qty: '2 gousses' },
      { name: 'Gingembre', qty: '1 c.à.c' },
      { name: 'Garam masala', qty: '1 c.à.c' },
      { name: 'Cumin', qty: '1 c.à.c' },
      { name: 'Curcuma', qty: '½ c.à.c' },
      { name: 'Coriandre fraîche', qty: '2 c.à.s' },
      { name: 'Huile pour cuisson', qty: '2 c.à.s' },
      { name: 'Œuf battu (pour sceller)', qty: '1' }
    ],
    steps: [
      'Cuis la patate en dés à l\'eau 10 min, égoutte.',
      'Fais revenir oignon, ail, gingembre.',
      'Ajoute la viande, fais cuire jusqu\'à dorée.',
      'Ajoute épices, patate, petits pois. Cuis 5 min.',
      'Coriandre, laisse refroidir.',
      'Coupe feuilles de brick en triangles. Place farce au coin, plie en triangle, scelle à l\'œuf.',
      'Fais dorer dans une poêle huilée OU au four 15 min à 200°C.'
    ],
    substitutions: [
      { from: 'Feuilles de brick', to: 'Pâte filo' }
    ],
    coach_note: 'Les samoussas algériens reviennent à ça en fait. Cuisson au four = plus léger.',
    photo_url: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&q=80',
    photo_gradient: 'linear-gradient(135deg,#bb3e03,#fcbf49)',
    membership_required: 'cookbook',
    featured: false
  },
  {
    title: 'Curry d\'Agneau (Lamb Rogan Josh)',
    category: 'main_meals',
    cuisine: 'indian',
    meal_type: 'dinner',
    goal_tag: 'bulk',
    craving_tag: 'comfort',
    prep_time: 90,
    difficulty: 2,
    total_calories: 620,
    total_protein: 42,
    total_carbs: 22,
    total_fat: 38,
    ingredients: [
      { name: 'Épaule d\'agneau désossée', qty: '350g' },
      { name: 'Yaourt nature', qty: '4 c.à.s' },
      { name: 'Oignons', qty: '2' },
      { name: 'Ail', qty: '4 gousses' },
      { name: 'Gingembre', qty: '1 c.à.s' },
      { name: 'Tomates concassées', qty: '300g' },
      { name: 'Paprika fumé', qty: '1 c.à.s' },
      { name: 'Garam masala', qty: '1 c.à.s' },
      { name: 'Cumin, coriandre, fenouil moulus', qty: '1 c.à.c chaque' },
      { name: 'Cannelle', qty: '1 bâton' },
      { name: 'Cardamome', qty: '4 gousses' },
      { name: 'Huile', qty: '3 c.à.s' }
    ],
    steps: [
      'Coupe l\'agneau en cubes. Sale.',
      'Fais-le dorer dans l\'huile chaude. Réserve.',
      'Dans la même casserole, fais revenir oignons, cannelle, cardamome.',
      'Ajoute ail, gingembre, toutes les épices moulues. Cuis 2 min.',
      'Ajoute tomates et yaourt. Mijote 5 min.',
      'Remets l\'agneau, ajoute un verre d\'eau.',
      'Couvre et mijote 1h15 à très feu doux jusqu\'à viande très tendre.',
      'Ajuste l\'eau si nécessaire. Sers avec riz basmati.'
    ],
    substitutions: [
      { from: 'Agneau', to: 'Bœuf à mijoter (paleron)' }
    ],
    coach_note: 'Curry du Cachemire. Long mais incroyable. La viande devient fondante, parfumée.',
    photo_url: 'https://images.unsplash.com/photo-1606491048802-8342506d6471?w=800&q=80',
    photo_gradient: 'linear-gradient(135deg,#6f1d1b,#bb3e03)',
    membership_required: 'cookbook',
    featured: false
  },
  {
    title: 'Lassi Mangue',
    category: 'desserts',
    cuisine: 'indian',
    meal_type: 'snack',
    goal_tag: 'maintain',
    craving_tag: 'sweet',
    prep_time: 5,
    difficulty: 1,
    total_calories: 220,
    total_protein: 10,
    total_carbs: 32,
    total_fat: 6,
    ingredients: [
      { name: 'Yaourt nature', qty: '250g' },
      { name: 'Mangue mûre (ou en boîte)', qty: '150g' },
      { name: 'Lait', qty: '100ml' },
      { name: 'Miel ou sucre', qty: '1 c.à.s' },
      { name: 'Cardamome moulue', qty: '1 pincée' },
      { name: 'Glaçons', qty: '4-5' }
    ],
    steps: [
      'Mixe tous les ingrédients ensemble jusqu\'à lisse et mousseux.',
      'Verse dans des verres avec glaçons.',
      'Saupoudre légèrement de cardamome.'
    ],
    substitutions: [
      { from: 'Mangue', to: 'Banane ou pêche' }
    ],
    coach_note: 'Boisson rafraîchissante indienne. Parfaite pour calmer le piquant d\'un curry.',
    photo_url: 'https://images.unsplash.com/photo-1546173159-315724a31696?w=800&q=80',
    photo_gradient: 'linear-gradient(135deg,#fcbf49,#fb8500)',
    membership_required: 'cookbook',
    featured: false
  },
  {
    title: 'Poulet Vindaloo (Curry Épicé)',
    category: 'main_meals',
    cuisine: 'indian',
    meal_type: 'dinner',
    goal_tag: 'maintain',
    craving_tag: 'spicy',
    prep_time: 45,
    difficulty: 2,
    total_calories: 480,
    total_protein: 42,
    total_carbs: 18,
    total_fat: 28,
    ingredients: [
      { name: 'Blanc de poulet', qty: '300g' },
      { name: 'Oignons', qty: '2' },
      { name: 'Ail', qty: '5 gousses' },
      { name: 'Gingembre', qty: '1 c.à.s' },
      { name: 'Tomates concassées', qty: '200g' },
      { name: 'Vinaigre de cidre', qty: '2 c.à.s' },
      { name: 'Cumin', qty: '1 c.à.s' },
      { name: 'Paprika fumé', qty: '1 c.à.s' },
      { name: 'Piment en poudre', qty: '1 c.à.c (ajuste)' },
      { name: 'Curcuma', qty: '½ c.à.c' },
      { name: 'Cannelle', qty: '½ c.à.c' },
      { name: 'Clous de girofle', qty: '3' },
      { name: 'Cassonade', qty: '1 c.à.c' },
      { name: 'Huile', qty: '3 c.à.s' }
    ],
    steps: [
      'Coupe le poulet en cubes. Marine 20 min avec vinaigre, ail, gingembre, toutes les épices, sel.',
      'Chauffe huile, fais revenir oignons hachés 8 min.',
      'Ajoute le poulet et sa marinade. Fais saisir 5 min.',
      'Ajoute tomates et un verre d\'eau, cassonade.',
      'Couvre, mijote 30 min.',
      'Sers avec riz et yaourt nature pour calmer le piquant.'
    ],
    substitutions: [
      { from: 'Piment fort', to: 'Piment doux pour moins relevé' }
    ],
    coach_note: 'Pour les amateurs de piquant. Le vindaloo c\'est la spécialité de Goa.',
    photo_url: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&q=80',
    photo_gradient: 'linear-gradient(135deg,#9d0208,#bb3e03)',
    membership_required: 'cookbook',
    featured: false
  },
  {
    title: 'Aloo Paratha (Pain Garni Pomme de Terre)',
    category: 'breakfast',
    cuisine: 'indian',
    meal_type: 'breakfast',
    goal_tag: 'maintain',
    craving_tag: 'comfort',
    prep_time: 50,
    difficulty: 2,
    total_calories: 420,
    total_protein: 12,
    total_carbs: 68,
    total_fat: 12,
    ingredients: [
      { name: 'Farine complète ou blanche', qty: '250g' },
      { name: 'Pommes de terre', qty: '300g' },
      { name: 'Oignon', qty: '½' },
      { name: 'Coriandre fraîche', qty: '2 c.à.s' },
      { name: 'Cumin', qty: '1 c.à.c' },
      { name: 'Garam masala', qty: '½ c.à.c' },
      { name: 'Piment doux', qty: '½ c.à.c' },
      { name: 'Beurre ou ghee', qty: '30g' },
      { name: 'Eau', qty: '150ml' }
    ],
    steps: [
      'Mélange farine, sel, un peu d\'huile et eau. Pétris en pâte souple. Repose 20 min.',
      'Cuis patates, écrase. Mélange avec oignon haché, herbes, épices, sel.',
      'Divise pâte en 8 boules. Étale chaque en disque.',
      'Pose 2 c.à.s de farce au centre, referme en pliant, étale doucement en disque épais.',
      'Cuis dans une poêle chaude 2 min par côté avec un peu de beurre.',
      'Sers avec yaourt et achard (légumes confits épicés).'
    ],
    substitutions: [
      { from: 'Ghee', to: 'Beurre clarifié ou beurre normal' }
    ],
    coach_note: 'Petit-déj indien typique. Très rassasiant, parfait avant une longue journée.',
    photo_url: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=800&q=80',
    photo_gradient: 'linear-gradient(135deg,#dda15e,#fcbf49)',
    membership_required: 'cookbook',
    featured: false
  },
  {
    title: 'Curry de Crevettes Coco',
    category: 'main_meals',
    cuisine: 'indian',
    meal_type: 'dinner',
    goal_tag: 'cut',
    craving_tag: 'comfort',
    prep_time: 25,
    difficulty: 1,
    total_calories: 380,
    total_protein: 32,
    total_carbs: 18,
    total_fat: 20,
    ingredients: [
      { name: 'Crevettes décortiquées', qty: '250g' },
      { name: 'Lait de coco', qty: '200ml' },
      { name: 'Oignon', qty: '1' },
      { name: 'Ail', qty: '3 gousses' },
      { name: 'Gingembre', qty: '1 c.à.c' },
      { name: 'Tomate', qty: '1' },
      { name: 'Curry en poudre', qty: '1 c.à.s' },
      { name: 'Curcuma', qty: '½ c.à.c' },
      { name: 'Cumin', qty: '1 c.à.c' },
      { name: 'Citron vert', qty: '1' },
      { name: 'Coriandre fraîche', qty: '2 c.à.s' }
    ],
    steps: [
      'Fais revenir oignon, ail, gingembre.',
      'Ajoute tomate en dés, toutes les épices. Mijote 5 min.',
      'Verse le lait de coco. Mijote 5 min.',
      'Ajoute les crevettes, cuis 3-4 min (elles deviennent roses).',
      'Termine par jus de citron vert et coriandre.',
      'Sers avec riz basmati.'
    ],
    substitutions: [
      { from: 'Crevettes', to: 'Poisson blanc en cubes' }
    ],
    coach_note: 'Curry du Kerala (sud de l\'Inde). Léger et parfumé, 32g de protéines.',
    photo_url: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=800&q=80',
    photo_gradient: 'linear-gradient(135deg,#fcbf49,#a8dadc)',
    membership_required: 'cookbook',
    featured: false
  },
  {
    title: 'Raita au Concombre',
    category: 'snacks',
    cuisine: 'indian',
    meal_type: 'snack',
    goal_tag: 'cut',
    craving_tag: 'fresh',
    prep_time: 10,
    difficulty: 1,
    total_calories: 120,
    total_protein: 8,
    total_carbs: 12,
    total_fat: 4,
    ingredients: [
      { name: 'Yaourt nature', qty: '250g' },
      { name: 'Concombre', qty: '1' },
      { name: 'Menthe fraîche', qty: '8 feuilles' },
      { name: 'Coriandre fraîche', qty: '1 c.à.s' },
      { name: 'Cumin moulu', qty: '½ c.à.c' },
      { name: 'Citron', qty: '½' },
      { name: 'Sel', qty: 'au goût' }
    ],
    steps: [
      'Râpe le concombre, presse pour enlever l\'eau.',
      'Mélange yaourt avec concombre, menthe et coriandre hachées, cumin, jus de citron, sel.',
      'Réfrigère 15 min avant de servir.'
    ],
    substitutions: [],
    coach_note: 'Sauce indienne fraîche qui accompagne les currys épicés. 120 kcal seulement.',
    photo_url: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=800&q=80',
    photo_gradient: 'linear-gradient(135deg,#a8dadc,#588157)',
    membership_required: 'cookbook',
    featured: false
  },
  {
    title: 'Korma de Poulet (Curry Crémeux Doux)',
    category: 'main_meals',
    cuisine: 'indian',
    meal_type: 'dinner',
    goal_tag: 'bulk',
    craving_tag: 'comfort',
    prep_time: 40,
    difficulty: 2,
    total_calories: 580,
    total_protein: 42,
    total_carbs: 24,
    total_fat: 34,
    ingredients: [
      { name: 'Blanc de poulet', qty: '300g' },
      { name: 'Oignons', qty: '2' },
      { name: 'Yaourt nature', qty: '4 c.à.s' },
      { name: 'Crème liquide', qty: '100ml' },
      { name: 'Amandes en poudre', qty: '40g' },
      { name: 'Ail', qty: '3 gousses' },
      { name: 'Gingembre', qty: '1 c.à.s' },
      { name: 'Cardamome', qty: '4 gousses' },
      { name: 'Cannelle', qty: '1 bâton' },
      { name: 'Garam masala', qty: '1 c.à.c' },
      { name: 'Curcuma', qty: '½ c.à.c' },
      { name: 'Beurre', qty: '30g' }
    ],
    steps: [
      'Fais frire les oignons hachés jusqu\'à brun doré. Mixe en pâte.',
      'Coupe le poulet, fais-le dorer dans le beurre. Réserve.',
      'Dans la même poêle, ajoute la pâte d\'oignons, ail-gingembre, cardamome, cannelle, autres épices. Cuis 3 min.',
      'Ajoute yaourt, mélange.',
      'Remets le poulet. Ajoute crème et amandes en poudre.',
      'Mijote 15 min à feu doux.',
      'Sers avec riz basmati ou naan.'
    ],
    substitutions: [
      { from: 'Amandes en poudre', to: 'Cajou en poudre' }
    ],
    coach_note: 'Le korma c\'est le plat indien des fêtes royales. Crémeux, doux, parfumé.',
    photo_url: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=800&q=80',
    photo_gradient: 'linear-gradient(135deg,#fcbf49,#dda15e)',
    membership_required: 'cookbook',
    featured: false
  },
  {
    title: 'Soupe de Lentilles aux Épices (Mulligatawny)',
    category: 'main_meals',
    cuisine: 'indian',
    meal_type: 'lunch',
    goal_tag: 'cut',
    craving_tag: 'comfort',
    prep_time: 40,
    difficulty: 1,
    total_calories: 320,
    total_protein: 20,
    total_carbs: 42,
    total_fat: 8,
    ingredients: [
      { name: 'Lentilles corail', qty: '150g' },
      { name: 'Blanc de poulet en dés', qty: '100g' },
      { name: 'Oignon', qty: '1' },
      { name: 'Carotte', qty: '1' },
      { name: 'Céleri', qty: '1 branche' },
      { name: 'Ail', qty: '2 gousses' },
      { name: 'Gingembre', qty: '1 c.à.c' },
      { name: 'Curry en poudre', qty: '1 c.à.s' },
      { name: 'Curcuma', qty: '½ c.à.c' },
      { name: 'Lait de coco', qty: '100ml' },
      { name: 'Bouillon', qty: '800ml' },
      { name: 'Citron', qty: '½' }
    ],
    steps: [
      'Fais revenir oignon, carotte, céleri, ail, gingembre 5 min.',
      'Ajoute épices, mélange 1 min.',
      'Ajoute lentilles, poulet, bouillon. Mijote 25 min.',
      'Mixe légèrement (laisse des morceaux) ou laisse entière selon préférence.',
      'Ajoute lait de coco et jus de citron.',
      'Sers chaud avec coriandre fraîche.'
    ],
    substitutions: [],
    coach_note: 'Soupe anglo-indienne. 20g de protéines pour 320 kcal — idéale en cut.',
    photo_url: 'https://images.unsplash.com/photo-1547308283-b941b6e95cb1?w=800&q=80',
    photo_gradient: 'linear-gradient(135deg,#fcbf49,#bb3e03)',
    membership_required: 'cookbook',
    featured: false
  },
  {
    title: 'Pakoras (Beignets Légumes Épicés)',
    category: 'snacks',
    cuisine: 'indian',
    meal_type: 'snack',
    goal_tag: 'maintain',
    craving_tag: 'comfort',
    prep_time: 30,
    difficulty: 1,
    total_calories: 240,
    total_protein: 8,
    total_carbs: 28,
    total_fat: 12,
    ingredients: [
      { name: 'Farine de pois chiches (ou farine classique)', qty: '100g' },
      { name: 'Oignon en lamelles', qty: '1' },
      { name: 'Pomme de terre râpée', qty: '1 petite' },
      { name: 'Épinards hachés', qty: '50g' },
      { name: 'Cumin', qty: '1 c.à.c' },
      { name: 'Curcuma', qty: '½ c.à.c' },
      { name: 'Coriandre en poudre', qty: '1 c.à.c' },
      { name: 'Piment en poudre', qty: '½ c.à.c' },
      { name: 'Bicarbonate', qty: '1 pincée' },
      { name: 'Eau', qty: '100ml' },
      { name: 'Huile pour cuisson', qty: '3 c.à.s' },
      { name: 'Coriandre fraîche', qty: '1 c.à.s' }
    ],
    steps: [
      'Mélange farine avec épices, bicarbonate, sel.',
      'Ajoute eau progressivement pour une pâte épaisse comme une crêpe.',
      'Ajoute légumes et coriandre, mélange.',
      'Chauffe l\'huile dans une poêle.',
      'Verse des c.à.s de pâte, fais cuire 3 min par face jusqu\'à doré.',
      'Égoutte sur papier absorbant. Sers chaud avec sauce tamarin ou yaourt.'
    ],
    substitutions: [
      { from: 'Farine de pois chiches', to: 'Farine + 1 c.à.c bicarbonate de plus' }
    ],
    coach_note: 'Beignets indiens au four (au lieu de friture). Moins gras, toujours bons.',
    photo_url: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?w=800&q=80',
    photo_gradient: 'linear-gradient(135deg,#bc6c25,#fcbf49)',
    membership_required: 'cookbook',
    featured: false
  },
  {
    title: 'Riz au Citron (Lemon Rice)',
    category: 'quick_meals',
    cuisine: 'indian',
    meal_type: 'lunch',
    goal_tag: 'maintain',
    craving_tag: 'fresh',
    prep_time: 20,
    difficulty: 1,
    total_calories: 380,
    total_protein: 8,
    total_carbs: 62,
    total_fat: 10,
    ingredients: [
      { name: 'Riz basmati cuit', qty: '200g' },
      { name: 'Citrons', qty: '2' },
      { name: 'Cacahuètes nature', qty: '20g' },
      { name: 'Curcuma', qty: '½ c.à.c' },
      { name: 'Cumin', qty: '1 c.à.c' },
      { name: 'Moutarde en graines', qty: '½ c.à.c' },
      { name: 'Gingembre', qty: '1 c.à.c' },
      { name: 'Piment vert', qty: '1' },
      { name: 'Coriandre fraîche', qty: '2 c.à.s' },
      { name: 'Huile', qty: '2 c.à.s' }
    ],
    steps: [
      'Chauffe l\'huile, ajoute moutarde en graines (elles pétillent), cumin, cacahuètes.',
      'Fais griller 1 min.',
      'Ajoute gingembre râpé, piment haché, curcuma.',
      'Verse sur le riz cuit dans un grand bol.',
      'Ajoute jus des 2 citrons, sel.',
      'Mélange délicatement, parsème de coriandre.'
    ],
    substitutions: [
      { from: 'Cacahuètes', to: 'Amandes' }
    ],
    coach_note: 'Riz indien sud très parfumé. Idéal pour utiliser un reste de riz.',
    photo_url: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=800&q=80',
    photo_gradient: 'linear-gradient(135deg,#fcbf49,#588157)',
    membership_required: 'cookbook',
    featured: false
  },
  {
    title: 'Poulet Madras',
    category: 'main_meals',
    cuisine: 'indian',
    meal_type: 'dinner',
    goal_tag: 'maintain',
    craving_tag: 'spicy',
    prep_time: 40,
    difficulty: 2,
    total_calories: 540,
    total_protein: 44,
    total_carbs: 22,
    total_fat: 30,
    ingredients: [
      { name: 'Cuisses de poulet désossées', qty: '300g' },
      { name: 'Oignons', qty: '2' },
      { name: 'Ail', qty: '4 gousses' },
      { name: 'Gingembre', qty: '1 c.à.s' },
      { name: 'Tomates concassées', qty: '300g' },
      { name: 'Lait de coco', qty: '150ml' },
      { name: 'Curry de Madras (mélange)', qty: '2 c.à.s' },
      { name: 'Cumin', qty: '1 c.à.c' },
      { name: 'Coriandre poudre', qty: '1 c.à.c' },
      { name: 'Paprika', qty: '1 c.à.c' },
      { name: 'Piment doux', qty: '1 c.à.c' },
      { name: 'Huile', qty: '3 c.à.s' }
    ],
    steps: [
      'Fais revenir oignons hachés 8 min jusqu\'à dorés.',
      'Ajoute ail-gingembre, toutes les épices. Cuis 2 min.',
      'Ajoute le poulet en morceaux, fais saisir 5 min.',
      'Ajoute tomates et un verre d\'eau.',
      'Couvre, mijote 25 min.',
      'Termine par lait de coco, mijote 5 min.',
      'Sers avec riz basmati et yaourt.'
    ],
    substitutions: [
      { from: 'Curry de Madras', to: 'Curry classique + ½ c.à.c piment fort' }
    ],
    coach_note: 'Curry du sud de l\'Inde, plus relevé que le tikka masala mais plus doux que le vindaloo.',
    photo_url: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&q=80',
    photo_gradient: 'linear-gradient(135deg,#bb3e03,#9d0208)',
    membership_required: 'cookbook',
    featured: false
  },
  {
    title: 'Riz au Lait Cardamome (Kheer)',
    category: 'desserts',
    cuisine: 'indian',
    meal_type: 'snack',
    goal_tag: 'maintain',
    craving_tag: 'sweet',
    prep_time: 45,
    difficulty: 1,
    total_calories: 280,
    total_protein: 8,
    total_carbs: 48,
    total_fat: 6,
    ingredients: [
      { name: 'Riz rond ou basmati', qty: '60g' },
      { name: 'Lait', qty: '700ml' },
      { name: 'Sucre', qty: '40g' },
      { name: 'Cardamome moulue', qty: '½ c.à.c' },
      { name: 'Amandes effilées', qty: '20g' },
      { name: 'Raisins secs', qty: '20g' },
      { name: 'Pistaches concassées', qty: '10g' },
      { name: 'Safran', qty: '1 pincée (facultatif)' }
    ],
    steps: [
      'Rince le riz, fais-le cuire dans le lait à feu très doux 40 min en remuant souvent.',
      'Quand le riz est tendre et le lait crémeux, ajoute sucre, cardamome, raisins, safran.',
      'Cuis encore 5 min.',
      'Sers chaud ou froid, garni d\'amandes et pistaches.'
    ],
    substitutions: [
      { from: 'Pistaches', to: 'Noix concassées' }
    ],
    coach_note: 'Dessert indien similaire au mhalbi algérien. Parfumé et réconfortant.',
    photo_url: 'https://images.unsplash.com/photo-1631815589968-fdb09a223b1e?w=800&q=80',
    photo_gradient: 'linear-gradient(135deg,#fefae0,#dda15e)',
    membership_required: 'cookbook',
    featured: false
  },
  {
    title: 'Saumon Tandoori',
    category: 'main_meals',
    cuisine: 'indian',
    meal_type: 'dinner',
    goal_tag: 'cut',
    craving_tag: 'protein',
    prep_time: 25,
    difficulty: 1,
    total_calories: 380,
    total_protein: 36,
    total_carbs: 6,
    total_fat: 22,
    ingredients: [
      { name: 'Filet de saumon', qty: '200g' },
      { name: 'Yaourt nature', qty: '3 c.à.s' },
      { name: 'Ail', qty: '2 gousses' },
      { name: 'Gingembre', qty: '1 c.à.c' },
      { name: 'Garam masala', qty: '1 c.à.c' },
      { name: 'Paprika', qty: '1 c.à.c' },
      { name: 'Cumin', qty: '½ c.à.c' },
      { name: 'Curcuma', qty: '¼ c.à.c' },
      { name: 'Citron', qty: '1' },
      { name: 'Huile', qty: '1 c.à.s' }
    ],
    steps: [
      'Mélange yaourt, ail-gingembre râpés, toutes les épices, jus de citron, huile, sel.',
      'Marine le saumon 20 min.',
      'Cuis au four à 220°C pendant 12 min, ou à la poêle 4 min par côté.',
      'Sers avec quartiers de citron, raita au concombre et riz basmati.'
    ],
    substitutions: [
      { from: 'Saumon', to: 'Thon ou cabillaud' }
    ],
    coach_note: 'Saumon façon tandoori — 36g de protéines + oméga 3. Cuisson rapide.',
    photo_url: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80',
    photo_gradient: 'linear-gradient(135deg,#bb3e03,#fcbf49)',
    membership_required: 'cookbook',
    featured: false
  },
  {
    title: 'Curry Œufs Indien (Egg Curry)',
    category: 'main_meals',
    cuisine: 'indian',
    meal_type: 'dinner',
    goal_tag: 'maintain',
    craving_tag: 'comfort',
    prep_time: 30,
    difficulty: 1,
    total_calories: 380,
    total_protein: 22,
    total_carbs: 22,
    total_fat: 24,
    ingredients: [
      { name: 'Œufs', qty: '6' },
      { name: 'Oignons', qty: '2' },
      { name: 'Tomates concassées', qty: '300g' },
      { name: 'Ail', qty: '3 gousses' },
      { name: 'Gingembre', qty: '1 c.à.s' },
      { name: 'Garam masala', qty: '1 c.à.c' },
      { name: 'Cumin', qty: '1 c.à.c' },
      { name: 'Curcuma', qty: '½ c.à.c' },
      { name: 'Coriandre poudre', qty: '1 c.à.c' },
      { name: 'Huile', qty: '2 c.à.s' },
      { name: 'Coriandre fraîche', qty: '2 c.à.s' }
    ],
    steps: [
      'Cuis les œufs durs 8 min. Écale.',
      'Fais cuire oignons hachés 8 min jusqu\'à dorés.',
      'Ajoute ail-gingembre, tomates, épices. Mijote 10 min.',
      'Mixe pour avoir une sauce lisse (facultatif).',
      'Remets sur le feu, ajoute les œufs durs entiers ou coupés en deux.',
      'Mijote 5 min pour imprégner.',
      'Coriandre. Sers avec riz.'
    ],
    substitutions: [],
    coach_note: 'Curry végétarien avec œufs durs. Économique et savoureux.',
    photo_url: 'https://images.unsplash.com/photo-1604908554007-fdca4f4b1de1?w=800&q=80',
    photo_gradient: 'linear-gradient(135deg,#fcbf49,#bb3e03)',
    membership_required: 'cookbook',
    featured: false
  }
]

console.log(`Seeding ${recipes.length} Indian recipes...`)

let success = 0
let failed = 0

for (const r of recipes) {
  const { error } = await sb.from('cookbook_recipes').insert(r)
  if (error) {
    console.error(`❌ ${r.title}:`, error.message)
    failed++
  } else {
    console.log(`✓ ${r.title}`)
    success++
  }
}

console.log(`\n✨ Done. ${success} inserted, ${failed} failed.`)
